<?php
declare(strict_types=1);

$topicOptions = [
    'Introduction' => 'Introduction',
    'Numbers' => 'Numbers',
    'Family' => 'Family',
    'Food' => 'Food',
    'Shopping' => 'Shopping',
    'Colors/Objects' => 'Colors/Objects',
    'Places/Directions' => 'Places/Directions',
    'Routine' => 'Routine',
    'Work' => 'Work',
    'Health' => 'Health',
];

return [
    'unit_type' => 'final_review',
    'lesson_number' => 103,
    'display_label' => 'Final Review',
    'title_en' => 'Final Review',
    'title_ar' => 'المُراجَعَة النِّهائِيَّة',
    'slug' => 'final-review-beginner',
    'submit_label' => 'Submit Final Review',
    'goal_en' => 'This is your final review for the Beginner book. You will use Arabic from all 12 lessons to complete listening, reading, writing, and speaking tasks.',
    'goal_ar' => 'هذه هي المراجعة النهائية لكتاب المبتدئ. ستستخدم اللغة العربية من كل الدروس الـ 12 لإكمال تدريبات الاستماع، القراءة، الكتابة، والتحدث.',
    'goal_checks' => [
        'Understand simple Arabic questions.',
        'Recognize key daily-life vocabulary.',
        'Complete basic Arabic sentences.',
        'Write a short self-introduction.',
        'Write a simple daily-life scenario response.',
        'Record a clear self-introduction.',
        'Record a practical role-play.',
        'Use Arabic from multiple topics together.',
    ],
    'situation_en' => 'This is the final checkpoint for Arabic for Daily Life - Beginner Level. Complete all auto-graded and teacher-reviewed tasks.',
    'situation_ar' => 'هذه هي نقطة التقييم النهائية لكتاب العربية للحياة اليومية - المستوى المبتدئ. أكمل كل تدريبات التصحيح التلقائي والتدريبات التي يراجعها المدرّس.',
    'safety_disclaimer_en' => 'For practice, you can use fake personal information. Do not share private phone numbers, addresses, or medical details. This review is for language practice only and is not medical advice.',
    'safety_disclaimer_ar' => 'للتدريب، يمكنك استخدام معلومات شخصية غير حقيقية. لا تشارك أرقام هاتف أو عناوين أو تفاصيل طبية خاصة. هذه المراجعة للتدريب اللغوي فقط وليست نصيحة طبية.',
    'warmup_title' => 'Final Review Instructions',
    'warmup_questions' => [
        'Which topic do you feel strongest in?',
        'Which topic do you want your teacher to review carefully?',
        'What is your speaking goal for the final review?',
    ],
    'review_overview' => [
        ['title' => 'Introduction', 'items' => ['أَنا اسْمي...', 'ما اسْمُكَ؟', 'أَنا مِن...', 'أَنا أَعيشُ في...']],
        ['title' => 'Numbers & Personal Info', 'items' => ['عُمْري...', 'رَقْمُ هاتِفي...', 'Numbers 0-20']],
        ['title' => 'Family', 'items' => ['عائِلَتي...', 'عِنْدي...', 'لَيْسَ عِنْدي...']],
        ['title' => 'Food & Shopping', 'items' => ['أُريد...', 'لا أُريد...', 'هذا بِكَم؟', 'غالي / رَخيص']],
        ['title' => 'Colors, Objects & Places', 'items' => ['هذا قَلَم أَحْمَر.', 'هذه حَقيبَة زَرْقاء.', 'أَنا في البَيْت.', 'بَيْتي قَريب مِن...']],
        ['title' => 'Directions, Routine, Work & Health', 'items' => ['أَيْنَ...؟', 'لُفّ يَمين / يَسار', 'أَصْحو...', 'أَعْمَلُ في...', 'عِنْدي أَلَم في...']],
    ],
    'vocabulary' => [
        ['key' => 'ana', 'arabic' => 'أَنا', 'pronunciation' => 'ana', 'meaning' => 'I', 'category' => 'Introduction', 'example' => 'أَنا اسْمي أَحْمَد.'],
        ['key' => 'ism', 'arabic' => 'اِسْم', 'pronunciation' => 'ism', 'meaning' => 'name', 'category' => 'Introduction', 'example' => 'ما اسْمُكَ؟'],
        ['key' => 'aeeshu', 'arabic' => 'أَعيشُ', 'pronunciation' => "a'eeshu", 'meaning' => 'I live', 'category' => 'Introduction', 'example' => 'أَنا أَعيشُ في دُبَي.'],
        ['key' => 'balad', 'arabic' => 'بَلَد', 'pronunciation' => 'balad', 'meaning' => 'country', 'category' => 'Personal Info', 'example' => 'أَنا مِن بَلَد جَميل.'],
        ['key' => 'madeenah', 'arabic' => 'مَدينَة', 'pronunciation' => 'madeenah', 'meaning' => 'city', 'category' => 'Personal Info', 'example' => 'دُبَي مَدينَة.'],
        ['key' => 'umr', 'arabic' => 'عُمْر', 'pronunciation' => 'umr', 'meaning' => 'age', 'category' => 'Numbers', 'example' => 'عُمْري عِشْرون سَنَة.'],
        ['key' => 'raqm', 'arabic' => 'رَقْم', 'pronunciation' => 'raqm', 'meaning' => 'number', 'category' => 'Numbers', 'example' => 'رَقْمُ هاتِفي...'],
        ['key' => 'haatif', 'arabic' => 'هاتِف', 'pronunciation' => 'haatif', 'meaning' => 'phone', 'category' => 'Numbers', 'example' => 'هذا هاتِف.'],
        ['key' => 'usrah', 'arabic' => 'أُسْرَة', 'pronunciation' => 'usrah', 'meaning' => 'family', 'category' => 'Family', 'example' => 'أُسْرَتي صَغيرَة.'],
        ['key' => 'aa_ilah', 'arabic' => 'عائِلَة', 'pronunciation' => "aa'ilah", 'meaning' => 'family', 'category' => 'Family', 'example' => 'عائِلَتي كَبيرَة.'],
        ['key' => 'ab', 'arabic' => 'أَب', 'pronunciation' => 'ab', 'meaning' => 'father', 'category' => 'Family', 'example' => 'عِنْدي أَب.'],
        ['key' => 'umm', 'arabic' => 'أُم', 'pronunciation' => 'umm', 'meaning' => 'mother', 'category' => 'Family', 'example' => 'عِنْدي أُم.'],
        ['key' => 'akh', 'arabic' => 'أَخ', 'pronunciation' => 'akh', 'meaning' => 'brother', 'category' => 'Family', 'example' => 'عِنْدي أَخ.'],
        ['key' => 'ukht', 'arabic' => 'أُخْت', 'pronunciation' => 'ukht', 'meaning' => 'sister', 'category' => 'Family', 'example' => 'عِنْدي أُخْت.'],
        ['key' => 'maa', 'arabic' => 'ماء', 'pronunciation' => "maa'", 'meaning' => 'water', 'category' => 'Food', 'example' => 'أُريد ماءً.'],
        ['key' => 'shaay', 'arabic' => 'شاي', 'pronunciation' => 'shaay', 'meaning' => 'tea', 'category' => 'Food', 'example' => 'أُريد شايًا.'],
        ['key' => 'qahwah', 'arabic' => 'قَهْوَة', 'pronunciation' => 'qahwah', 'meaning' => 'coffee', 'category' => 'Food', 'example' => 'أُريد قَهْوَة.'],
        ['key' => 'dajaaj', 'arabic' => 'دَجاج', 'pronunciation' => 'dajaaj', 'meaning' => 'chicken', 'category' => 'Food', 'example' => 'أُريد دَجاجًا.'],
        ['key' => 'aruzz', 'arabic' => 'أَرُزّ', 'pronunciation' => 'aruzz', 'meaning' => 'rice', 'category' => 'Food', 'example' => 'أُريد أَرُزًّا.'],
        ['key' => 'ureed', 'arabic' => 'أُريد', 'pronunciation' => 'ureed', 'meaning' => 'I want', 'category' => 'Food/Shopping', 'example' => 'أُريد هذا.'],
        ['key' => 'bikam', 'arabic' => 'بِكَم؟', 'pronunciation' => 'bikam?', 'meaning' => 'how much?', 'category' => 'Shopping', 'example' => 'هذا بِكَم؟'],
        ['key' => 'sir', 'arabic' => 'سِعْر', 'pronunciation' => 'sir', 'meaning' => 'price', 'category' => 'Shopping', 'example' => 'السِّعْر عَشَرَة دَراهِم.'],
        ['key' => 'ghaali', 'arabic' => 'غالي', 'pronunciation' => 'ghaali', 'meaning' => 'expensive', 'category' => 'Shopping', 'example' => 'هذا غالي.'],
        ['key' => 'rakhees', 'arabic' => 'رَخيص', 'pronunciation' => 'rakhees', 'meaning' => 'cheap', 'category' => 'Shopping', 'example' => 'هذا رَخيص.'],
        ['key' => 'ahmar', 'arabic' => 'أَحْمَر', 'pronunciation' => 'ahmar', 'meaning' => 'red', 'category' => 'Colors', 'example' => 'قَلَم أَحْمَر.'],
        ['key' => 'azraq', 'arabic' => 'أَزْرَق', 'pronunciation' => 'azraq', 'meaning' => 'blue', 'category' => 'Colors', 'example' => 'كِتاب أَزْرَق.'],
        ['key' => 'qalam', 'arabic' => 'قَلَم', 'pronunciation' => 'qalam', 'meaning' => 'pen', 'category' => 'Objects', 'example' => 'هذا قَلَم.'],
        ['key' => 'haqeebah', 'arabic' => 'حَقيبَة', 'pronunciation' => 'haqeebah', 'meaning' => 'bag', 'category' => 'Objects', 'example' => 'هذه حَقيبَة.'],
        ['key' => 'bayt', 'arabic' => 'بَيْت', 'pronunciation' => 'bayt', 'meaning' => 'home', 'category' => 'Places', 'example' => 'أَنا في البَيْت.'],
        ['key' => 'saydaliyyah', 'arabic' => 'صَيْدَلِيَّة', 'pronunciation' => 'saydaliyyah', 'meaning' => 'pharmacy', 'category' => 'Places', 'example' => 'أَيْنَ الصَّيْدَلِيَّة؟'],
        ['key' => 'ayna', 'arabic' => 'أَيْنَ؟', 'pronunciation' => 'ayna?', 'meaning' => 'where?', 'category' => 'Directions', 'example' => 'أَيْنَ المَطْعَم؟'],
        ['key' => 'yameen', 'arabic' => 'يَمين', 'pronunciation' => 'yameen', 'meaning' => 'right', 'category' => 'Directions', 'example' => 'لُفّ يَمين.'],
        ['key' => 'yasaar', 'arabic' => 'يَسار', 'pronunciation' => 'yasaar', 'meaning' => 'left', 'category' => 'Directions', 'example' => 'لُفّ يَسار.'],
        ['key' => 'as_saaah', 'arabic' => 'السّاعَة', 'pronunciation' => "as-saa'ah", 'meaning' => 'time / o’clock', 'category' => 'Routine', 'example' => 'السّاعَة سَبْعَة.'],
        ['key' => 'asbaho', 'arabic' => 'أَصْحو', 'pronunciation' => 'as-ho', 'meaning' => 'I wake up', 'category' => 'Routine', 'example' => 'أَصْحو في السّاعَة سَبْعَة.'],
        ['key' => 'amal', 'arabic' => 'عَمَل', 'pronunciation' => 'amal', 'meaning' => 'work', 'category' => 'Work', 'example' => 'أَذْهَبُ إِلى العَمَل.'],
        ['key' => 'ahtaaju', 'arabic' => 'أَحتاجُ', 'pronunciation' => 'ahtaaju', 'meaning' => 'I need', 'category' => 'Health', 'example' => 'أَحتاجُ مُساعَدَة.'],
        ['key' => 'alam', 'arabic' => 'أَلَم', 'pronunciation' => 'alam', 'meaning' => 'pain', 'category' => 'Health', 'example' => 'عِنْدي أَلَم.'],
        ['key' => 'tabeeb', 'arabic' => 'طَبيب', 'pronunciation' => 'tabeeb', 'meaning' => 'doctor', 'category' => 'Health', 'example' => 'أَحتاجُ طَبيبًا.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Final Review Vocabulary', 'key' => 'B1-FR-Core-Vocab', 'file' => '/assets/audio/books/beginner/final-review/B1-FR-Core-Vocab.mp3'],
        ['title' => 'Audio Practice - Final Review Listening', 'key' => 'B1-FR-Listening', 'file' => '/assets/audio/books/beginner/final-review/B1-FR-Listening.mp3'],
    ],
    'sentences' => [
        ['ar' => 'أَنا اسْمي أَحْمَد.', 'en' => 'My name is Ahmed.'],
        ['ar' => 'عُمْري عِشْرون سَنَة.', 'en' => 'I am twenty years old.'],
        ['ar' => 'عِنْدي أَخ وَأُخْت.', 'en' => 'I have a brother and sister.'],
        ['ar' => 'أُريد ماءً وَقَهْوَة.', 'en' => 'I want water and coffee.'],
        ['ar' => 'هذا القَلَم بِكَم؟', 'en' => 'How much is this pen?'],
        ['ar' => 'هذه حَقيبَة زَرْقاء.', 'en' => 'This is a blue bag.'],
        ['ar' => 'أَيْنَ الصَّيْدَلِيَّة؟', 'en' => 'Where is the pharmacy?'],
        ['ar' => 'أَصْحو في السّاعَة سَبْعَة.', 'en' => 'I wake up at seven o’clock.'],
        ['ar' => 'أَنا أَعْمَلُ في شَرِكَة.', 'en' => 'I work in a company.'],
        ['ar' => 'عِنْدي أَلَم في الرَّأْس.', 'en' => 'I have pain in my head.'],
    ],
    'grammar_tip' => [
        'title' => 'Final Review Strategy',
        'body' => 'Use short, clear Arabic sentences. Combine one sentence from each topic: introduction, personal information, family, food, shopping, places, directions, routine, work, and health.',
        'examples' => [
            ['ar' => 'أَنا اسْمي أَحْمَد.', 'en' => 'My name is Ahmed.'],
            ['ar' => 'أُريد ماءً.', 'en' => 'I want water.'],
            ['ar' => 'أَيْنَ الصَّيْدَلِيَّة؟', 'en' => 'Where is the pharmacy?'],
            ['ar' => 'أَحتاجُ مُساعَدَة.', 'en' => 'I need help.'],
        ],
    ],
    'dialogue_ar' => [
        'السَّلامُ عَلَيْكُم.',
        'أَنا اسْمي أَحْمَد.',
        'أَنا مِن مِصْر، وَأَعيشُ في دُبَي.',
        'عُمْري عِشْرون سَنَة.',
        'عائِلَتي صَغيرَة. عِنْدي أَب وَأُم وَأَخ.',
        'أَنا أَعْمَلُ في شَرِكَة في دُبَي.',
        'أَصْحو في السّاعَة سَبْعَة، ثُمَّ أَذْهَبُ إِلى العَمَل.',
        'في المَساء، أَدْرُسُ العَرَبِيَّة.',
        'بَيْتي قَريب مِن المَوْل.',
        'أُريد ماءً وَقَهْوَة.',
        'أَنا مُتْعَب قَليلًا، وَعِنْدي أَلَم في الرَّأْس.',
    ],
    'dialogue_en' => [
        'Peace be upon you.',
        'My name is Ahmed.',
        'I am from Egypt, and I live in Dubai.',
        'I am twenty years old.',
        'My family is small. I have a father, mother, and brother.',
        'I work in a company in Dubai.',
        'I wake up at seven, then I go to work.',
        'In the evening, I study Arabic.',
        'My home is near the mall.',
        'I want water and coffee.',
        'I am a little tired, and I have pain in my head.',
    ],
    'listening_review' => [
        ['id' => 'listen_1', 'question' => 'What did you hear?', 'options' => ['A' => 'My name is Ahmed.', 'B' => 'I live in Dubai.', 'C' => 'I want water.'], 'correct' => 'A'],
        ['id' => 'listen_2', 'question' => 'What did you hear?', 'options' => ['A' => 'I have a brother.', 'B' => 'I am twenty years old.', 'C' => 'I work in a company.'], 'correct' => 'B'],
        ['id' => 'listen_3', 'question' => 'What did you hear?', 'options' => ['A' => 'I have a father and mother.', 'B' => 'I have a brother and sister.', 'C' => 'I do not have a sister.'], 'correct' => 'B'],
        ['id' => 'listen_4', 'question' => 'What did you hear?', 'options' => ['A' => 'I want water and coffee.', 'B' => 'I want chicken and rice.', 'C' => 'I want the bill.'], 'correct' => 'A'],
        ['id' => 'listen_5', 'question' => 'What did you hear?', 'options' => ['A' => 'How much is this pen?', 'B' => 'Where is this pen?', 'C' => 'What color is this pen?'], 'correct' => 'A'],
        ['id' => 'listen_6', 'question' => 'What did you hear?', 'options' => ['A' => 'This is a red car.', 'B' => 'This is a blue bag.', 'C' => 'This is a black phone.'], 'correct' => 'B'],
        ['id' => 'listen_7', 'question' => 'What did you hear?', 'options' => ['A' => 'Where is the pharmacy?', 'B' => 'Where is the restaurant?', 'C' => 'Where is the mall?'], 'correct' => 'A'],
        ['id' => 'listen_8', 'question' => 'What did you hear?', 'options' => ['A' => 'I sleep at night.', 'B' => 'I wake up at seven o’clock.', 'C' => 'I study Arabic in the evening.'], 'correct' => 'B'],
        ['id' => 'listen_9', 'question' => 'What did you hear?', 'options' => ['A' => 'I work in a company.', 'B' => 'I need help.', 'C' => 'I have a meeting.'], 'correct' => 'A'],
        ['id' => 'listen_10', 'question' => 'What did you hear?', 'options' => ['A' => 'I have stomach pain.', 'B' => 'I need a doctor.', 'C' => 'I have pain in my head.'], 'correct' => 'C'],
    ],
    'reading_comprehension' => [
        ['id' => 'read_1', 'question' => 'What is the person’s name?', 'options' => ['A' => 'Ahmed', 'B' => 'Omar', 'C' => 'Ali'], 'correct' => 'A'],
        ['id' => 'read_2', 'question' => 'Where is he from?', 'options' => ['A' => 'Dubai', 'B' => 'Egypt', 'C' => 'Saudi Arabia'], 'correct' => 'B'],
        ['id' => 'read_3', 'question' => 'Where does he live?', 'options' => ['A' => 'Cairo', 'B' => 'Dubai', 'C' => 'Sharjah'], 'correct' => 'B'],
        ['id' => 'read_4', 'question' => 'What does he have in his family?', 'options' => ['A' => 'Father, mother, and brother', 'B' => 'Father and sister', 'C' => 'Wife and children'], 'correct' => 'A'],
        ['id' => 'read_5', 'question' => 'Where does he work?', 'options' => ['A' => 'In a school', 'B' => 'In a company', 'C' => 'In a shop'], 'correct' => 'B'],
        ['id' => 'read_6', 'question' => 'What time does he wake up?', 'options' => ['A' => 'Seven o’clock', 'B' => 'Eight o’clock', 'C' => 'Ten o’clock'], 'correct' => 'A'],
        ['id' => 'read_7', 'question' => 'What does he study in the evening?', 'options' => ['A' => 'English', 'B' => 'Arabic', 'C' => 'Math'], 'correct' => 'B'],
        ['id' => 'read_8', 'question' => 'What is near his home?', 'options' => ['A' => 'The mall', 'B' => 'The hospital', 'C' => 'The school'], 'correct' => 'A'],
        ['id' => 'read_9', 'question' => 'What does he want?', 'options' => ['A' => 'Water and coffee', 'B' => 'Chicken and rice', 'C' => 'Tea and juice'], 'correct' => 'A'],
        ['id' => 'read_10', 'question' => 'What health problem does he mention?', 'options' => ['A' => 'Pain in the stomach', 'B' => 'Pain in the head', 'C' => 'Pain in the back'], 'correct' => 'B'],
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'أَنا مِن مِصْر means:', 'options' => ['A' => 'I am from Egypt.', 'B' => 'I live in Egypt.', 'C' => 'I want Egypt.'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'كَمْ عُمْرُكَ؟ means:', 'options' => ['A' => 'What is your name?', 'B' => 'How old are you?', 'C' => 'Where do you live?'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'لَيْسَ عِنْدي أُخْت means:', 'options' => ['A' => 'I have a sister.', 'B' => 'I do not have a sister.', 'C' => 'My sister is young.'], 'correct' => 'B'],
        ['id' => 'mcq_4', 'question' => 'أُريد دَجاجًا وَأَرُزًّا means:', 'options' => ['A' => 'I want chicken and rice.', 'B' => 'I want water and coffee.', 'C' => 'I want bread and tea.'], 'correct' => 'A'],
        ['id' => 'mcq_5', 'question' => 'السِّعْر عَشَرَة دَراهِم means:', 'options' => ['A' => 'The price is ten dirhams.', 'B' => 'I need ten dirhams.', 'C' => 'I have ten dirhams.'], 'correct' => 'A'],
        ['id' => 'mcq_6', 'question' => 'هذا كِتاب أَزْرَق means:', 'options' => ['A' => 'This is a red pen.', 'B' => 'This is a blue book.', 'C' => 'This is a black phone.'], 'correct' => 'B'],
        ['id' => 'mcq_7', 'question' => 'أَنا في البَيْت means:', 'options' => ['A' => 'I am at home.', 'B' => 'I live in a house.', 'C' => 'I want a house.'], 'correct' => 'A'],
        ['id' => 'mcq_8', 'question' => 'لُفّ يَسار means:', 'options' => ['A' => 'Turn right.', 'B' => 'Turn left.', 'C' => 'Go straight.'], 'correct' => 'B'],
        ['id' => 'mcq_9', 'question' => 'أَنا أَعْمَلُ كَمُحاسِب means:', 'options' => ['A' => 'I work as an accountant.', 'B' => 'I work in a company.', 'C' => 'I need an accountant.'], 'correct' => 'A'],
        ['id' => 'mcq_10', 'question' => 'أَحتاجُ طَبيبًا means:', 'options' => ['A' => 'I have a doctor.', 'B' => 'I need a doctor.', 'C' => 'I am a doctor.'], 'correct' => 'B'],
    ],
    'vocabulary_matching' => [
        ['id' => 'match_ism', 'arabic' => 'اِسْم', 'correct' => 'name'],
        ['id' => 'match_umr', 'arabic' => 'عُمْر', 'correct' => 'age'],
        ['id' => 'match_usrah', 'arabic' => 'أُسْرَة', 'correct' => 'family'],
        ['id' => 'match_ureed', 'arabic' => 'أُريد', 'correct' => 'I want'],
        ['id' => 'match_sir', 'arabic' => 'سِعْر', 'correct' => 'price'],
        ['id' => 'match_ahmar', 'arabic' => 'أَحْمَر', 'correct' => 'red'],
        ['id' => 'match_bayt', 'arabic' => 'بَيْت', 'correct' => 'home'],
        ['id' => 'match_ayna', 'arabic' => 'أَيْنَ؟', 'correct' => 'where?'],
        ['id' => 'match_saah', 'arabic' => 'السّاعَة', 'correct' => 'time / o’clock'],
        ['id' => 'match_amal', 'arabic' => 'عَمَل', 'correct' => 'work'],
        ['id' => 'match_ahtaaju', 'arabic' => 'أَحتاجُ', 'correct' => 'I need'],
        ['id' => 'match_alam', 'arabic' => 'أَلَم', 'correct' => 'pain'],
    ],
    'vocabulary_matching_options' => ['name', 'age', 'family', 'I want', 'price', 'red', 'home', 'where?', 'time / o’clock', 'work', 'I need', 'pain'],
    'topic_category' => [
        ['id' => 'topic_1', 'question' => 'أَنا اسْمي أَحْمَد.', 'options' => $topicOptions, 'correct' => 'Introduction'],
        ['id' => 'topic_2', 'question' => 'عُمْري عِشْرون سَنَة.', 'options' => $topicOptions, 'correct' => 'Numbers'],
        ['id' => 'topic_3', 'question' => 'عِنْدي أَخ.', 'options' => $topicOptions, 'correct' => 'Family'],
        ['id' => 'topic_4', 'question' => 'أُريد ماءً.', 'options' => $topicOptions, 'correct' => 'Food'],
        ['id' => 'topic_5', 'question' => 'هذا بِكَم؟', 'options' => $topicOptions, 'correct' => 'Shopping'],
        ['id' => 'topic_6', 'question' => 'هذا قَلَم أَحْمَر.', 'options' => $topicOptions, 'correct' => 'Colors/Objects'],
        ['id' => 'topic_7', 'question' => 'أَيْنَ المَطْعَم؟', 'options' => $topicOptions, 'correct' => 'Places/Directions'],
        ['id' => 'topic_8', 'question' => 'أَصْحو في السّاعَة سَبْعَة.', 'options' => $topicOptions, 'correct' => 'Routine'],
        ['id' => 'topic_9', 'question' => 'أَعْمَلُ في شَرِكَة.', 'options' => $topicOptions, 'correct' => 'Work'],
        ['id' => 'topic_10', 'question' => 'عِنْدي صُداع.', 'options' => $topicOptions, 'correct' => 'Health'],
    ],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'أَنا اسْمي ________.'],
        ['id' => 'cs_2', 'prompt' => 'أَنا مِن ________.'],
        ['id' => 'cs_3', 'prompt' => 'أَنا أَعيشُ في ________.'],
        ['id' => 'cs_4', 'prompt' => 'عُمْري ________ سَنَة.'],
        ['id' => 'cs_5', 'prompt' => 'عِنْدي ________.'],
        ['id' => 'cs_6', 'prompt' => 'أُريد ________.'],
        ['id' => 'cs_7', 'prompt' => 'هذا ________؟'],
        ['id' => 'cs_8', 'prompt' => 'أَيْنَ ________؟'],
        ['id' => 'cs_9', 'prompt' => 'أَصْحو في السّاعَة ________.'],
        ['id' => 'cs_10', 'prompt' => 'أَحتاجُ ________.'],
    ],
    'writing_tasks' => [
        [
            'key' => 'writing_self_introduction',
            'title' => 'Writing Task 1 - Full Self-Introduction',
            'instructions' => 'Write 8-10 Arabic sentences introducing yourself. Include greeting, name, country, city, age, family, work/study, routine, one thing you want or need, and thank you.',
            'placeholder' => 'اكتب هنا تعريفًا كاملًا عن نفسك باللغة العربية...',
            'min_sentences' => 8,
        ],
        [
            'key' => 'writing_daily_life_scenario',
            'title' => 'Writing Task 2 - Daily-Life Scenario',
            'instructions' => 'Write 10-12 Arabic lines or sentences. Include greeting, asking for a place, directions, price, buying/ordering, color/object, work/routine, health/help, and polite ending.',
            'placeholder' => 'اكتب هنا موقفًا يوميًا كاملًا باللغة العربية...',
            'min_sentences' => 10,
        ],
    ],
    'speaking_tasks' => [
        [
            'key' => 'speaking_task_1',
            'title' => 'Speaking 1 - Introduce Yourself and Your Day',
            'instructions' => 'Record yourself for 60-90 seconds. Include greeting, name, country, where you live, age, family, work/study, daily routine, one thing you want or need, and thank you. Direct browser recording only.',
            'max_duration_label' => '120 seconds',
        ],
        [
            'key' => 'speaking_task_2',
            'title' => 'Speaking 2 - Practical Daily-Life Role-Play',
            'instructions' => 'Record yourself for 90-150 seconds. Ask for directions, buy or order something, describe an object with color, say a health/help sentence, and end politely. Direct browser recording only.',
            'max_duration_label' => '180 seconds',
        ],
    ],
    'matching' => [],
    'matching_options' => [],
    'number_recognition' => [],
    'price_recognition' => [],
    'color_recognition' => [],
    'time_recognition' => [],
    'daily_action_matching' => [],
    'direction_matching' => [],
    'direction_recognition' => [],
    'job_matching' => [],
    'workplace_matching' => [],
    'work_sentence_practice' => [],
    'body_matching' => [],
    'health_phrase_matching' => [],
    'pain_sentence_practice' => [],
    'conversation_phrase_matching' => [],
    'topic_recognition' => [],
    'category_practice' => [],
    'sequence_practice' => [],
    'description_matching' => [],
    'complete_conversation' => [],
    'arrange_words' => [],
    'listening_numbers' => [],
    'min_sentences' => 0,
    'self_check_min' => 7,
    'self_check' => [
        'introduce_self' => 'I can introduce myself in Arabic.',
        'personal_info' => 'I can say my age and simple personal information.',
        'family' => 'I can talk about my family.',
        'food_drink' => 'I can order food or drink.',
        'prices' => 'I can ask about prices.',
        'colors_objects' => 'I can describe simple objects with colors.',
        'home_places' => 'I can talk about home and places.',
        'directions' => 'I can ask for simple directions.',
        'daily_routine' => 'I can talk about my daily routine.',
        'work_study' => 'I can talk about work or study.',
        'health_problem' => 'I can describe a simple health problem.',
        'speak_60_seconds' => 'I can speak for at least 60 seconds in Arabic.',
        'ready_finish_beginner' => 'I am ready to finish the Beginner book.',
    ],
];
