<?php
declare(strict_types=1);

return [
    'unit_type' => 'lesson',
    'lesson_number' => 10,
    'title_en' => 'Work & Jobs',
    'title_ar' => 'العَمَل وَالوَظائِف',
    'slug' => 'lesson-10-work-jobs',
    'goal_en' => 'By the end of this lesson, you can talk about your job and workplace using simple Arabic sentences.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تتحدث عن عملك ومكان عملك بجمل عربية بسيطة.',
    'goal_checks' => [
        'Say common job names in Arabic.',
        'Say "I work as..." in Arabic.',
        'Say "I work in..." in Arabic.',
        'Ask someone about their job.',
        'Say simple work tasks.',
        'Use "I have" and "I need" at work.',
        'Record a short speaking task about work.',
    ],
    'situation_en' => 'You meet someone new in Dubai. They ask you about your job, where you work, and what you do every day.',
    'situation_ar' => 'تقابل شخصًا جديدًا في دبي. يسألك عن وظيفتك، وأين تعمل، وماذا تفعل كل يوم في العمل.',
    'warmup_title' => 'Quick Review from Lesson 8 and Lesson 9',
    'warmup_questions' => [
        'How do you say "I go to work" in Arabic?',
        'How do you say "I work in the morning" in Arabic?',
        'How do you say "Where is the office?" in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'amal', 'arabic' => 'عَمَل', 'pronunciation' => 'amal', 'meaning' => 'work', 'category' => 'Work Word', 'example' => 'أَذْهَبُ إِلى العَمَل.'],
        ['key' => 'wazeefah', 'arabic' => 'وَظيفَة', 'pronunciation' => 'wazeefah', 'meaning' => 'job', 'category' => 'Work Word', 'example' => 'عِنْدي وَظيفَة.'],
        ['key' => 'muallim', 'arabic' => 'مُعَلِّم', 'pronunciation' => 'muallim', 'meaning' => 'teacher - male', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَمُعَلِّم.'],
        ['key' => 'muallimah', 'arabic' => 'مُعَلِّمَة', 'pronunciation' => 'muallimah', 'meaning' => 'teacher - female', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَمُعَلِّمَة.'],
        ['key' => 'taalib', 'arabic' => 'طالِب', 'pronunciation' => 'taalib', 'meaning' => 'student - male', 'category' => 'Job', 'example' => 'أَنا طالِب.'],
        ['key' => 'taalibah', 'arabic' => 'طالِبَة', 'pronunciation' => 'taalibah', 'meaning' => 'student - female', 'category' => 'Job', 'example' => 'أَنا طالِبَة.'],
        ['key' => 'tabeeb', 'arabic' => 'طَبيب', 'pronunciation' => 'tabeeb', 'meaning' => 'doctor - male', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَطَبيب.'],
        ['key' => 'tabeebah', 'arabic' => 'طَبيبَة', 'pronunciation' => 'tabeebah', 'meaning' => 'doctor - female', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَطَبيبَة.'],
        ['key' => 'muhandis', 'arabic' => 'مُهَنْدِس', 'pronunciation' => 'muhandis', 'meaning' => 'engineer - male', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَمُهَنْدِس.'],
        ['key' => 'muhandisah', 'arabic' => 'مُهَنْدِسَة', 'pronunciation' => 'muhandisah', 'meaning' => 'engineer - female', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَمُهَنْدِسَة.'],
        ['key' => 'muhaasib', 'arabic' => 'مُحاسِب', 'pronunciation' => 'muhaasib', 'meaning' => 'accountant - male', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَمُحاسِب.'],
        ['key' => 'muhaasibah', 'arabic' => 'مُحاسِبَة', 'pronunciation' => 'muhaasibah', 'meaning' => 'accountant - female', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَمُحاسِبَة.'],
        ['key' => 'baai', 'arabic' => 'بائِع', 'pronunciation' => "baa'i", 'meaning' => 'salesperson - male', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَبائِع.'],
        ['key' => 'baaiyah', 'arabic' => 'بائِعَة', 'pronunciation' => "baa'iah", 'meaning' => 'salesperson - female', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَبائِعَة.'],
        ['key' => 'mudeer', 'arabic' => 'مُدير', 'pronunciation' => 'mudeer', 'meaning' => 'manager - male', 'category' => 'Job', 'example' => 'أَنا مُدير.'],
        ['key' => 'mudeerah', 'arabic' => 'مُديرَة', 'pronunciation' => 'mudeerah', 'meaning' => 'manager - female', 'category' => 'Job', 'example' => 'أَنا مُديرَة.'],
        ['key' => 'muwazzaf', 'arabic' => 'مُوَظَّف', 'pronunciation' => 'muwazzaf', 'meaning' => 'employee - male', 'category' => 'Job', 'example' => 'أَنا مُوَظَّف.'],
        ['key' => 'muwazzafah', 'arabic' => 'مُوَظَّفَة', 'pronunciation' => 'muwazzafah', 'meaning' => 'employee - female', 'category' => 'Job', 'example' => 'أَنا مُوَظَّفَة.'],
        ['key' => 'saaeq', 'arabic' => 'سائِق', 'pronunciation' => "saa'iq", 'meaning' => 'driver', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَسائِق.'],
        ['key' => 'tabbaakh', 'arabic' => 'طَبّاخ', 'pronunciation' => 'tabbaakh', 'meaning' => 'cook / chef', 'category' => 'Job', 'example' => 'أَنا أَعْمَلُ كَطَبّاخ.'],
        ['key' => 'maktab', 'arabic' => 'مَكْتَب', 'pronunciation' => 'maktab', 'meaning' => 'office', 'category' => 'Workplace', 'example' => 'أَنا أَعْمَلُ في مَكْتَب.'],
        ['key' => 'sharikah', 'arabic' => 'شَرِكَة', 'pronunciation' => 'sharikah', 'meaning' => 'company', 'category' => 'Workplace', 'example' => 'أَنا أَعْمَلُ في شَرِكَة.'],
        ['key' => 'madrasah', 'arabic' => 'مَدْرَسَة', 'pronunciation' => 'madrasah', 'meaning' => 'school', 'category' => 'Workplace', 'example' => 'أَنا أَعْمَلُ في مَدْرَسَة.'],
        ['key' => 'mustashfaa', 'arabic' => 'مُسْتَشْفى', 'pronunciation' => 'mustashfaa', 'meaning' => 'hospital', 'category' => 'Workplace', 'example' => 'أَنا أَعْمَلُ في مُسْتَشْفى.'],
        ['key' => 'mahall', 'arabic' => 'مَحَلّ', 'pronunciation' => 'mahall', 'meaning' => 'shop', 'category' => 'Workplace', 'example' => 'أَنا أَعْمَلُ في مَحَلّ.'],
        ['key' => 'matam', 'arabic' => 'مَطْعَم', 'pronunciation' => "mat'am", 'meaning' => 'restaurant', 'category' => 'Workplace', 'example' => 'أَنا أَعْمَلُ في مَطْعَم.'],
        ['key' => 'fareeq', 'arabic' => 'فَريق', 'pronunciation' => 'fareeq', 'meaning' => 'team', 'category' => 'Workplace Word', 'example' => 'أَعْمَلُ مَعَ فَريق.'],
        ['key' => 'zameel', 'arabic' => 'زَميل', 'pronunciation' => 'zameel', 'meaning' => 'colleague - male', 'category' => 'Workplace Word', 'example' => 'عِنْدي زَميل جَيِّد.'],
        ['key' => 'zameelah', 'arabic' => 'زَميلَة', 'pronunciation' => 'zameelah', 'meaning' => 'colleague - female', 'category' => 'Workplace Word', 'example' => 'عِنْدي زَميلَة جَيِّدَة.'],
        ['key' => 'ameel', 'arabic' => 'عَميل', 'pronunciation' => 'ameel', 'meaning' => 'customer / client - male', 'category' => 'Workplace Word', 'example' => 'أَتَكَلَّمُ مَعَ عَميل.'],
        ['key' => 'ameelah', 'arabic' => 'عَميلَة', 'pronunciation' => 'ameelah', 'meaning' => 'customer / client - female', 'category' => 'Workplace Word', 'example' => 'أَتَكَلَّمُ مَعَ عَميلَة.'],
        ['key' => 'ijtimaa', 'arabic' => 'اِجْتِماع', 'pronunciation' => 'ijtimaa', 'meaning' => 'meeting', 'category' => 'Work Task', 'example' => 'عِنْدي اِجْتِماع اليَوْم.'],
        ['key' => 'bareed_elektroni', 'arabic' => 'بَريد إِلِكْتروني', 'pronunciation' => 'bareed elektronii', 'meaning' => 'email', 'category' => 'Work Task', 'example' => 'أُرْسِلُ بَريدًا إِلِكْترونِيًا.'],
        ['key' => 'taqreer', 'arabic' => 'تَقْرير', 'pronunciation' => 'taqreer', 'meaning' => 'report', 'category' => 'Work Task', 'example' => 'أَكْتُبُ تَقْريرًا.'],
        ['key' => 'muhimmah', 'arabic' => 'مُهِمَّة', 'pronunciation' => 'muhimmah', 'meaning' => 'task', 'category' => 'Work Task', 'example' => 'عِنْدي مُهِمَّة اليَوْم.'],
        ['key' => 'mashroo', 'arabic' => 'مَشْروع', 'pronunciation' => 'mashroo', 'meaning' => 'project', 'category' => 'Work Task', 'example' => 'عِنْدي مَشْروع جَديد.'],
        ['key' => 'ahtaaju', 'arabic' => 'أَحْتاجُ', 'pronunciation' => 'ahtaaju', 'meaning' => 'I need', 'category' => 'Work Phrase', 'example' => 'أَحْتاجُ مُساعَدَة.'],
        ['key' => 'musaadah', 'arabic' => 'مُساعَدَة', 'pronunciation' => 'musaadah', 'meaning' => 'help', 'category' => 'Work Phrase', 'example' => 'أَحْتاجُ مُساعَدَة.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Work & Jobs Vocabulary', 'key' => 'B1-L10-Work-Jobs-Vocab', 'file' => '/assets/audio/books/beginner/lesson-10/B1-L10-Work-Jobs-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L10-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-10/B1-L10-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'أَنا أَعْمَلُ كَمُعَلِّم.', 'en' => 'I work as a teacher.'],
        ['ar' => 'أَنا أَعْمَلُ كَطَبيب.', 'en' => 'I work as a doctor.'],
        ['ar' => 'أَنا أَعْمَلُ كَمُهَنْدِس.', 'en' => 'I work as an engineer.'],
        ['ar' => 'أَنا أَعْمَلُ كَمُحاسِب.', 'en' => 'I work as an accountant.'],
        ['ar' => 'أَنا أَعْمَلُ في شَرِكَة.', 'en' => 'I work in a company.'],
        ['ar' => 'أَنا أَعْمَلُ في مَدْرَسَة.', 'en' => 'I work in a school.'],
        ['ar' => 'أَنا أَعْمَلُ في مَكْتَب.', 'en' => 'I work in an office.'],
        ['ar' => 'ما عَمَلُكَ؟', 'en' => 'What is your job?'],
        ['ar' => 'أَيْنَ تَعْمَل؟', 'en' => 'Where do you work?'],
        ['ar' => 'أَكْتُبُ تَقْريرًا.', 'en' => 'I write a report.'],
        ['ar' => 'أُرْسِلُ بَريدًا إِلِكْترونِيًا.', 'en' => 'I send an email.'],
        ['ar' => 'أَتَكَلَّمُ مَعَ عَميل.', 'en' => 'I speak with a customer.'],
        ['ar' => 'عِنْدي اِجْتِماع اليَوْم.', 'en' => 'I have a meeting today.'],
        ['ar' => 'عِنْدي مَشْروع جَديد.', 'en' => 'I have a new project.'],
        ['ar' => 'أَحْتاجُ مُساعَدَة.', 'en' => 'I need help.'],
    ],
    'grammar_tip' => [
        'title' => 'How to talk about work',
        'body' => 'Use أَعْمَلُ كَـ to say "I work as...". Use أَعْمَلُ في to say "I work in...". Use عِنْدي for "I have" and أَحْتاجُ for "I need".',
        'examples' => [
            ['ar' => 'أَنا أَعْمَلُ كَمُحاسِب.', 'en' => 'I work as an accountant.'],
            ['ar' => 'أَنا أَعْمَلُ في شَرِكَة.', 'en' => 'I work in a company.'],
            ['ar' => 'عِنْدي اِجْتِماع اليَوْم.', 'en' => 'I have a meeting today.'],
            ['ar' => 'أَحْتاجُ مُساعَدَة.', 'en' => 'I need help.'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: ما اسْمُكَ؟',
        'B: أَنا اسْمي أَحْمَد.',
        'A: ما عَمَلُكَ؟',
        'B: أَنا أَعْمَلُ كَمُحاسِب.',
        'A: أَيْنَ تَعْمَل؟',
        'B: أَنا أَعْمَلُ في شَرِكَة في دُبَي.',
        'A: ماذا تَفْعَل في العَمَل؟',
        'B: أَكْتُبُ تَقْريرًا وَأُرْسِلُ بَريدًا إِلِكْترونِيًا.',
        'A: هَلْ عِنْدَكَ اِجْتِماع اليَوْم؟',
        'B: نَعَم، عِنْدي اِجْتِماع اليَوْم.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: What is your name?',
        'B: My name is Ahmed.',
        'A: What is your job?',
        'B: I work as an accountant.',
        'A: Where do you work?',
        'B: I work in a company in Dubai.',
        'A: What do you do at work?',
        'B: I write a report and send an email.',
        'A: Do you have a meeting today?',
        'B: Yes, I have a meeting today.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does وَظيفَة mean?', 'options' => ['A' => 'job', 'B' => 'food', 'C' => 'direction'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'What does مُعَلِّم mean?', 'options' => ['A' => 'doctor', 'B' => 'teacher', 'C' => 'driver'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'أَنا أَعْمَلُ في شَرِكَة means:', 'options' => ['A' => 'I work in a company.', 'B' => 'I live in a company.', 'C' => 'I want a company.'], 'correct' => 'A'],
        ['id' => 'mcq_4', 'question' => 'عِنْدي اِجْتِماع means:', 'options' => ['A' => 'I need help.', 'B' => 'I have a meeting.', 'C' => 'I work in a school.'], 'correct' => 'B'],
        ['id' => 'mcq_5', 'question' => 'أَحْتاجُ مُساعَدَة means:', 'options' => ['A' => 'I need help.', 'B' => 'I have a project.', 'C' => 'I send an email.'], 'correct' => 'A'],
    ],
    'job_matching' => [
        ['id' => 'match_muallim', 'arabic' => 'مُعَلِّم', 'correct' => 'teacher'],
        ['id' => 'match_tabeeb', 'arabic' => 'طَبيب', 'correct' => 'doctor'],
        ['id' => 'match_muhandis', 'arabic' => 'مُهَنْدِس', 'correct' => 'engineer'],
        ['id' => 'match_muhasib', 'arabic' => 'مُحاسِب', 'correct' => 'accountant'],
        ['id' => 'match_baai', 'arabic' => 'بائِع', 'correct' => 'salesperson'],
        ['id' => 'match_mudeer', 'arabic' => 'مُدير', 'correct' => 'manager'],
        ['id' => 'match_muwazzaf', 'arabic' => 'مُوَظَّف', 'correct' => 'employee'],
        ['id' => 'match_saaeq', 'arabic' => 'سائِق', 'correct' => 'driver'],
        ['id' => 'match_taalib', 'arabic' => 'طالِب', 'correct' => 'student'],
        ['id' => 'match_tabbaakh', 'arabic' => 'طَبّاخ', 'correct' => 'cook / chef'],
    ],
    'job_matching_options' => ['teacher', 'doctor', 'engineer', 'accountant', 'salesperson', 'manager', 'employee', 'driver', 'student', 'cook / chef'],
    'workplace_matching' => [
        ['id' => 'match_maktab', 'arabic' => 'مَكْتَب', 'correct' => 'office'],
        ['id' => 'match_sharikah', 'arabic' => 'شَرِكَة', 'correct' => 'company'],
        ['id' => 'match_mahall', 'arabic' => 'مَحَلّ', 'correct' => 'shop'],
        ['id' => 'match_matam', 'arabic' => 'مَطْعَم', 'correct' => 'restaurant'],
        ['id' => 'match_fareeq', 'arabic' => 'فَريق', 'correct' => 'team'],
        ['id' => 'match_zameel', 'arabic' => 'زَميل', 'correct' => 'colleague'],
        ['id' => 'match_ameel', 'arabic' => 'عَميل', 'correct' => 'customer / client'],
        ['id' => 'match_ijtimaa', 'arabic' => 'اِجْتِماع', 'correct' => 'meeting'],
        ['id' => 'match_taqreer', 'arabic' => 'تَقْرير', 'correct' => 'report'],
        ['id' => 'match_mashroo', 'arabic' => 'مَشْروع', 'correct' => 'project'],
    ],
    'workplace_matching_options' => ['office', 'company', 'shop', 'restaurant', 'team', 'colleague', 'customer / client', 'meeting', 'report', 'project'],
    'work_sentence_practice' => [
        ['id' => 'ws_1', 'question' => 'أَنا أَعْمَلُ كَمُعَلِّم.', 'options' => ['A' => 'I work as a teacher.', 'B' => 'I work in a school.', 'C' => 'I need a teacher.'], 'correct' => 'A'],
        ['id' => 'ws_2', 'question' => 'أَنا أَعْمَلُ في مَحَلّ.', 'options' => ['A' => 'I work in a shop.', 'B' => 'I buy from a shop.', 'C' => 'I live near a shop.'], 'correct' => 'A'],
        ['id' => 'ws_3', 'question' => 'أَكْتُبُ تَقْريرًا.', 'options' => ['A' => 'I write a report.', 'B' => 'I send an email.', 'C' => 'I have a meeting.'], 'correct' => 'A'],
        ['id' => 'ws_4', 'question' => 'أُرْسِلُ بَريدًا إِلِكْترونِيًا.', 'options' => ['A' => 'I need help.', 'B' => 'I send an email.', 'C' => 'I work with a team.'], 'correct' => 'B'],
        ['id' => 'ws_5', 'question' => 'أَعْمَلُ مَعَ فَريق.', 'options' => ['A' => 'I work with a team.', 'B' => 'I have a meeting.', 'C' => 'I am a manager.'], 'correct' => 'A'],
        ['id' => 'ws_6', 'question' => 'عِنْدي مَشْروع جَديد.', 'options' => ['A' => 'I have a new project.', 'B' => 'I need a new job.', 'C' => 'I go to work.'], 'correct' => 'A'],
    ],
    'matching' => [],
    'matching_options' => [],
    'number_recognition' => [],
    'price_recognition' => [],
    'color_recognition' => [],
    'time_recognition' => [],
    'daily_action_matching' => [],
    'direction_matching' => [],
    'direction_recognition' => [],
    'sequence_practice' => [],
    'description_matching' => [],
    'category_practice' => [],
    'listening_review' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'أَنا أَعْمَلُ كَـ ________.'],
        ['id' => 'cs_2', 'prompt' => 'أَنا أَعْمَلُ في ________.'],
        ['id' => 'cs_3', 'prompt' => 'عِنْدي ________ اليَوْم.'],
        ['id' => 'cs_4', 'prompt' => 'أَحْتاجُ ________.'],
        ['id' => 'cs_5', 'prompt' => 'أُرْسِلُ ________.'],
        ['id' => 'cs_6', 'prompt' => 'أَكْتُبُ ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write a Short Work Profile',
    'writing_instructions' => 'Write 6 Arabic sentences about your job or a practice/fake job. Use: أَنا اسْمي، أَنا أَعْمَلُ كَـ، أَنا أَعْمَلُ في، أَذْهَبُ إِلى العَمَل، عِنْدي، أَحْتاجُ.',
    'writing_placeholder' => 'اكتب هنا 6 جمل عن عملك أو وظيفة للتدريب...',
    'min_sentences' => 6,
    'speaking_title' => 'Speaking Task - Talk About Your Job',
    'speaking_instructions' => 'Record yourself for about 60 seconds. Say your name, your job or practice job, where you work, when you go to work, one or two things you do at work, one thing you have today, one thing you need, and ask the other person about their job. Direct browser recording only.',
    'self_check_min' => 4,
    'self_check' => [
        'job_names' => 'I can say common job names in Arabic.',
        'say_where_work' => 'I can say where I work in Arabic.',
        'work_as' => 'I can say "I work as..." in Arabic.',
        'work_tasks' => 'I can say simple work tasks in Arabic.',
        'meeting_task_project' => 'I can say "I have a meeting/task/project."',
        'need_help' => 'I can say "I need help."',
        'record_work_speaking' => 'I can record a short speaking task about work.',
    ],
];
