<?php
declare(strict_types=1);

return [
    'lesson_number' => 4,
    'title_en' => 'Food & Drinks',
    'title_ar' => 'الطَّعام وَالشَّراب',
    'slug' => 'lesson-4-food-drinks',
    'goal_en' => 'By the end of this lesson, you can order simple food and drinks in Arabic.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تطلب طعامًا وشرابًا بسيطًا باللغة العربية.',
    'goal_checks' => [
        'Say basic food words.',
        'Say basic drink words.',
        'Say "I want..." in Arabic.',
        'Say "I do not want..." in Arabic.',
        'Ask "Do you have...?" in Arabic.',
        'Order food or drink politely.',
        'Record a short restaurant/cafe order.',
    ],
    'situation_en' => 'You are in a cafe or restaurant in Dubai. You want to order food and a drink in simple Arabic.',
    'situation_ar' => 'أنت في كافيه أو مطعم في دبي. تريد أن تطلب طعامًا وشرابًا باللغة العربية بطريقة بسيطة.',
    'warmup_title' => 'Quick Review from Lessons 1-3',
    'warmup_questions' => [
        'How do you say "My name is Ahmed" in Arabic?',
        'How do you say "I am twenty years old" in Arabic?',
        'How do you say "I have a brother" in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'taaam', 'arabic' => 'طَعام', 'pronunciation' => "ta'aam", 'meaning' => 'food', 'category' => 'Food', 'example' => 'أُريد طَعامًا.'],
        ['key' => 'sharaab', 'arabic' => 'شَراب', 'pronunciation' => 'sharaab', 'meaning' => 'drink', 'category' => 'Drink', 'example' => 'أُريد شَرابًا.'],
        ['key' => 'maa', 'arabic' => 'ماء', 'pronunciation' => "maa'", 'meaning' => 'water', 'category' => 'Drink', 'example' => 'أُريد ماءً.'],
        ['key' => 'shaay', 'arabic' => 'شاي', 'pronunciation' => 'shaay', 'meaning' => 'tea', 'category' => 'Drink', 'example' => 'أُريد شايًا.'],
        ['key' => 'qahwah', 'arabic' => 'قَهْوَة', 'pronunciation' => 'qahwah', 'meaning' => 'coffee', 'category' => 'Drink', 'example' => 'أُريد قَهْوَة.'],
        ['key' => 'aseer', 'arabic' => 'عَصير', 'pronunciation' => 'aseer', 'meaning' => 'juice', 'category' => 'Drink', 'example' => 'أُريد عَصيرًا.'],
        ['key' => 'khubz', 'arabic' => 'خُبْز', 'pronunciation' => 'khubz', 'meaning' => 'bread', 'category' => 'Food', 'example' => 'أُريد خُبْزًا.'],
        ['key' => 'aruzz', 'arabic' => 'أَرُزّ', 'pronunciation' => 'aruzz', 'meaning' => 'rice', 'category' => 'Food', 'example' => 'أُريد أَرُزًّا.'],
        ['key' => 'dajaaj', 'arabic' => 'دَجاج', 'pronunciation' => 'dajaaj', 'meaning' => 'chicken', 'category' => 'Food', 'example' => 'أُريد دَجاجًا.'],
        ['key' => 'samak', 'arabic' => 'سَمَك', 'pronunciation' => 'samak', 'meaning' => 'fish', 'category' => 'Food', 'example' => 'أُريد سَمَكًا.'],
        ['key' => 'khudaar', 'arabic' => 'خُضار', 'pronunciation' => 'khudaar', 'meaning' => 'vegetables', 'category' => 'Food', 'example' => 'أُريد خُضارًا.'],
        ['key' => 'faakihah', 'arabic' => 'فاكِهَة', 'pronunciation' => 'faakihah', 'meaning' => 'fruit', 'category' => 'Food', 'example' => 'أُريد فاكِهَة.'],
        ['key' => 'qaaimat_at_taaam', 'arabic' => 'قَائِمَة الطَّعام', 'pronunciation' => "qaa'imat at-ta'aam", 'meaning' => 'menu', 'category' => 'Restaurant Word', 'example' => 'أُريد قَائِمَة الطَّعام.'],
        ['key' => 'hisaab', 'arabic' => 'حِساب', 'pronunciation' => 'hisaab', 'meaning' => 'bill', 'category' => 'Restaurant Word', 'example' => 'أُريد الحِساب.'],
        ['key' => 'min_fadlik', 'arabic' => 'مِن فَضْلِكَ', 'pronunciation' => 'min fadlik', 'meaning' => 'please - to a male', 'category' => 'Polite Phrase', 'example' => 'أُريد ماءً، مِن فَضْلِكَ.'],
        ['key' => 'min_fadliki', 'arabic' => 'مِن فَضْلِكِ', 'pronunciation' => 'min fadliki', 'meaning' => 'please - to a female', 'category' => 'Polite Phrase', 'example' => 'أُريد قَهْوَة، مِن فَضْلِكِ.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Food & Drinks Vocabulary', 'key' => 'B1-L04-Food-Drinks-Vocab', 'file' => '/assets/audio/books/beginner/lesson-4/B1-L04-Food-Drinks-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L04-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-4/B1-L04-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'أُريد ماءً.', 'en' => 'I want water.'],
        ['ar' => 'أُريد شايًا.', 'en' => 'I want tea.'],
        ['ar' => 'أُريد قَهْوَة.', 'en' => 'I want coffee.'],
        ['ar' => 'أُريد عَصيرًا.', 'en' => 'I want juice.'],
        ['ar' => 'أُريد دَجاجًا.', 'en' => 'I want chicken.'],
        ['ar' => 'أُريد أَرُزًّا.', 'en' => 'I want rice.'],
        ['ar' => 'لا أُريد سَمَكًا.', 'en' => 'I do not want fish.'],
        ['ar' => 'هَلْ عِنْدَكُم ماء؟', 'en' => 'Do you have water?'],
        ['ar' => 'هَلْ عِنْدَكُم قَهْوَة؟', 'en' => 'Do you have coffee?'],
        ['ar' => 'أُريد قَائِمَة الطَّعام، مِن فَضْلِكَ.', 'en' => 'I want the menu, please.'],
        ['ar' => 'أُريد الحِساب، مِن فَضْلِكَ.', 'en' => 'I want the bill, please.'],
        ['ar' => 'شُكْرًا.', 'en' => 'Thank you.'],
    ],
    'grammar_tip' => [
        'title' => 'How to say "I want" and "I do not want"',
        'body' => 'Use أُريد to say "I want". Use لا أُريد to say "I do not want". The goal is practical speaking and making a clear order.',
        'examples' => [
            ['ar' => 'أُريد ماءً.', 'en' => 'I want water.'],
            ['ar' => 'أُريد شايًا.', 'en' => 'I want tea.'],
            ['ar' => 'لا أُريد سَمَكًا.', 'en' => 'I do not want fish.'],
            ['ar' => 'لا أُريد قَهْوَة.', 'en' => 'I do not want coffee.'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: هَلْ عِنْدَكُم قَهْوَة؟',
        'B: نَعَم، عِنْدَنا قَهْوَة.',
        'A: أُريد قَهْوَة وَماءً، مِن فَضْلِكَ.',
        'B: طَيِّب. هَلْ تُريد طَعامًا؟',
        'A: نَعَم، أُريد دَجاجًا وَأَرُزًّا.',
        'B: حاضِر.',
        'A: شُكْرًا.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: Do you have coffee?',
        'B: Yes, we have coffee.',
        'A: I want coffee and water, please.',
        'B: Okay. Do you want food?',
        'A: Yes, I want chicken and rice.',
        'B: Sure.',
        'A: Thank you.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does ماء mean?', 'options' => ['A' => 'coffee', 'B' => 'water', 'C' => 'rice'], 'correct' => 'B'],
        ['id' => 'mcq_2', 'question' => 'What does قَهْوَة mean?', 'options' => ['A' => 'coffee', 'B' => 'tea', 'C' => 'juice'], 'correct' => 'A'],
        ['id' => 'mcq_3', 'question' => 'أُريد ماءً means:', 'options' => ['A' => 'I have water.', 'B' => 'I want water.', 'C' => 'I do not want water.'], 'correct' => 'B'],
        ['id' => 'mcq_4', 'question' => 'لا أُريد سَمَكًا means:', 'options' => ['A' => 'I want fish.', 'B' => 'I do not want fish.', 'C' => 'I have fish.'], 'correct' => 'B'],
        ['id' => 'mcq_5', 'question' => 'أُريد الحِساب means:', 'options' => ['A' => 'I want the bill.', 'B' => 'I want the menu.', 'C' => 'I want water.'], 'correct' => 'A'],
    ],
    'category_practice' => [
        ['id' => 'cat_1', 'question' => 'ماء', 'options' => ['Food' => 'Food', 'Drink' => 'Drink', 'Restaurant Word' => 'Restaurant Word'], 'correct' => 'Drink'],
        ['id' => 'cat_2', 'question' => 'دَجاج', 'options' => ['Food' => 'Food', 'Drink' => 'Drink', 'Restaurant Word' => 'Restaurant Word'], 'correct' => 'Food'],
        ['id' => 'cat_3', 'question' => 'قَائِمَة الطَّعام', 'options' => ['Food' => 'Food', 'Drink' => 'Drink', 'Restaurant Word' => 'Restaurant Word'], 'correct' => 'Restaurant Word'],
        ['id' => 'cat_4', 'question' => 'عَصير', 'options' => ['Food' => 'Food', 'Drink' => 'Drink', 'Restaurant Word' => 'Restaurant Word'], 'correct' => 'Drink'],
        ['id' => 'cat_5', 'question' => 'أَرُزّ', 'options' => ['Food' => 'Food', 'Drink' => 'Drink', 'Restaurant Word' => 'Restaurant Word'], 'correct' => 'Food'],
    ],
    'matching' => [
        ['id' => 'match_maa', 'arabic' => 'ماء', 'correct' => 'water'],
        ['id' => 'match_shaay', 'arabic' => 'شاي', 'correct' => 'tea'],
        ['id' => 'match_qahwah', 'arabic' => 'قَهْوَة', 'correct' => 'coffee'],
        ['id' => 'match_khubz', 'arabic' => 'خُبْز', 'correct' => 'bread'],
        ['id' => 'match_dajaaj', 'arabic' => 'دَجاج', 'correct' => 'chicken'],
        ['id' => 'match_aruzz', 'arabic' => 'أَرُزّ', 'correct' => 'rice'],
    ],
    'matching_options' => ['water', 'tea', 'coffee', 'bread', 'chicken', 'rice'],
    'number_recognition' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'أُريد ________.'],
        ['id' => 'cs_2', 'prompt' => 'لا أُريد ________.'],
        ['id' => 'cs_3', 'prompt' => 'هَلْ عِنْدَكُم ________؟'],
        ['id' => 'cs_4', 'prompt' => 'أُريد ________ وَ ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write a Simple Food Order',
    'writing_instructions' => 'Write 4-5 Arabic sentences for a cafe or restaurant order.',
    'writing_placeholder' => 'اكتب هنا طلبًا بسيطًا في مطعم أو كافيه...',
    'min_sentences' => 4,
    'speaking_title' => 'Speaking Task - Order Food and Drinks',
    'speaking_instructions' => 'Record yourself for 30-45 seconds. Include greeting, ask if they have one item, say what drink you want, say what food you want, say one thing you do not want, and say thank you.',
    'self_check' => [
        'food_words' => 'I can say basic food words in Arabic.',
        'drink_words' => 'I can say basic drink words in Arabic.',
        'say_i_want' => 'I can say "I want..." in Arabic.',
        'say_i_dont_want' => 'I can say "I do not want..." in Arabic.',
        'ask_do_you_have' => 'I can ask "Do you have...?" in Arabic.',
        'order_politely' => 'I can order food or drink politely in Arabic.',
        'record_order' => 'I can record a short restaurant/cafe order.',
    ],
];
