<?php
declare(strict_types=1);

return [
    'unit_type' => 'lesson',
    'lesson_number' => 6,
    'title_en' => 'Colors & Objects',
    'title_ar' => 'الأَلْوان وَالأَشْياء',
    'slug' => 'lesson-6-colors-objects',
    'goal_en' => 'By the end of this lesson, you can describe simple objects using colors in Arabic.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تصف أشياء بسيطة باستخدام الألوان باللغة العربية.',
    'goal_checks' => [
        'Say basic colors in Arabic.',
        'Say common objects in Arabic.',
        'Use هذا with masculine objects.',
        'Use هذه with feminine objects.',
        'Describe an object with a color.',
        'Write simple object descriptions.',
        'Record a short speaking task describing objects.',
    ],
    'situation_en' => 'You are in a shop or classroom. You want to describe objects around you in Arabic using colors.',
    'situation_ar' => 'أنت في محل أو فصل. تريد أن تصف الأشياء حولك باللغة العربية باستخدام الألوان.',
    'warmup_title' => 'Quick Review from Lesson 5',
    'warmup_questions' => [
        'How do you say "How much is this?" in Arabic?',
        'How do you say "I want this" in Arabic?',
        'How do you say "This is expensive" in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'abyad', 'arabic' => 'أَبْيَض', 'pronunciation' => 'abyad', 'meaning' => 'white - masculine', 'category' => 'Color', 'example' => 'هذا قَلَم أَبْيَض.'],
        ['key' => 'baydaa', 'arabic' => 'بَيْضاء', 'pronunciation' => "baydaa'", 'meaning' => 'white - feminine', 'category' => 'Color', 'example' => 'هذه حَقيبَة بَيْضاء.'],
        ['key' => 'aswad', 'arabic' => 'أَسْوَد', 'pronunciation' => 'aswad', 'meaning' => 'black - masculine', 'category' => 'Color', 'example' => 'هذا كِتاب أَسْوَد.'],
        ['key' => 'sawdaa', 'arabic' => 'سَوْداء', 'pronunciation' => "sawdaa'", 'meaning' => 'black - feminine', 'category' => 'Color', 'example' => 'هذه حَقيبَة سَوْداء.'],
        ['key' => 'ahmar', 'arabic' => 'أَحْمَر', 'pronunciation' => 'ahmar', 'meaning' => 'red - masculine', 'category' => 'Color', 'example' => 'هذا قَلَم أَحْمَر.'],
        ['key' => 'hamraa', 'arabic' => 'حَمْراء', 'pronunciation' => "hamraa'", 'meaning' => 'red - feminine', 'category' => 'Color', 'example' => 'هذه ساعَة حَمْراء.'],
        ['key' => 'azraq', 'arabic' => 'أَزْرَق', 'pronunciation' => 'azraq', 'meaning' => 'blue - masculine', 'category' => 'Color', 'example' => 'هذا كِتاب أَزْرَق.'],
        ['key' => 'zarqaa', 'arabic' => 'زَرْقاء', 'pronunciation' => "zarqaa'", 'meaning' => 'blue - feminine', 'category' => 'Color', 'example' => 'هذه حَقيبَة زَرْقاء.'],
        ['key' => 'akhdar', 'arabic' => 'أَخْضَر', 'pronunciation' => 'akhdar', 'meaning' => 'green - masculine', 'category' => 'Color', 'example' => 'هذا قَلَم أَخْضَر.'],
        ['key' => 'khadraa', 'arabic' => 'خَضْراء', 'pronunciation' => "khadraa'", 'meaning' => 'green - feminine', 'category' => 'Color', 'example' => 'هذه حَقيبَة خَضْراء.'],
        ['key' => 'asfar', 'arabic' => 'أَصْفَر', 'pronunciation' => 'asfar', 'meaning' => 'yellow - masculine', 'category' => 'Color', 'example' => 'هذا كِتاب أَصْفَر.'],
        ['key' => 'safraa', 'arabic' => 'صَفْراء', 'pronunciation' => "safraa'", 'meaning' => 'yellow - feminine', 'category' => 'Color', 'example' => 'هذه وَرَقَة صَفْراء.'],
        ['key' => 'bunni', 'arabic' => 'بُنِّي', 'pronunciation' => 'bunni', 'meaning' => 'brown - masculine', 'category' => 'Color', 'example' => 'هذا كُرْسي بُنِّي.'],
        ['key' => 'bunniyyah', 'arabic' => 'بُنِّيَّة', 'pronunciation' => 'bunniyyah', 'meaning' => 'brown - feminine', 'category' => 'Color', 'example' => 'هذه حَقيبَة بُنِّيَّة.'],
        ['key' => 'ramaadi', 'arabic' => 'رَمادي', 'pronunciation' => 'ramaadi', 'meaning' => 'grey - masculine', 'category' => 'Color', 'example' => 'هذا هاتِف رَمادي.'],
        ['key' => 'ramaadiyyah', 'arabic' => 'رَمادِيَّة', 'pronunciation' => 'ramaadiyyah', 'meaning' => 'grey - feminine', 'category' => 'Color', 'example' => 'هذه ساعَة رَمادِيَّة.'],
        ['key' => 'qalam', 'arabic' => 'قَلَم', 'pronunciation' => 'qalam', 'meaning' => 'pen', 'category' => 'Object - masculine', 'example' => 'هذا قَلَم أَحْمَر.'],
        ['key' => 'kitaab', 'arabic' => 'كِتاب', 'pronunciation' => 'kitaab', 'meaning' => 'book', 'category' => 'Object - masculine', 'example' => 'هذا كِتاب أَزْرَق.'],
        ['key' => 'haatif', 'arabic' => 'هاتِف', 'pronunciation' => 'haatif', 'meaning' => 'phone', 'category' => 'Object - masculine', 'example' => 'هذا هاتِف أَسْوَد.'],
        ['key' => 'kursi', 'arabic' => 'كُرْسي', 'pronunciation' => 'kursi', 'meaning' => 'chair', 'category' => 'Object - masculine', 'example' => 'هذا كُرْسي بُنِّي.'],
        ['key' => 'baab', 'arabic' => 'باب', 'pronunciation' => 'baab', 'meaning' => 'door', 'category' => 'Object - masculine', 'example' => 'هذا باب أَبْيَض.'],
        ['key' => 'haqeebah', 'arabic' => 'حَقيبَة', 'pronunciation' => 'haqeebah', 'meaning' => 'bag', 'category' => 'Object - feminine', 'example' => 'هذه حَقيبَة زَرْقاء.'],
        ['key' => 'saaah', 'arabic' => 'ساعَة', 'pronunciation' => "saa'ah", 'meaning' => 'watch / clock', 'category' => 'Object - feminine', 'example' => 'هذه ساعَة سَوْداء.'],
        ['key' => 'waraqah', 'arabic' => 'وَرَقَة', 'pronunciation' => 'waraqah', 'meaning' => 'paper', 'category' => 'Object - feminine', 'example' => 'هذه وَرَقَة بَيْضاء.'],
        ['key' => 'naafidhah', 'arabic' => 'نافِذَة', 'pronunciation' => 'naafidhah', 'meaning' => 'window', 'category' => 'Object - feminine', 'example' => 'هذه نافِذَة بَيْضاء.'],
        ['key' => 'taawilah', 'arabic' => 'طاوِلَة', 'pronunciation' => 'taawilah', 'meaning' => 'table', 'category' => 'Object - feminine', 'example' => 'هذه طاوِلَة بُنِّيَّة.'],
        ['key' => 'sayyaarah', 'arabic' => 'سَيّارَة', 'pronunciation' => 'sayyaarah', 'meaning' => 'car', 'category' => 'Object - feminine', 'example' => 'هذه سَيّارَة حَمْراء.'],
        ['key' => 'miftaah', 'arabic' => 'مِفْتاح', 'pronunciation' => 'miftaah', 'meaning' => 'key', 'category' => 'Object - masculine', 'example' => 'هذا مِفْتاح أَصْفَر.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Colors & Objects Vocabulary', 'key' => 'B1-L06-Colors-Objects-Vocab', 'file' => '/assets/audio/books/beginner/lesson-6/B1-L06-Colors-Objects-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L06-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-6/B1-L06-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'هذا قَلَم أَحْمَر.', 'en' => 'This is a red pen.'],
        ['ar' => 'هذا كِتاب أَزْرَق.', 'en' => 'This is a blue book.'],
        ['ar' => 'هذا هاتِف أَسْوَد.', 'en' => 'This is a black phone.'],
        ['ar' => 'هذا باب أَبْيَض.', 'en' => 'This is a white door.'],
        ['ar' => 'هذه حَقيبَة زَرْقاء.', 'en' => 'This is a blue bag.'],
        ['ar' => 'هذه ساعَة سَوْداء.', 'en' => 'This is a black watch.'],
        ['ar' => 'هذه سَيّارَة حَمْراء.', 'en' => 'This is a red car.'],
        ['ar' => 'هذه وَرَقَة بَيْضاء.', 'en' => 'This is a white paper.'],
        ['ar' => 'ما لَوْن هذا؟', 'en' => 'What color is this? - masculine item'],
        ['ar' => 'ما لَوْن هذه؟', 'en' => 'What color is this? - feminine item'],
        ['ar' => 'هذا لَوْنُه أَحْمَر.', 'en' => 'This color is red.'],
        ['ar' => 'هذه لَوْنُها زَرْقاء.', 'en' => 'This color is blue.'],
    ],
    'grammar_tip' => [
        'title' => 'Review: هذا / هذه and color position',
        'body' => 'Use هذا with many masculine objects and هذه with many feminine objects. In Arabic, the color usually comes after the object: object + color.',
        'examples' => [
            ['ar' => 'هذا قَلَم.', 'en' => 'This is a pen.'],
            ['ar' => 'هذه حَقيبَة.', 'en' => 'This is a bag.'],
            ['ar' => 'قَلَم أَحْمَر', 'en' => 'red pen'],
            ['ar' => 'حَقيبَة زَرْقاء', 'en' => 'blue bag'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: ما هذا؟',
        'B: هذا قَلَم.',
        'A: ما لَوْن القَلَم؟',
        'B: هذا قَلَم أَحْمَر.',
        'A: ما هذه؟',
        'B: هذه حَقيبَة.',
        'A: ما لَوْن الحَقيبَة؟',
        'B: هذه حَقيبَة زَرْقاء.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: What is this?',
        'B: This is a pen.',
        'A: What color is the pen?',
        'B: This is a red pen.',
        'A: What is this?',
        'B: This is a bag.',
        'A: What color is the bag?',
        'B: This is a blue bag.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does أَحْمَر mean?', 'options' => ['A' => 'red', 'B' => 'blue', 'C' => 'black'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'What does أَزْرَق mean?', 'options' => ['A' => 'green', 'B' => 'blue', 'C' => 'white'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'What does قَلَم mean?', 'options' => ['A' => 'book', 'B' => 'bag', 'C' => 'pen'], 'correct' => 'C'],
        ['id' => 'mcq_4', 'question' => 'هذا قَلَم أَحْمَر means:', 'options' => ['A' => 'This is a red pen.', 'B' => 'This is a blue bag.', 'C' => 'This is a black phone.'], 'correct' => 'A'],
        ['id' => 'mcq_5', 'question' => 'هذه حَقيبَة زَرْقاء means:', 'options' => ['A' => 'This is a red car.', 'B' => 'This is a blue bag.', 'C' => 'This is a white paper.'], 'correct' => 'B'],
    ],
    'color_recognition' => [
        ['id' => 'color_1', 'question' => 'أَبْيَض', 'options' => ['A' => 'white', 'B' => 'black', 'C' => 'red'], 'correct' => 'A'],
        ['id' => 'color_2', 'question' => 'أَسْوَد', 'options' => ['A' => 'yellow', 'B' => 'black', 'C' => 'blue'], 'correct' => 'B'],
        ['id' => 'color_3', 'question' => 'أَخْضَر', 'options' => ['A' => 'green', 'B' => 'brown', 'C' => 'grey'], 'correct' => 'A'],
        ['id' => 'color_4', 'question' => 'أَصْفَر', 'options' => ['A' => 'red', 'B' => 'yellow', 'C' => 'white'], 'correct' => 'B'],
        ['id' => 'color_5', 'question' => 'بُنِّي', 'options' => ['A' => 'brown', 'B' => 'green', 'C' => 'blue'], 'correct' => 'A'],
        ['id' => 'color_6', 'question' => 'رَمادي', 'options' => ['A' => 'grey', 'B' => 'black', 'C' => 'red'], 'correct' => 'A'],
    ],
    'matching' => [
        ['id' => 'match_qalam', 'arabic' => 'قَلَم', 'correct' => 'pen'],
        ['id' => 'match_kitaab', 'arabic' => 'كِتاب', 'correct' => 'book'],
        ['id' => 'match_haatif', 'arabic' => 'هاتِف', 'correct' => 'phone'],
        ['id' => 'match_kursi', 'arabic' => 'كُرْسي', 'correct' => 'chair'],
        ['id' => 'match_haqeebah', 'arabic' => 'حَقيبَة', 'correct' => 'bag'],
        ['id' => 'match_saaah', 'arabic' => 'ساعَة', 'correct' => 'watch / clock'],
        ['id' => 'match_waraqah', 'arabic' => 'وَرَقَة', 'correct' => 'paper'],
        ['id' => 'match_sayyaarah', 'arabic' => 'سَيّارَة', 'correct' => 'car'],
    ],
    'matching_options' => ['pen', 'book', 'phone', 'chair', 'bag', 'watch / clock', 'paper', 'car'],
    'description_matching' => [
        ['id' => 'desc_1', 'arabic' => 'قَلَم أَحْمَر', 'correct' => 'red pen'],
        ['id' => 'desc_2', 'arabic' => 'كِتاب أَزْرَق', 'correct' => 'blue book'],
        ['id' => 'desc_3', 'arabic' => 'هاتِف أَسْوَد', 'correct' => 'black phone'],
        ['id' => 'desc_4', 'arabic' => 'حَقيبَة زَرْقاء', 'correct' => 'blue bag'],
        ['id' => 'desc_5', 'arabic' => 'وَرَقَة بَيْضاء', 'correct' => 'white paper'],
        ['id' => 'desc_6', 'arabic' => 'سَيّارَة حَمْراء', 'correct' => 'red car'],
    ],
    'description_matching_options' => ['red pen', 'blue book', 'black phone', 'blue bag', 'white paper', 'red car'],
    'number_recognition' => [],
    'category_practice' => [],
    'price_recognition' => [],
    'listening_review' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'هذا قَلَم ________.'],
        ['id' => 'cs_2', 'prompt' => 'هذه حَقيبَة ________.'],
        ['id' => 'cs_3', 'prompt' => 'هذا ________ أَسْوَد.'],
        ['id' => 'cs_4', 'prompt' => 'هذه ________ بَيْضاء.'],
        ['id' => 'cs_5', 'prompt' => 'ما لَوْن هذا؟ هذا ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Describe 5 Objects',
    'writing_instructions' => 'Write 5 Arabic sentences describing objects with colors. Use هذا / هذه and object + color order.',
    'writing_placeholder' => 'اكتب هنا 5 جمل تصف أشياء وألوان...',
    'min_sentences' => 5,
    'speaking_title' => 'Speaking Task - Describe Objects Around You',
    'speaking_instructions' => 'Record yourself for 45-60 seconds. Describe at least 5 objects, use هذا / هذه, use at least 4 colors, and ask one color question. Direct browser recording only.',
    'self_check_min' => 4,
    'self_check' => [
        'colors_arabic' => 'I can say basic colors in Arabic.',
        'objects_arabic' => 'I can say common objects in Arabic.',
        'use_haadha' => 'I can use هذا with simple examples.',
        'use_haadhihi' => 'I can use هذه with simple examples.',
        'describe_object_color' => 'I can describe an object using a color.',
        'write_descriptions' => 'I can write simple object descriptions.',
        'record_objects_speaking' => 'I can record a short speaking task describing objects.',
    ],
];
