<?php
declare(strict_types=1);

return [
    'unit_type' => 'lesson',
    'lesson_number' => 8,
    'title_en' => 'Time & Daily Routine',
    'title_ar' => 'الوَقْت وَالرُّوتين اليَوْمي',
    'slug' => 'lesson-8-time-daily-routine',
    'goal_en' => 'By the end of this lesson, you can say simple times and describe your daily routine in Arabic.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تقول الوقت بطريقة بسيطة وتصف روتينك اليومي باللغة العربية.',
    'goal_checks' => [
        'Say basic time words.',
        'Say morning, noon, evening, and night.',
        'Say simple clock times.',
        'Use في السّاعَة to say "at ... o’clock".',
        'Say basic daily actions.',
        'Use ثُمَّ and بَعْدَ ذَلِكَ to connect actions.',
        'Write and record a simple daily routine.',
    ],
    'situation_en' => 'You are talking to a new Arabic-speaking friend. They ask about your daily routine and what time you do things.',
    'situation_ar' => 'تتحدث مع صديق جديد يتكلم العربية. يسألك عن روتينك اليومي ومتى تفعل الأشياء خلال اليوم.',
    'warmup_title' => 'Quick Review from Lesson 7',
    'warmup_questions' => [
        'How do you say "I live in Dubai" in Arabic?',
        'How do you say "I am at home" in Arabic?',
        'How do you ask "Where is the restaurant?" in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'waqt', 'arabic' => 'وَقْت', 'pronunciation' => 'waqt', 'meaning' => 'time', 'category' => 'Time', 'example' => 'ما الوَقْت الآن؟'],
        ['key' => 'saah', 'arabic' => 'ساعَة', 'pronunciation' => "saa'ah", 'meaning' => 'hour / clock / o’clock', 'category' => 'Time', 'example' => 'السّاعَة واحِدَة.'],
        ['key' => 'al_yawm', 'arabic' => 'اليَوْم', 'pronunciation' => 'al-yawm', 'meaning' => 'today / the day', 'category' => 'Time', 'example' => 'اليَوْم جَميل.'],
        ['key' => 'as_sabaah', 'arabic' => 'الصَّباح', 'pronunciation' => 'as-sabaah', 'meaning' => 'morning', 'category' => 'Time', 'example' => 'أَصْحو في الصَّباح.'],
        ['key' => 'az_zuhr', 'arabic' => 'الظُّهْر', 'pronunciation' => 'az-zuhr', 'meaning' => 'noon / midday', 'category' => 'Time', 'example' => 'أَنا آكُل في الظُّهْر.'],
        ['key' => 'al_masaa', 'arabic' => 'المَساء', 'pronunciation' => "al-masaa'", 'meaning' => 'evening', 'category' => 'Time', 'example' => 'أَنا أَذْهَبُ في المَساء.'],
        ['key' => 'al_layl', 'arabic' => 'اللَّيْل', 'pronunciation' => 'al-layl', 'meaning' => 'night', 'category' => 'Time', 'example' => 'أَنامُ في اللَّيْل.'],
        ['key' => 'al_aan', 'arabic' => 'الآن', 'pronunciation' => 'al-aan', 'meaning' => 'now', 'category' => 'Time', 'example' => 'أَنا في البَيْت الآن.'],
        ['key' => 'baakiran', 'arabic' => 'باكِرًا', 'pronunciation' => 'baakiran', 'meaning' => 'early', 'category' => 'Time', 'example' => 'أَصْحو باكِرًا.'],
        ['key' => 'mutaakhkhiran', 'arabic' => 'مُتَأَخِّرًا', 'pronunciation' => "muta'akhkhiran", 'meaning' => 'late', 'category' => 'Time', 'example' => 'أَنامُ مُتَأَخِّرًا.'],
        ['key' => 'kulla_yawm', 'arabic' => 'كُلَّ يَوْم', 'pronunciation' => 'kulla yawm', 'meaning' => 'every day', 'category' => 'Time', 'example' => 'أَدْرُسُ كُلَّ يَوْم.'],
        ['key' => 'ahyaanan', 'arabic' => 'أَحيانًا', 'pronunciation' => 'ahyaanan', 'meaning' => 'sometimes', 'category' => 'Time', 'example' => 'أَحيانًا أَذْهَبُ إلى المَوْل.'],
        ['key' => 'ashu', 'arabic' => 'أَصْحو', 'pronunciation' => 'ashu', 'meaning' => 'I wake up', 'category' => 'Daily Action', 'example' => 'أَصْحو في السّاعَة سَبْعَة.'],
        ['key' => 'aghsil_wajhi', 'arabic' => 'أَغْسِل وَجْهي', 'pronunciation' => 'aghsil wajhi', 'meaning' => 'I wash my face', 'category' => 'Daily Action', 'example' => 'أَغْسِل وَجْهي في الصَّباح.'],
        ['key' => 'aftur', 'arabic' => 'أَفْطُر', 'pronunciation' => 'aftur', 'meaning' => 'I have breakfast', 'category' => 'Daily Action', 'example' => 'أَفْطُر في السّاعَة ثَمانِيَة.'],
        ['key' => 'adhhabu', 'arabic' => 'أَذْهَبُ', 'pronunciation' => 'adhhabu', 'meaning' => 'I go', 'category' => 'Daily Action', 'example' => 'أَذْهَبُ إلى العَمَل.'],
        ['key' => 'amalu', 'arabic' => 'أَعْمَلُ', 'pronunciation' => "a'malu", 'meaning' => 'I work', 'category' => 'Daily Action', 'example' => 'أَعْمَلُ في الصَّباح.'],
        ['key' => 'adrusu', 'arabic' => 'أَدْرُسُ', 'pronunciation' => 'adrusu', 'meaning' => 'I study', 'category' => 'Daily Action', 'example' => 'أَدْرُسُ العَرَبِيَّة.'],
        ['key' => 'aakulu', 'arabic' => 'آكُلُ', 'pronunciation' => 'aakulu', 'meaning' => 'I eat', 'category' => 'Daily Action', 'example' => 'آكُلُ في الظُّهْر.'],
        ['key' => 'ashrabu', 'arabic' => 'أَشْرَبُ', 'pronunciation' => 'ashrabu', 'meaning' => 'I drink', 'category' => 'Daily Action', 'example' => 'أَشْرَبُ ماءً.'],
        ['key' => 'arjiu', 'arabic' => 'أَرْجِعُ', 'pronunciation' => "arji'u", 'meaning' => 'I return', 'category' => 'Daily Action', 'example' => 'أَرْجِعُ إلى البَيْت.'],
        ['key' => 'astareehu', 'arabic' => 'أَسْتَريحُ', 'pronunciation' => 'astareehu', 'meaning' => 'I rest', 'category' => 'Daily Action', 'example' => 'أَسْتَريحُ في المَساء.'],
        ['key' => 'anaamu', 'arabic' => 'أَنامُ', 'pronunciation' => 'anaamu', 'meaning' => 'I sleep', 'category' => 'Daily Action', 'example' => 'أَنامُ في اللَّيْل.'],
        ['key' => 'alabu', 'arabic' => 'أَلْعَبُ', 'pronunciation' => "al'abu", 'meaning' => 'I play', 'category' => 'Daily Action', 'example' => 'أَلْعَبُ في المَساء.'],
        ['key' => 'ushaahidu', 'arabic' => 'أُشاهِدُ', 'pronunciation' => 'ushaahidu', 'meaning' => 'I watch', 'category' => 'Daily Action', 'example' => 'أُشاهِدُ فيديو.'],
        ['key' => 'aqrau', 'arabic' => 'أَقْرَأُ', 'pronunciation' => "aqra'u", 'meaning' => 'I read', 'category' => 'Daily Action', 'example' => 'أَقْرَأُ كِتابًا.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Time & Daily Routine Vocabulary', 'key' => 'B1-L08-Time-Routine-Vocab', 'file' => '/assets/audio/books/beginner/lesson-8/B1-L08-Time-Routine-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L08-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-8/B1-L08-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'ما الوَقْت الآن؟', 'en' => 'What time is it now?'],
        ['ar' => 'السّاعَة واحِدَة.', 'en' => 'It is one o’clock.'],
        ['ar' => 'السّاعَة اِثْنان.', 'en' => 'It is two o’clock.'],
        ['ar' => 'السّاعَة ثَلاثَة.', 'en' => 'It is three o’clock.'],
        ['ar' => 'السّاعَة خَمْسَة.', 'en' => 'It is five o’clock.'],
        ['ar' => 'السّاعَة سَبْعَة.', 'en' => 'It is seven o’clock.'],
        ['ar' => 'السّاعَة عَشَرَة.', 'en' => 'It is ten o’clock.'],
        ['ar' => 'في السّاعَة سَبْعَة.', 'en' => 'At seven o’clock.'],
        ['ar' => 'في الصَّباح.', 'en' => 'In the morning.'],
        ['ar' => 'في المَساء.', 'en' => 'In the evening.'],
        ['ar' => 'أَصْحو في السّاعَة سَبْعَة.', 'en' => 'I wake up at seven o’clock.'],
        ['ar' => 'أَفْطُر في السّاعَة ثَمانِيَة.', 'en' => 'I have breakfast at eight o’clock.'],
        ['ar' => 'أَذْهَبُ إلى العَمَل.', 'en' => 'I go to work.'],
        ['ar' => 'أَدْرُسُ العَرَبِيَّة في المَساء.', 'en' => 'I study Arabic in the evening.'],
        ['ar' => 'آكُلُ في الظُّهْر.', 'en' => 'I eat at noon.'],
        ['ar' => 'أَرْجِعُ إلى البَيْت.', 'en' => 'I return home.'],
        ['ar' => 'أَسْتَريحُ في المَساء.', 'en' => 'I rest in the evening.'],
        ['ar' => 'أَنامُ في اللَّيْل.', 'en' => 'I sleep at night.'],
        ['ar' => 'كُلَّ يَوْم أَدْرُسُ العَرَبِيَّة.', 'en' => 'Every day, I study Arabic.'],
    ],
    'grammar_tip' => [
        'title' => 'How to talk about time and connect daily actions',
        'body' => 'Use في السّاعَة before a time to say "at ... o’clock". Use ثُمَّ for "then" and بَعْدَ ذَلِكَ for "after that" to make your routine longer and clearer.',
        'examples' => [
            ['ar' => 'في السّاعَة واحِدَة.', 'en' => 'at one o’clock'],
            ['ar' => 'في السّاعَة سَبْعَة.', 'en' => 'at seven o’clock'],
            ['ar' => 'أَصْحو في السّاعَة سَبْعَة.', 'en' => 'I wake up at seven o’clock.'],
            ['ar' => 'أَصْحو، ثُمَّ أَفْطُر.', 'en' => 'I wake up, then I have breakfast.'],
            ['ar' => 'بَعْدَ ذَلِكَ أَدْرُسُ العَرَبِيَّة.', 'en' => 'After that, I study Arabic.'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: ما الوَقْت الآن؟',
        'B: السّاعَة سَبْعَة.',
        'A: ماذا تَفْعَل في الصَّباح؟',
        'B: أَصْحو في السّاعَة سَبْعَة، ثُمَّ أَفْطُر.',
        'A: هَلْ تَذْهَبُ إلى العَمَل؟',
        'B: نَعَم، أَذْهَبُ إلى العَمَل.',
        'A: ماذا تَفْعَل في المَساء؟',
        'B: أَدْرُسُ العَرَبِيَّة، ثُمَّ أَسْتَريحُ.',
        'A: مَتى تَنام؟',
        'B: أَنامُ في اللَّيْل.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: What time is it now?',
        'B: It is seven o’clock.',
        'A: What do you do in the morning?',
        'B: I wake up at seven o’clock, then I have breakfast.',
        'A: Do you go to work?',
        'B: Yes, I go to work.',
        'A: What do you do in the evening?',
        'B: I study Arabic, then I rest.',
        'A: When do you sleep?',
        'B: I sleep at night.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does الصَّباح mean?', 'options' => ['A' => 'morning', 'B' => 'evening', 'C' => 'night'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'What does أَصْحو mean?', 'options' => ['A' => 'I sleep', 'B' => 'I wake up', 'C' => 'I eat'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'أَنامُ في اللَّيْل means:', 'options' => ['A' => 'I sleep at night.', 'B' => 'I work in the morning.', 'C' => 'I study Arabic.'], 'correct' => 'A'],
        ['id' => 'mcq_4', 'question' => 'في السّاعَة سَبْعَة means:', 'options' => ['A' => 'at seven o’clock', 'B' => 'at ten o’clock', 'C' => 'in the evening'], 'correct' => 'A'],
        ['id' => 'mcq_5', 'question' => 'ثُمَّ means:', 'options' => ['A' => 'where', 'B' => 'then', 'C' => 'price'], 'correct' => 'B'],
    ],
    'time_recognition' => [
        ['id' => 'time_1', 'question' => 'السّاعَة واحِدَة', 'options' => ['A' => 'It is one o’clock.', 'B' => 'It is seven o’clock.', 'C' => 'It is ten o’clock.'], 'correct' => 'A'],
        ['id' => 'time_2', 'question' => 'السّاعَة خَمْسَة', 'options' => ['A' => 'It is three o’clock.', 'B' => 'It is five o’clock.', 'C' => 'It is fifteen.'], 'correct' => 'B'],
        ['id' => 'time_3', 'question' => 'السّاعَة عَشَرَة', 'options' => ['A' => 'It is ten o’clock.', 'B' => 'It is twenty.', 'C' => 'It is one o’clock.'], 'correct' => 'A'],
        ['id' => 'time_4', 'question' => 'في الصَّباح', 'options' => ['A' => 'in the morning', 'B' => 'at night', 'C' => 'in the mall'], 'correct' => 'A'],
        ['id' => 'time_5', 'question' => 'في المَساء', 'options' => ['A' => 'at noon', 'B' => 'in the evening', 'C' => 'in the kitchen'], 'correct' => 'B'],
        ['id' => 'time_6', 'question' => 'في اللَّيْل', 'options' => ['A' => 'at night', 'B' => 'in the morning', 'C' => 'every day'], 'correct' => 'A'],
    ],
    'daily_action_matching' => [
        ['id' => 'match_ashu', 'arabic' => 'أَصْحو', 'correct' => 'I wake up'],
        ['id' => 'match_aftur', 'arabic' => 'أَفْطُر', 'correct' => 'I have breakfast'],
        ['id' => 'match_adhhab', 'arabic' => 'أَذْهَبُ', 'correct' => 'I go'],
        ['id' => 'match_amalu', 'arabic' => 'أَعْمَلُ', 'correct' => 'I work'],
        ['id' => 'match_adrusu', 'arabic' => 'أَدْرُسُ', 'correct' => 'I study'],
        ['id' => 'match_aakulu', 'arabic' => 'آكُلُ', 'correct' => 'I eat'],
        ['id' => 'match_arjiu', 'arabic' => 'أَرْجِعُ', 'correct' => 'I return'],
        ['id' => 'match_astareehu', 'arabic' => 'أَسْتَريحُ', 'correct' => 'I rest'],
        ['id' => 'match_anaamu', 'arabic' => 'أَنامُ', 'correct' => 'I sleep'],
        ['id' => 'match_aqrau', 'arabic' => 'أَقْرَأُ', 'correct' => 'I read'],
    ],
    'daily_action_matching_options' => ['I wake up', 'I have breakfast', 'I go', 'I work', 'I study', 'I eat', 'I return', 'I rest', 'I sleep', 'I read'],
    'sequence_practice' => [
        ['id' => 'seq_sleep', 'sentence' => 'أَنامُ في اللَّيْل.', 'correct_order' => 5],
        ['id' => 'seq_wake', 'sentence' => 'أَصْحو في السّاعَة سَبْعَة.', 'correct_order' => 1],
        ['id' => 'seq_breakfast', 'sentence' => 'أَفْطُر في الصَّباح.', 'correct_order' => 2],
        ['id' => 'seq_work', 'sentence' => 'أَذْهَبُ إلى العَمَل.', 'correct_order' => 3],
        ['id' => 'seq_return', 'sentence' => 'أَرْجِعُ إلى البَيْت.', 'correct_order' => 4],
    ],
    'matching' => [],
    'matching_options' => [],
    'category_practice' => [],
    'number_recognition' => [],
    'price_recognition' => [],
    'color_recognition' => [],
    'description_matching' => [],
    'listening_review' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'أَصْحو في السّاعَة ________.'],
        ['id' => 'cs_2', 'prompt' => 'أَفْطُر في ________.'],
        ['id' => 'cs_3', 'prompt' => 'أَذْهَبُ إلى ________.'],
        ['id' => 'cs_4', 'prompt' => 'أَدْرُسُ العَرَبِيَّة في ________.'],
        ['id' => 'cs_5', 'prompt' => 'أَنامُ في ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write About Your Daily Routine',
    'writing_instructions' => 'Write 6 Arabic sentences about your daily routine. Use time expressions like في السّاعَة, في الصَّباح, في المَساء, and connect actions with ثُمَّ or بَعْدَ ذَلِكَ if you can.',
    'writing_placeholder' => 'اكتب هنا 6 جمل عن روتينك اليومي...',
    'min_sentences' => 6,
    'speaking_title' => 'Speaking Task - Talk About Your Daily Routine',
    'speaking_instructions' => 'Record yourself for about 60 seconds. Include a greeting, what time you wake up, what you do in the morning, where you go, what you do at noon/evening, when you sleep, and use ثُمَّ or بَعْدَ ذَلِكَ at least once. Direct browser recording only.',
    'self_check_min' => 4,
    'self_check' => [
        'basic_times' => 'I can say basic times in Arabic.',
        'parts_of_day' => 'I can say morning, evening, and night in Arabic.',
        'wake_up_time' => 'I can say what time I wake up.',
        'daily_actions' => 'I can say basic daily actions in Arabic.',
        'use_fee_alsaah' => 'I can use في السّاعَة in simple sentences.',
        'use_thumma_bad_thalik' => 'I can use ثُمَّ or بَعْدَ ذَلِكَ.',
        'write_record_routine' => 'I can write and record a simple daily routine.',
    ],
];
