<?php
declare(strict_types=1);

$numbers = [
    ['digit' => '0', 'arabic' => 'صِفْر', 'pronunciation' => 'sifr', 'meaning' => 'zero'],
    ['digit' => '1', 'arabic' => 'واحِد', 'pronunciation' => 'waahid', 'meaning' => 'one'],
    ['digit' => '2', 'arabic' => 'اِثْنان', 'pronunciation' => 'ithnaan', 'meaning' => 'two'],
    ['digit' => '3', 'arabic' => 'ثَلاثَة', 'pronunciation' => 'thalaatha', 'meaning' => 'three'],
    ['digit' => '4', 'arabic' => 'أَرْبَعَة', 'pronunciation' => "arba'a", 'meaning' => 'four'],
    ['digit' => '5', 'arabic' => 'خَمْسَة', 'pronunciation' => 'khamsa', 'meaning' => 'five'],
    ['digit' => '6', 'arabic' => 'سِتَّة', 'pronunciation' => 'sitta', 'meaning' => 'six'],
    ['digit' => '7', 'arabic' => 'سَبْعَة', 'pronunciation' => "sab'a", 'meaning' => 'seven'],
    ['digit' => '8', 'arabic' => 'ثَمانِيَة', 'pronunciation' => 'thamaaniya', 'meaning' => 'eight'],
    ['digit' => '9', 'arabic' => 'تِسْعَة', 'pronunciation' => "tis'a", 'meaning' => 'nine'],
    ['digit' => '10', 'arabic' => 'عَشَرَة', 'pronunciation' => 'ashara', 'meaning' => 'ten'],
    ['digit' => '11', 'arabic' => 'أَحَدَ عَشَر', 'pronunciation' => 'ahada ashar', 'meaning' => 'eleven'],
    ['digit' => '12', 'arabic' => 'اِثْنا عَشَر', 'pronunciation' => 'ithna ashar', 'meaning' => 'twelve'],
    ['digit' => '13', 'arabic' => 'ثَلاثَةَ عَشَر', 'pronunciation' => 'thalaathata ashar', 'meaning' => 'thirteen'],
    ['digit' => '14', 'arabic' => 'أَرْبَعَةَ عَشَر', 'pronunciation' => "arba'ata ashar", 'meaning' => 'fourteen'],
    ['digit' => '15', 'arabic' => 'خَمْسَةَ عَشَر', 'pronunciation' => 'khamsata ashar', 'meaning' => 'fifteen'],
    ['digit' => '16', 'arabic' => 'سِتَّةَ عَشَر', 'pronunciation' => 'sittata ashar', 'meaning' => 'sixteen'],
    ['digit' => '17', 'arabic' => 'سَبْعَةَ عَشَر', 'pronunciation' => "sab'ata ashar", 'meaning' => 'seventeen'],
    ['digit' => '18', 'arabic' => 'ثَمانِيَةَ عَشَر', 'pronunciation' => 'thamaaniyata ashar', 'meaning' => 'eighteen'],
    ['digit' => '19', 'arabic' => 'تِسْعَةَ عَشَر', 'pronunciation' => "tis'ata ashar", 'meaning' => 'nineteen'],
    ['digit' => '20', 'arabic' => 'عِشْرون', 'pronunciation' => 'ishroon', 'meaning' => 'twenty'],
];

return [
    'lesson_number' => 2,
    'title_en' => 'Numbers, Age & Phone Number',
    'title_ar' => 'الأرقام، العمر، ورقم الهاتف',
    'slug' => 'lesson-2-numbers-age-phone-number',
    'goal_en' => 'By the end of this lesson, you can say your age, say your phone number, and understand simple numbers in Arabic.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تقول عمرك، وتقول رقم هاتفك، وتفهم الأرقام البسيطة باللغة العربية.',
    'goal_checks' => ['Say numbers from 0 to 20','Say your age','Ask someone about age','Say your phone number','Ask someone for their phone number','Record an introduction with age and phone number'],
    'situation_en' => 'You meet a new Arabic-speaking person. They ask your age and phone number. You need to answer clearly in Arabic.',
    'situation_ar' => 'تقابل شخصًا يتحدث العربية. يسألك عن عمرك ورقم هاتفك، وتحتاج أن تجيب بوضوح باللغة العربية.',
    'warmup_title' => 'Quick Review from Lesson 1',
    'warmup_questions' => ['How do you say "My name is Ahmed" in Arabic?','How do you say "I am from Egypt" in Arabic?','How do you say "I live in Dubai" in Arabic?'],
    'vocabulary' => array_map(static fn($n) => ['key' => 'number_' . $n['digit'], 'arabic' => $n['arabic'], 'pronunciation' => $n['pronunciation'], 'meaning' => $n['digit'] . ' - ' . $n['meaning'], 'example' => $n['digit']], $numbers),
    'audio_blocks' => [
        ['title' => 'Audio Practice - Numbers', 'key' => 'B1-L02-Numbers', 'file' => '/assets/audio/books/beginner/lesson-2/B1-L02-Numbers.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L02-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-2/B1-L02-Dialogue.mp3'],
        ['title' => 'Listening Number Task', 'key' => 'B1-L02-Listening-Numbers', 'file' => '/assets/audio/books/beginner/lesson-2/B1-L02-Listening-Numbers.mp3'],
    ],
    'sentences' => [
        ['ar' => 'كَمْ عُمْرُكَ؟', 'en' => 'How old are you? - to a male'],
        ['ar' => 'كَمْ عُمْرُكِ؟', 'en' => 'How old are you? - to a female'],
        ['ar' => 'عُمْري عِشْرون سَنَة.', 'en' => 'I am twenty years old.'],
        ['ar' => 'عُمْري خَمْسَةَ عَشَر سَنَة.', 'en' => 'I am fifteen years old.'],
        ['ar' => 'أَنا عُمْري عِشْرون سَنَة.', 'en' => 'I am twenty years old.'],
        ['ar' => 'ما رَقْمُ هاتِفِكَ؟', 'en' => 'What is your phone number? - to a male'],
        ['ar' => 'ما رَقْمُ هاتِفِكِ؟', 'en' => 'What is your phone number? - to a female'],
        ['ar' => 'رَقْمُ هاتِفي ...', 'en' => 'My phone number is ...'],
        ['ar' => 'رَقْمُ هاتِفي واحِد، اِثْنان، ثَلاثَة.', 'en' => 'My phone number is one, two, three.'],
        ['ar' => 'هَلْ مُمْكِن رَقْمُ هاتِفِكَ؟', 'en' => 'Can I have your phone number? - to a male'],
    ],
    'dialogue_ar' => ['A: السَّلامُ عَلَيْكُمْ.','B: وَعَلَيْكُمُ السَّلام.','A: ما اسْمُكَ؟','B: أَنا اسْمي أَحْمَد.','A: كَمْ عُمْرُكَ؟','B: عُمْري عِشْرون سَنَة.','A: ما رَقْمُ هاتِفِكَ؟','B: رَقْمُ هاتِفي واحِد، اِثْنان، ثَلاثَة، أَرْبَعَة.'],
    'dialogue_en' => ['A: Peace be upon you.','B: And peace be upon you.','A: What is your name?','B: My name is Ahmed.','A: How old are you?','B: I am twenty years old.','A: What is your phone number?','B: My phone number is one, two, three, four.'],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does واحِد mean?', 'options' => ['A' => 'one', 'B' => 'ten', 'C' => 'seven'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'What does عُمْري mean?', 'options' => ['A' => 'my name', 'B' => 'my age', 'C' => 'my city'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'كَمْ عُمْرُكَ؟ means:', 'options' => ['A' => 'What is your name?', 'B' => 'Where do you live?', 'C' => 'How old are you?'], 'correct' => 'C'],
        ['id' => 'mcq_4', 'question' => 'رَقْمُ هاتِفي means:', 'options' => ['A' => 'my phone number', 'B' => 'my country', 'C' => 'my age'], 'correct' => 'A'],
        ['id' => 'mcq_5', 'question' => 'What does خَمْسَة mean?', 'options' => ['A' => 'four', 'B' => 'five', 'C' => 'fifteen'], 'correct' => 'B'],
    ],
    'number_recognition' => [
        ['id' => 'nr_1', 'question' => '3 = ?', 'options' => ['A' => 'ثَلاثَة', 'B' => 'سَبْعَة', 'C' => 'عَشَرَة'], 'correct' => 'A'],
        ['id' => 'nr_2', 'question' => '7 = ?', 'options' => ['A' => 'أَرْبَعَة', 'B' => 'سَبْعَة', 'C' => 'تِسْعَة'], 'correct' => 'B'],
        ['id' => 'nr_3', 'question' => '10 = ?', 'options' => ['A' => 'واحِد', 'B' => 'عَشَرَة', 'C' => 'عِشْرون'], 'correct' => 'B'],
        ['id' => 'nr_4', 'question' => '15 = ?', 'options' => ['A' => 'خَمْسَةَ عَشَر', 'B' => 'خَمْسَة', 'C' => 'خَمْسون'], 'correct' => 'A'],
        ['id' => 'nr_5', 'question' => '20 = ?', 'options' => ['A' => 'اِثْنان', 'B' => 'عِشْرون', 'C' => 'عَشَرَة'], 'correct' => 'B'],
    ],
    'listening_numbers' => [
        ['id' => 'ln_1', 'question' => 'What number did you hear?', 'options' => ['A' => '4', 'B' => '5', 'C' => '9'], 'correct' => 'B'],
        ['id' => 'ln_2', 'question' => 'What number did you hear?', 'options' => ['A' => '10', 'B' => '2', 'C' => '12'], 'correct' => 'A'],
        ['id' => 'ln_3', 'question' => 'What number did you hear?', 'options' => ['A' => '7', 'B' => '17', 'C' => '11'], 'correct' => 'A'],
        ['id' => 'ln_4', 'question' => 'What number did you hear?', 'options' => ['A' => '2', 'B' => '20', 'C' => '12'], 'correct' => 'B'],
        ['id' => 'ln_5', 'question' => 'What number did you hear?', 'options' => ['A' => '3', 'B' => '8', 'C' => '13'], 'correct' => 'A'],
    ],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'أَنا اسْمي ________.'],
        ['id' => 'cs_2', 'prompt' => 'عُمْري ________ سَنَة.'],
        ['id' => 'cs_3', 'prompt' => 'رَقْمُ هاتِفي ________.'],
        ['id' => 'cs_4', 'prompt' => 'أَنا أَعيشُ في ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write Your Basic Information',
    'writing_instructions' => 'Write 4-5 Arabic sentences about yourself. You can use a fake phone number for practice.',
    'writing_placeholder' => 'اكتب هنا 4 أو 5 جمل عن نفسك...',
    'min_sentences' => 4,
    'speaking_title' => 'Speaking Task - Record Your Information',
    'speaking_instructions' => 'Record yourself for 30-45 seconds. Include greeting, name, country, city, age, a practice phone number, and one question.',
    'self_check' => [
        'numbers_0_20' => 'I can say numbers from 0 to 20.',
        'say_age' => 'I can say my age in Arabic.',
        'ask_age' => 'I can ask someone about their age.',
        'say_phone' => 'I can say a phone number in Arabic.',
        'ask_phone' => 'I can ask for someone’s phone number.',
        'record_intro_age_phone' => 'I can record a short introduction with my age and phone number.',
    ],
];
