<?php
declare(strict_types=1);

return [
    'unit_type' => 'lesson',
    'lesson_number' => 5,
    'title_en' => 'Shopping',
    'title_ar' => 'التَّسَوُّق',
    'slug' => 'lesson-5-shopping',
    'goal_en' => 'By the end of this lesson, you can ask about prices and buy simple items in Arabic.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تسأل عن الأسعار وتشتري أشياء بسيطة باللغة العربية.',
    'goal_checks' => [
        'Say basic shopping words.',
        'Ask "How much?" in Arabic.',
        'Say "I want this."',
        'Use هذا and هذه.',
        'Say expensive and cheap.',
        'Make a simple purchase.',
        'Record a short shopping role-play.',
    ],
    'situation_en' => 'You are shopping in a mall or small shop in Dubai. You want to ask about the price and buy one item in Arabic.',
    'situation_ar' => 'أنت تتسوق في مول أو محل صغير في دبي. تريد أن تسأل عن السعر وتشتري شيئًا واحدًا باللغة العربية.',
    'warmup_title' => 'Quick Review from Review 1',
    'warmup_questions' => [
        'How do you say "I want water" in Arabic?',
        'How do you say "I am from Egypt" in Arabic?',
        'How do you say "Thank you" in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'tasawwuq', 'arabic' => 'تَسَوُّق', 'pronunciation' => 'tasawwuq', 'meaning' => 'shopping', 'category' => 'Topic', 'example' => 'أُحِبُّ التَّسَوُّق.'],
        ['key' => 'mahall', 'arabic' => 'مَحَلّ', 'pronunciation' => 'mahall', 'meaning' => 'shop / store', 'category' => 'Place', 'example' => 'هذا مَحَلّ جَميل.'],
        ['key' => 'sir', 'arabic' => 'سِعْر', 'pronunciation' => "si'r", 'meaning' => 'price', 'category' => 'Price', 'example' => 'كَم السِّعْر؟'],
        ['key' => 'fuloos', 'arabic' => 'فُلوس', 'pronunciation' => 'fuloos', 'meaning' => 'money', 'category' => 'Price', 'example' => 'عِنْدي فُلوس.'],
        ['key' => 'dirham', 'arabic' => 'دِرْهَم', 'pronunciation' => 'dirham', 'meaning' => 'dirham', 'category' => 'Price', 'example' => 'السِّعْر عَشَرَة دَراهِم.'],
        ['key' => 'bikam', 'arabic' => 'بِكَم؟', 'pronunciation' => 'bikam?', 'meaning' => 'how much?', 'category' => 'Phrase', 'example' => 'هذا بِكَم؟'],
        ['key' => 'kam_as_sir', 'arabic' => 'كَم السِّعْر؟', 'pronunciation' => "kam as-si'r?", 'meaning' => 'how much is the price?', 'category' => 'Phrase', 'example' => 'كَم السِّعْر؟'],
        ['key' => 'ureed_haadha', 'arabic' => 'أُريد هذا', 'pronunciation' => 'ureed haadha', 'meaning' => 'I want this - masculine', 'category' => 'Phrase', 'example' => 'أُريد هذا.'],
        ['key' => 'ureed_haadhihi', 'arabic' => 'أُريد هذه', 'pronunciation' => 'ureed haadhihi', 'meaning' => 'I want this - feminine', 'category' => 'Phrase', 'example' => 'أُريد هذه.'],
        ['key' => 'haadha', 'arabic' => 'هذا', 'pronunciation' => 'haadha', 'meaning' => 'this - masculine', 'category' => 'Pointer', 'example' => 'هذا قَلَم.'],
        ['key' => 'haadhihi', 'arabic' => 'هذه', 'pronunciation' => 'haadhihi', 'meaning' => 'this - feminine', 'category' => 'Pointer', 'example' => 'هذه حَقيبَة.'],
        ['key' => 'ghaalee', 'arabic' => 'غالي', 'pronunciation' => 'ghaalee', 'meaning' => 'expensive - masculine', 'category' => 'Description', 'example' => 'هذا غالي.'],
        ['key' => 'ghaaliyah', 'arabic' => 'غالِيَة', 'pronunciation' => 'ghaaliyah', 'meaning' => 'expensive - feminine', 'category' => 'Description', 'example' => 'هذه غالِيَة.'],
        ['key' => 'rakhees', 'arabic' => 'رَخيص', 'pronunciation' => 'rakhees', 'meaning' => 'cheap - masculine', 'category' => 'Description', 'example' => 'هذا رَخيص.'],
        ['key' => 'rakheesah', 'arabic' => 'رَخيصَة', 'pronunciation' => 'rakheesah', 'meaning' => 'cheap - feminine', 'category' => 'Description', 'example' => 'هذه رَخيصَة.'],
        ['key' => 'qalam', 'arabic' => 'قَلَم', 'pronunciation' => 'qalam', 'meaning' => 'pen', 'category' => 'Item', 'example' => 'هذا قَلَم.'],
        ['key' => 'kitaab', 'arabic' => 'كِتاب', 'pronunciation' => 'kitaab', 'meaning' => 'book', 'category' => 'Item', 'example' => 'هذا كِتاب.'],
        ['key' => 'haqeebah', 'arabic' => 'حَقيبَة', 'pronunciation' => 'haqeebah', 'meaning' => 'bag', 'category' => 'Item', 'example' => 'هذه حَقيبَة.'],
        ['key' => 'qamees', 'arabic' => 'قَميص', 'pronunciation' => 'qamees', 'meaning' => 'shirt', 'category' => 'Item', 'example' => 'هذا قَميص.'],
        ['key' => 'ashtaree', 'arabic' => 'أَشْتَري', 'pronunciation' => 'ashtaree', 'meaning' => 'I buy', 'category' => 'Verb', 'example' => 'أُريد أَنْ أَشْتَري هذا.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Shopping Vocabulary', 'key' => 'B1-L05-Shopping-Vocab', 'file' => '/assets/audio/books/beginner/lesson-5/B1-L05-Shopping-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L05-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-5/B1-L05-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'هذا بِكَم؟', 'en' => 'How much is this? - masculine item'],
        ['ar' => 'هذه بِكَم؟', 'en' => 'How much is this? - feminine item'],
        ['ar' => 'كَم السِّعْر؟', 'en' => 'How much is the price?'],
        ['ar' => 'أُريد هذا.', 'en' => 'I want this. - masculine item'],
        ['ar' => 'أُريد هذه.', 'en' => 'I want this. - feminine item'],
        ['ar' => 'أُريد أَنْ أَشْتَري هذا.', 'en' => 'I want to buy this.'],
        ['ar' => 'السِّعْر عَشَرَة دَراهِم.', 'en' => 'The price is ten dirhams.'],
        ['ar' => 'هذا غالي.', 'en' => 'This is expensive. - masculine'],
        ['ar' => 'هذه غالِيَة.', 'en' => 'This is expensive. - feminine'],
        ['ar' => 'هذا رَخيص.', 'en' => 'This is cheap. - masculine'],
        ['ar' => 'هذه رَخيصَة.', 'en' => 'This is cheap. - feminine'],
        ['ar' => 'عِنْدَكَ حَجْم أَكْبَر؟', 'en' => 'Do you have a bigger size? - to a male'],
        ['ar' => 'عِنْدَكِ حَجْم أَكْبَر؟', 'en' => 'Do you have a bigger size? - to a female'],
        ['ar' => 'شُكْرًا.', 'en' => 'Thank you.'],
    ],
    'grammar_tip' => [
        'title' => 'Shopping grammar tips',
        'body' => 'Use هذا with masculine words and هذه with feminine words. For shopping descriptions, use غالي / رَخيص with masculine items and غالِيَة / رَخيصَة with feminine items.',
        'examples' => [
            ['ar' => 'هذا قَلَم.', 'en' => 'This is a pen.'],
            ['ar' => 'هذه حَقيبَة.', 'en' => 'This is a bag.'],
            ['ar' => 'هذا غالي.', 'en' => 'This is expensive.'],
            ['ar' => 'هذه رَخيصَة.', 'en' => 'This is cheap.'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: هذا القَلَم بِكَم؟',
        'B: السِّعْر عَشَرَة دَراهِم.',
        'A: هذا غالي. عِنْدَكَ قَلَم رَخيص؟',
        'B: نَعَم، هذا قَلَم رَخيص.',
        'A: أُريد هذا، مِن فَضْلِكَ.',
        'B: حاضِر.',
        'A: شُكْرًا.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: How much is this pen?',
        'B: The price is ten dirhams.',
        'A: This is expensive. Do you have a cheap pen?',
        'B: Yes, this is a cheap pen.',
        'A: I want this, please.',
        'B: Sure.',
        'A: Thank you.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does بِكَم؟ mean?', 'options' => ['A' => 'How old?', 'B' => 'How much?', 'C' => 'Where?'], 'correct' => 'B'],
        ['id' => 'mcq_2', 'question' => 'What does سِعْر mean?', 'options' => ['A' => 'price', 'B' => 'family', 'C' => 'food'], 'correct' => 'A'],
        ['id' => 'mcq_3', 'question' => 'أُريد هذا means:', 'options' => ['A' => 'I want this.', 'B' => 'I do not want this.', 'C' => 'This is expensive.'], 'correct' => 'A'],
        ['id' => 'mcq_4', 'question' => 'هذا غالي means:', 'options' => ['A' => 'This is cheap.', 'B' => 'This is expensive.', 'C' => 'I want this.'], 'correct' => 'B'],
        ['id' => 'mcq_5', 'question' => 'رَخيص means:', 'options' => ['A' => 'cheap', 'B' => 'expensive', 'C' => 'price'], 'correct' => 'A'],
    ],
    'matching' => [
        ['id' => 'match_sir', 'arabic' => 'سِعْر', 'correct' => 'price'],
        ['id' => 'match_mahall', 'arabic' => 'مَحَلّ', 'correct' => 'shop'],
        ['id' => 'match_dirham', 'arabic' => 'دِرْهَم', 'correct' => 'dirham'],
        ['id' => 'match_ghaalee', 'arabic' => 'غالي', 'correct' => 'expensive'],
        ['id' => 'match_rakhees', 'arabic' => 'رَخيص', 'correct' => 'cheap'],
        ['id' => 'match_qalam', 'arabic' => 'قَلَم', 'correct' => 'pen'],
        ['id' => 'match_kitaab', 'arabic' => 'كِتاب', 'correct' => 'book'],
        ['id' => 'match_haqeebah', 'arabic' => 'حَقيبَة', 'correct' => 'bag'],
    ],
    'matching_options' => ['price', 'shop', 'dirham', 'expensive', 'cheap', 'pen', 'book', 'bag'],
    'price_recognition' => [
        ['id' => 'price_1', 'question' => 'عَشَرَة دَراهِم means:', 'options' => ['A' => '5 dirhams', 'B' => '10 dirhams', 'C' => '20 dirhams'], 'correct' => 'B'],
        ['id' => 'price_2', 'question' => 'خَمْسَة دَراهِم means:', 'options' => ['A' => '5 dirhams', 'B' => '15 dirhams', 'C' => '50 dirhams'], 'correct' => 'A'],
        ['id' => 'price_3', 'question' => 'عِشْرون دِرْهَمًا means:', 'options' => ['A' => '2 dirhams', 'B' => '10 dirhams', 'C' => '20 dirhams'], 'correct' => 'C'],
        ['id' => 'price_4', 'question' => 'كَم السِّعْر؟ means:', 'options' => ['A' => 'What is the price?', 'B' => 'What is your name?', 'C' => 'Where do you live?'], 'correct' => 'A'],
        ['id' => 'price_5', 'question' => 'السِّعْر عَشَرَة دَراهِم means:', 'options' => ['A' => 'The price is ten dirhams.', 'B' => 'I want ten dirhams.', 'C' => 'I have ten dirhams.'], 'correct' => 'A'],
    ],
    'number_recognition' => [],
    'category_practice' => [],
    'listening_review' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'هذا ________؟'],
        ['id' => 'cs_2', 'prompt' => 'كَم ________؟'],
        ['id' => 'cs_3', 'prompt' => 'أُريد ________.'],
        ['id' => 'cs_4', 'prompt' => 'هذا ________.'],
        ['id' => 'cs_5', 'prompt' => 'هذه ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write a Simple Shopping Conversation',
    'writing_instructions' => 'Write a short shopping conversation between a customer and a seller. Use price, هذا / هذه, expensive or cheap, and a polite buying sentence.',
    'writing_placeholder' => 'اكتب هنا محادثة قصيرة في محل...',
    'min_sentences' => 5,
    'speaking_title' => 'Speaking Task - Shopping Role-Play',
    'speaking_instructions' => 'Record yourself for 45-60 seconds. Ask about the price of one item, say if it is expensive or cheap, say you want to buy it, and say thank you. Direct browser recording only.',
    'self_check_min' => 4,
    'self_check' => [
        'ask_how_much' => 'I can ask "How much?" in Arabic.',
        'say_i_want_this' => 'I can say "I want this" in Arabic.',
        'use_haadha_haadhihi' => 'I can use هذا and هذه in simple examples.',
        'expensive_cheap' => 'I can say expensive and cheap in Arabic.',
        'understand_prices' => 'I can understand simple prices in Arabic.',
        'write_shopping_conversation' => 'I can write a short shopping conversation.',
        'record_shopping_roleplay' => 'I can record a short shopping role-play.',
    ],
];
