<?php
declare(strict_types=1);

return [
    'lesson_number' => 3,
    'title_en' => 'Family',
    'title_ar' => 'الأُسْرَة',
    'slug' => 'lesson-3-family',
    'goal_en' => 'By the end of this lesson, you can talk about your family using simple Arabic sentences.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تتحدث عن أسرتك بجمل عربية بسيطة.',
    'goal_checks' => [
        'Say basic family member words.',
        'Say “I have...” in Arabic.',
        'Say “I don’t have...” in Arabic.',
        'Ask someone about their family.',
        'Write 4-5 simple sentences about family.',
        'Record a short speaking task about family.',
    ],
    'situation_en' => 'You are talking with a new Arabic-speaking friend. They ask you about your family, and you want to answer in simple Arabic.',
    'situation_ar' => 'تتحدث مع صديق جديد يتكلم العربية. يسألك عن أسرتك، وتريد أن تجيب باللغة العربية بطريقة بسيطة.',
    'warmup_title' => 'Quick Review from Lessons 1-2',
    'warmup_questions' => [
        'How do you say “My name is Ahmed” in Arabic?',
        'How do you say “I live in Dubai” in Arabic?',
        'How do you say “I am twenty years old” in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'usrah', 'arabic' => 'أُسْرَة', 'pronunciation' => 'usrah', 'meaning' => 'family', 'example' => 'أُسْرَتي كَبيرَة.'],
        ['key' => 'aailah', 'arabic' => 'عائِلَة', 'pronunciation' => "aa'ilah", 'meaning' => 'family', 'example' => 'عائِلَتي في مِصْر.'],
        ['key' => 'ab', 'arabic' => 'أَب', 'pronunciation' => 'ab', 'meaning' => 'father', 'example' => 'عِنْدي أَب.'],
        ['key' => 'umm', 'arabic' => 'أُم', 'pronunciation' => 'umm', 'meaning' => 'mother', 'example' => 'عِنْدي أُم.'],
        ['key' => 'akh', 'arabic' => 'أَخ', 'pronunciation' => 'akh', 'meaning' => 'brother', 'example' => 'عِنْدي أَخ.'],
        ['key' => 'ukht', 'arabic' => 'أُخْت', 'pronunciation' => 'ukht', 'meaning' => 'sister', 'example' => 'عِنْدي أُخْت.'],
        ['key' => 'zawj', 'arabic' => 'زَوْج', 'pronunciation' => 'zawj', 'meaning' => 'husband', 'example' => 'عِنْدي زَوْج.'],
        ['key' => 'zawjah', 'arabic' => 'زَوْجَة', 'pronunciation' => 'zawjah', 'meaning' => 'wife', 'example' => 'عِنْدي زَوْجَة.'],
        ['key' => 'ibn', 'arabic' => 'اِبْن', 'pronunciation' => 'ibn', 'meaning' => 'son', 'example' => 'عِنْدي اِبْن.'],
        ['key' => 'bint', 'arabic' => 'بِنْت', 'pronunciation' => 'bint', 'meaning' => 'daughter / girl', 'example' => 'عِنْدي بِنْت.'],
        ['key' => 'atfaal', 'arabic' => 'أَطْفال', 'pronunciation' => 'atfaal', 'meaning' => 'children', 'example' => 'عِنْدي أَطْفال.'],
        ['key' => 'sagheer', 'arabic' => 'صَغير', 'pronunciation' => 'sagheer', 'meaning' => 'young / small - masculine', 'example' => 'أَخي صَغير.'],
        ['key' => 'sagheerah', 'arabic' => 'صَغيرَة', 'pronunciation' => 'sagheerah', 'meaning' => 'young / small - feminine', 'example' => 'أُخْتي صَغيرَة.'],
        ['key' => 'kabeer', 'arabic' => 'كَبير', 'pronunciation' => 'kabeer', 'meaning' => 'big / older - masculine', 'example' => 'أَخي كَبير.'],
        ['key' => 'kabeerah', 'arabic' => 'كَبيرَة', 'pronunciation' => 'kabeerah', 'meaning' => 'big / older - feminine', 'example' => 'أُخْتي كَبيرَة.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Family Vocabulary', 'key' => 'B1-L03-Family-Vocab', 'file' => '/assets/audio/books/beginner/lesson-3/B1-L03-Family-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L03-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-3/B1-L03-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'عِنْدي أَب.', 'en' => 'I have a father.'],
        ['ar' => 'عِنْدي أُم.', 'en' => 'I have a mother.'],
        ['ar' => 'عِنْدي أَخ.', 'en' => 'I have a brother.'],
        ['ar' => 'عِنْدي أُخْت.', 'en' => 'I have a sister.'],
        ['ar' => 'عِنْدي أَخ وَأُخْت.', 'en' => 'I have a brother and a sister.'],
        ['ar' => 'لَيْسَ عِنْدي أَخ.', 'en' => 'I do not have a brother.'],
        ['ar' => 'لَيْسَ عِنْدي أُخْت.', 'en' => 'I do not have a sister.'],
        ['ar' => 'عائِلَتي كَبيرَة.', 'en' => 'My family is big.'],
        ['ar' => 'عائِلَتي صَغيرَة.', 'en' => 'My family is small.'],
        ['ar' => 'أَخي كَبير.', 'en' => 'My brother is older/big.'],
        ['ar' => 'أُخْتي صَغيرَة.', 'en' => 'My sister is young/small.'],
        ['ar' => 'هَلْ عِنْدَكَ أَخ؟', 'en' => 'Do you have a brother? - to a male'],
        ['ar' => 'هَلْ عِنْدَكِ أُخْت؟', 'en' => 'Do you have a sister? - to a female'],
    ],
    'grammar_tip' => [
        'title' => 'How to say “I have” and “I don’t have”',
        'body' => 'Use عِنْدي to say “I have”. Use لَيْسَ عِنْدي to say “I do not have”. Focus on using the sentence pattern correctly in speaking.',
        'examples' => [
            ['ar' => 'عِنْدي أَخ.', 'en' => 'I have a brother.'],
            ['ar' => 'عِنْدي أُخْت.', 'en' => 'I have a sister.'],
            ['ar' => 'لَيْسَ عِنْدي أَخ.', 'en' => 'I do not have a brother.'],
            ['ar' => 'لَيْسَ عِنْدي أُخْت.', 'en' => 'I do not have a sister.'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: ما اسْمُكَ؟',
        'B: أَنا اسْمي أَحْمَد.',
        'A: هَلْ عِنْدَكَ أَخ؟',
        'B: نَعَم، عِنْدي أَخ.',
        'A: هَلْ عِنْدَكَ أُخْت؟',
        'B: لا، لَيْسَ عِنْدي أُخْت.',
        'A: عائِلَتُكَ كَبيرَة؟',
        'B: لا، عائِلَتي صَغيرَة.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: What is your name?',
        'B: My name is Ahmed.',
        'A: Do you have a brother?',
        'B: Yes, I have a brother.',
        'A: Do you have a sister?',
        'B: No, I do not have a sister.',
        'A: Is your family big?',
        'B: No, my family is small.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does أَب mean?', 'options' => ['A' => 'father', 'B' => 'mother', 'C' => 'brother'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'What does أُم mean?', 'options' => ['A' => 'sister', 'B' => 'mother', 'C' => 'daughter'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'عِنْدي أَخ means:', 'options' => ['A' => 'I have a brother.', 'B' => 'I have a sister.', 'C' => 'I am a brother.'], 'correct' => 'A'],
        ['id' => 'mcq_4', 'question' => 'لَيْسَ عِنْدي أُخْت means:', 'options' => ['A' => 'I have a sister.', 'B' => 'I do not have a sister.', 'C' => 'My sister is young.'], 'correct' => 'B'],
        ['id' => 'mcq_5', 'question' => 'عائِلَتي كَبيرَة means:', 'options' => ['A' => 'My family is small.', 'B' => 'My family is big.', 'C' => 'My father is big.'], 'correct' => 'B'],
    ],
    'matching' => [
        ['id' => 'match_ab', 'arabic' => 'أَب', 'correct' => 'father'],
        ['id' => 'match_umm', 'arabic' => 'أُم', 'correct' => 'mother'],
        ['id' => 'match_akh', 'arabic' => 'أَخ', 'correct' => 'brother'],
        ['id' => 'match_ukht', 'arabic' => 'أُخْت', 'correct' => 'sister'],
        ['id' => 'match_ibn', 'arabic' => 'اِبْن', 'correct' => 'son'],
        ['id' => 'match_bint', 'arabic' => 'بِنْت', 'correct' => 'daughter'],
    ],
    'matching_options' => ['father', 'mother', 'brother', 'sister', 'son', 'daughter'],
    'number_recognition' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'عِنْدي ________.'],
        ['id' => 'cs_2', 'prompt' => 'لَيْسَ عِنْدي ________.'],
        ['id' => 'cs_3', 'prompt' => 'عائِلَتي ________.'],
        ['id' => 'cs_4', 'prompt' => 'عِنْدي ________ وَ ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write About Your Family',
    'writing_instructions' => 'Write 4-5 Arabic sentences about your family. You can write about a practice/fake family if you do not want to share personal information.',
    'writing_placeholder' => 'اكتب هنا 4 أو 5 جمل عن أسرتك...',
    'min_sentences' => 4,
    'speaking_title' => 'Speaking Task - Talk About Your Family',
    'speaking_instructions' => 'Record yourself for 30-45 seconds. Include greeting, name, whether your family is big or small, two family members you have, one family member you do not have if applicable, and one question.',
    'self_check' => [
        'family_words' => 'I can say basic family words in Arabic.',
        'say_i_have' => 'I can say “I have...” in Arabic.',
        'say_i_dont_have' => 'I can say “I do not have...” in Arabic.',
        'ask_family' => 'I can ask someone about their family.',
        'write_family' => 'I can write simple sentences about my family.',
        'record_family' => 'I can record a short speaking task about my family.',
    ],
];
