<?php
declare(strict_types=1);

return [
    'lesson_number' => 1,
    'title_en' => 'Introduce Yourself',
    'title_ar' => 'عرّف نفسك',
    'slug' => 'lesson-1-introduce-yourself',
    'goal_en' => 'By the end of this lesson, you can introduce yourself in Arabic and ask another person simple personal questions.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تقدم نفسك باللغة العربية وتسأل شخصًا آخر أسئلة شخصية بسيطة.',
    'goal_checks' => ['Say your name','Say your country','Say where you live','Ask someone their name','Ask where someone is from','Record a short self-introduction'],
    'situation_en' => 'You meet a new person in Dubai. You want to introduce yourself in simple Arabic.',
    'situation_ar' => 'تقابل شخصًا جديدًا في دبي، وتريد أن تقدم نفسك باللغة العربية بطريقة بسيطة.',
    'warmup_title' => 'Warm-up Questions',
    'warmup_questions' => ['What is your name?','Where are you from?','Where do you live now?','Do you know any Arabic words?'],
    'vocabulary' => [
        ['key' => 'ism', 'arabic' => 'اِسْم', 'pronunciation' => 'ism', 'meaning' => 'name', 'example' => 'ما اِسْمُكَ؟'],
        ['key' => 'balad', 'arabic' => 'بَلَد', 'pronunciation' => 'balad', 'meaning' => 'country', 'example' => 'أَنا مِن بَلَدٍ جَميل.'],
        ['key' => 'madeenah', 'arabic' => 'مَدينَة', 'pronunciation' => 'madeenah', 'meaning' => 'city', 'example' => 'دُبَي مَدينَة جَميلَة.'],
        ['key' => 'aeeshu', 'arabic' => 'أَعيشُ', 'pronunciation' => "a'eeshu", 'meaning' => 'I live', 'example' => 'أَنا أَعيشُ في دُبَي.'],
        ['key' => 'ana', 'arabic' => 'أَنا', 'pronunciation' => 'ana', 'meaning' => 'I / me', 'example' => 'أَنا مُحَمَّد.'],
        ['key' => 'anta', 'arabic' => 'أَنْتَ', 'pronunciation' => 'anta', 'meaning' => 'you - male', 'example' => 'مِن أَيْنَ أَنْتَ؟'],
        ['key' => 'anti', 'arabic' => 'أَنْتِ', 'pronunciation' => 'anti', 'meaning' => 'you - female', 'example' => 'مِن أَيْنَ أَنْتِ؟'],
        ['key' => 'min', 'arabic' => 'مِن', 'pronunciation' => 'min', 'meaning' => 'from', 'example' => 'أَنا مِن مِصْر.'],
        ['key' => 'fee', 'arabic' => 'في', 'pronunciation' => 'fee', 'meaning' => 'in', 'example' => 'أَنا في دُبَي.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Vocabulary', 'key' => 'B1-L01-Vocab', 'file' => '/assets/audio/books/beginner/lesson-1/B1-L01-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L01-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-1/B1-L01-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'أَنا اسْمي أَحْمَد.', 'en' => 'My name is Ahmed.'],
        ['ar' => 'أَنا اسْمي سارا.', 'en' => 'My name is Sara.'],
        ['ar' => 'أَنا مِن مِصْر.', 'en' => 'I am from Egypt.'],
        ['ar' => 'أَنا مِنَ الهِنْد.', 'en' => 'I am from India.'],
        ['ar' => 'أَنا أَعيشُ في دُبَي.', 'en' => 'I live in Dubai.'],
        ['ar' => 'أَنا أَعيشُ في الشّارِقَة.', 'en' => 'I live in Sharjah.'],
        ['ar' => 'ما اسْمُكَ؟', 'en' => 'What is your name? - to a male'],
        ['ar' => 'ما اسْمُكِ؟', 'en' => 'What is your name? - to a female'],
        ['ar' => 'مِن أَيْنَ أَنْتَ؟', 'en' => 'Where are you from? - to a male'],
        ['ar' => 'مِن أَيْنَ أَنْتِ؟', 'en' => 'Where are you from? - to a female'],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُمْ.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: ما اسْمُكَ؟',
        'B: أَنا اسْمي أَحْمَد. ما اسْمُكَ؟',
        'A: أَنا اسْمي عُمَر. مِن أَيْنَ أَنْتَ؟',
        'B: أَنا مِن مِصْر. أَيْنَ تَعيشُ؟',
        'A: أَنا أَعيشُ في دُبَي.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: What is your name?',
        'B: My name is Ahmed. What is your name?',
        'A: My name is Omar. Where are you from?',
        'B: I am from Egypt. Where do you live?',
        'A: I live in Dubai.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does اِسْم mean?', 'options' => ['A' => 'city', 'B' => 'name', 'C' => 'country'], 'correct' => 'B'],
        ['id' => 'mcq_2', 'question' => 'What does أَنا mean?', 'options' => ['A' => 'I', 'B' => 'you', 'C' => 'from'], 'correct' => 'A'],
        ['id' => 'mcq_3', 'question' => 'أَنا مِن مِصْر means:', 'options' => ['A' => 'I live in Egypt.', 'B' => 'I am from Egypt.', 'C' => 'My name is Egypt.'], 'correct' => 'B'],
        ['id' => 'mcq_4', 'question' => 'ما اسْمُكَ؟ means:', 'options' => ['A' => 'Where do you live?', 'B' => 'What is your name?', 'C' => 'Where are you from?'], 'correct' => 'B'],
        ['id' => 'mcq_5', 'question' => 'أَنا أَعيشُ في دُبَي means:', 'options' => ['A' => 'I live in Dubai.', 'B' => 'I am from Dubai.', 'C' => 'My name is Dubai.'], 'correct' => 'A'],
    ],
    'number_recognition' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'أَنا اسْمي ________.'],
        ['id' => 'cs_2', 'prompt' => 'أَنا مِن ________.'],
        ['id' => 'cs_3', 'prompt' => 'أَنا أَعيشُ في ________.'],
        ['id' => 'cs_4', 'prompt' => 'أَنا ________.'],
    ],
    'arrange_words' => [
        ['id' => 'aw_1', 'words' => ['اسْمي', 'أَنا', 'أَحْمَد'], 'correct' => 'أَنا اسْمي أَحْمَد.'],
        ['id' => 'aw_2', 'words' => ['مِصْر', 'مِن', 'أَنا'], 'correct' => 'أَنا مِن مِصْر.'],
        ['id' => 'aw_3', 'words' => ['في', 'أَعيشُ', 'دُبَي', 'أَنا'], 'correct' => 'أَنا أَعيشُ في دُبَي.'],
    ],
    'writing_title' => 'Writing Task - Write About Yourself',
    'writing_instructions' => 'Write 4 Arabic sentences about yourself. Minimum 3 sentences required.',
    'writing_placeholder' => 'اكتب هنا 4 جمل عن نفسك...',
    'min_sentences' => 3,
    'speaking_title' => 'Speaking Task - Record Your Self-Introduction',
    'speaking_instructions' => 'Record yourself for 30 seconds. Include greeting, name, country, city, and two questions.',
    'self_check' => [
        'say_name' => 'I can say my name in Arabic.',
        'say_country' => 'I can say where I am from.',
        'say_city' => 'I can say where I live.',
        'ask_name' => 'I can ask someone their name.',
        'ask_country' => 'I can ask where someone is from.',
        'record_intro' => 'I can record a short Arabic introduction.',
    ],
];
