<?php
declare(strict_types=1);

return [
    'unit_type' => 'lesson',
    'lesson_number' => 11,
    'title_en' => 'Health & Body',
    'title_ar' => 'الصِّحَّة وَالجِسْم',
    'slug' => 'lesson-11-health-body',
    'goal_en' => 'By the end of this lesson, you can describe a simple health problem and ask for help in Arabic.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تصف مشكلة صحية بسيطة وتطلب المساعدة باللغة العربية.',
    'goal_checks' => [
        'Say basic body parts in Arabic.',
        'Say "I am tired" and "I am sick".',
        'Say "I have pain in...".',
        'Ask for help.',
        'Say you need a doctor or pharmacy.',
        'Use simple health phrases.',
        'Record a short health problem role-play.',
    ],
    'situation_en' => 'You are not feeling well in Dubai. You need to explain a simple health problem to a doctor, pharmacist, or friend in Arabic.',
    'situation_ar' => 'أنت لا تشعر أنك بخير في دبي. تحتاج أن تشرح مشكلة صحية بسيطة لطبيب أو صيدلي أو صديق باللغة العربية.',
    'safety_disclaimer_en' => 'This lesson is for language practice only. It is not medical advice. If you have a real health problem, contact a qualified doctor or emergency service.',
    'safety_disclaimer_ar' => 'هذا الدرس للتدريب اللغوي فقط، وليس نصيحة طبية. إذا كانت لديك مشكلة صحية حقيقية، تواصل مع طبيب مؤهل أو خدمة الطوارئ.',
    'warmup_title' => 'Quick Review from Lesson 10',
    'warmup_questions' => [
        'How do you say "I need help" in Arabic?',
        'How do you say "I have a meeting today" in Arabic?',
        'How do you say "I work in a company" in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'jism', 'arabic' => 'جِسْم', 'pronunciation' => 'jism', 'meaning' => 'body', 'category' => 'Body Part', 'example' => 'جِسْمي مُتْعَب.'],
        ['key' => 'ras', 'arabic' => 'رَأْس', 'pronunciation' => "ra's", 'meaning' => 'head', 'category' => 'Body Part', 'example' => 'عِنْدي أَلَم في الرَّأْس.'],
        ['key' => 'ayn', 'arabic' => 'عَيْن', 'pronunciation' => 'ayn', 'meaning' => 'eye', 'category' => 'Body Part', 'example' => 'عَيْني تُؤْلِمُني.'],
        ['key' => 'udhun', 'arabic' => 'أُذُن', 'pronunciation' => 'udhun', 'meaning' => 'ear', 'category' => 'Body Part', 'example' => 'عِنْدي أَلَم في الأُذُن.'],
        ['key' => 'anf', 'arabic' => 'أَنْف', 'pronunciation' => 'anf', 'meaning' => 'nose', 'category' => 'Body Part', 'example' => 'أَنْفي مُتْعَب.'],
        ['key' => 'fam', 'arabic' => 'فَم', 'pronunciation' => 'fam', 'meaning' => 'mouth', 'category' => 'Body Part', 'example' => 'فَمي جافّ.'],
        ['key' => 'asnaan', 'arabic' => 'أَسْنان', 'pronunciation' => 'asnaan', 'meaning' => 'teeth', 'category' => 'Body Part', 'example' => 'عِنْدي أَلَم في الأَسْنان.'],
        ['key' => 'halq', 'arabic' => 'حَلْق', 'pronunciation' => 'halq', 'meaning' => 'throat', 'category' => 'Body Part', 'example' => 'عِنْدي أَلَم في الحَلْق.'],
        ['key' => 'batn', 'arabic' => 'بَطْن', 'pronunciation' => 'batn', 'meaning' => 'stomach', 'category' => 'Body Part', 'example' => 'عِنْدي أَلَم في البَطْن.'],
        ['key' => 'zahr', 'arabic' => 'ظَهْر', 'pronunciation' => 'zahr', 'meaning' => 'back', 'category' => 'Body Part', 'example' => 'عِنْدي أَلَم في الظَّهْر.'],
        ['key' => 'yad', 'arabic' => 'يَد', 'pronunciation' => 'yad', 'meaning' => 'hand', 'category' => 'Body Part', 'example' => 'يَدي تُؤْلِمُني.'],
        ['key' => 'rijl', 'arabic' => 'رِجْل', 'pronunciation' => 'rijl', 'meaning' => 'leg / foot', 'category' => 'Body Part', 'example' => 'عِنْدي أَلَم في الرِّجْل.'],
        ['key' => 'qalb', 'arabic' => 'قَلْب', 'pronunciation' => 'qalb', 'meaning' => 'heart', 'category' => 'Body Part', 'example' => 'القَلْب مُهِمّ.'],
        ['key' => 'wajh', 'arabic' => 'وَجْه', 'pronunciation' => 'wajh', 'meaning' => 'face', 'category' => 'Body Part', 'example' => 'وَجْهي مُتْعَب.'],
        ['key' => 'sihhah', 'arabic' => 'صِحَّة', 'pronunciation' => 'sihhah', 'meaning' => 'health', 'category' => 'Health', 'example' => 'الصِّحَّة مُهِمَّة.'],
        ['key' => 'mareed', 'arabic' => 'مَريض', 'pronunciation' => 'mareed', 'meaning' => 'sick - male', 'category' => 'Health', 'example' => 'أَنا مَريض.'],
        ['key' => 'mareedah', 'arabic' => 'مَريضَة', 'pronunciation' => 'mareedah', 'meaning' => 'sick - female', 'category' => 'Health', 'example' => 'أَنا مَريضَة.'],
        ['key' => 'mutab', 'arabic' => 'مُتْعَب', 'pronunciation' => "mut'ab", 'meaning' => 'tired - male', 'category' => 'Health', 'example' => 'أَنا مُتْعَب.'],
        ['key' => 'mutabah', 'arabic' => 'مُتْعَبَة', 'pronunciation' => "mut'abah", 'meaning' => 'tired - female', 'category' => 'Health', 'example' => 'أَنا مُتْعَبَة.'],
        ['key' => 'alam', 'arabic' => 'أَلَم', 'pronunciation' => 'alam', 'meaning' => 'pain', 'category' => 'Health', 'example' => 'عِنْدي أَلَم.'],
        ['key' => 'sudaa', 'arabic' => 'صُداع', 'pronunciation' => "sudaa'", 'meaning' => 'headache', 'category' => 'Health', 'example' => 'عِنْدي صُداع.'],
        ['key' => 'hummaa', 'arabic' => 'حُمّى', 'pronunciation' => 'hummaa', 'meaning' => 'fever', 'category' => 'Health', 'example' => 'عِنْدي حُمّى.'],
        ['key' => 'suaal', 'arabic' => 'سُعال', 'pronunciation' => "su'aal", 'meaning' => 'cough', 'category' => 'Health', 'example' => 'عِنْدي سُعال.'],
        ['key' => 'dawkhah', 'arabic' => 'دَوْخَة', 'pronunciation' => 'dawkhah', 'meaning' => 'dizziness', 'category' => 'Health', 'example' => 'عِنْدي دَوْخَة.'],
        ['key' => 'tabeeb', 'arabic' => 'طَبيب', 'pronunciation' => 'tabeeb', 'meaning' => 'doctor - male', 'category' => 'Health Place/Person', 'example' => 'أَحتاجُ طَبيبًا.'],
        ['key' => 'tabeebah', 'arabic' => 'طَبيبَة', 'pronunciation' => 'tabeebah', 'meaning' => 'doctor - female', 'category' => 'Health Place/Person', 'example' => 'أَحتاجُ طَبيبَة.'],
        ['key' => 'saydaliyyah', 'arabic' => 'صَيْدَلِيَّة', 'pronunciation' => 'saydaliyyah', 'meaning' => 'pharmacy', 'category' => 'Health Place', 'example' => 'أَيْنَ الصَّيْدَلِيَّة؟'],
        ['key' => 'dawaa', 'arabic' => 'دَواء', 'pronunciation' => "dawaa'", 'meaning' => 'medicine', 'category' => 'Health', 'example' => 'أُريد دَواء.'],
        ['key' => 'musaadah', 'arabic' => 'مُساعَدَة', 'pronunciation' => "musaa'adah", 'meaning' => 'help', 'category' => 'Health Phrase', 'example' => 'أَحتاجُ مُساعَدَة.'],
        ['key' => 'al_aan', 'arabic' => 'الآن', 'pronunciation' => 'al-aan', 'meaning' => 'now', 'category' => 'Time/Health', 'example' => 'أَحتاجُ طَبيبًا الآن.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Health & Body Vocabulary', 'key' => 'B1-L11-Health-Body-Vocab', 'file' => '/assets/audio/books/beginner/lesson-11/B1-L11-Health-Body-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L11-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-11/B1-L11-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'أَنا مُتْعَب.', 'en' => 'I am tired - male'],
        ['ar' => 'أَنا مُتْعَبَة.', 'en' => 'I am tired - female'],
        ['ar' => 'أَنا مَريض.', 'en' => 'I am sick - male'],
        ['ar' => 'أَنا مَريضَة.', 'en' => 'I am sick - female'],
        ['ar' => 'عِنْدي أَلَم.', 'en' => 'I have pain.'],
        ['ar' => 'عِنْدي أَلَم في الرَّأْس.', 'en' => 'I have pain in the head.'],
        ['ar' => 'عِنْدي أَلَم في البَطْن.', 'en' => 'I have stomach pain.'],
        ['ar' => 'عِنْدي أَلَم في الظَّهْر.', 'en' => 'I have back pain.'],
        ['ar' => 'عِنْدي أَلَم في الأَسْنان.', 'en' => 'I have tooth pain.'],
        ['ar' => 'عِنْدي صُداع.', 'en' => 'I have a headache.'],
        ['ar' => 'عِنْدي حُمّى.', 'en' => 'I have a fever.'],
        ['ar' => 'عِنْدي سُعال.', 'en' => 'I have a cough.'],
        ['ar' => 'عِنْدي دَوْخَة.', 'en' => 'I feel dizzy / I have dizziness.'],
        ['ar' => 'أَحتاجُ طَبيبًا.', 'en' => 'I need a doctor.'],
        ['ar' => 'أَحتاجُ طَبيبَة.', 'en' => 'I need a female doctor.'],
        ['ar' => 'أَحتاجُ مُساعَدَة.', 'en' => 'I need help.'],
        ['ar' => 'أُريد دَواء.', 'en' => 'I want medicine.'],
        ['ar' => 'أَيْنَ الصَّيْدَلِيَّة؟', 'en' => 'Where is the pharmacy?'],
        ['ar' => 'الصَّيْدَلِيَّة قَريبَة.', 'en' => 'The pharmacy is near.'],
        ['ar' => 'هَلْ عِنْدَكُم دَواء؟', 'en' => 'Do you have medicine?'],
    ],
    'grammar_tip' => [
        'title' => 'Health survival phrases',
        'body' => 'Use عِنْدي أَلَم في + body part to say where you have pain. Use أَحتاجُ for "I need" and أُريد for "I want". This is language practice only, not medical advice.',
        'examples' => [
            ['ar' => 'عِنْدي أَلَم في الرَّأْس.', 'en' => 'I have pain in the head.'],
            ['ar' => 'عِنْدي أَلَم في البَطْن.', 'en' => 'I have stomach pain.'],
            ['ar' => 'أَحتاجُ طَبيبًا.', 'en' => 'I need a doctor.'],
            ['ar' => 'أَحتاجُ مُساعَدَة.', 'en' => 'I need help.'],
            ['ar' => 'أُريد دَواء.', 'en' => 'I want medicine.'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: أَنا مُتْعَب.',
        'B: ما المُشْكِلَة؟',
        'A: عِنْدي أَلَم في الرَّأْس وَعِنْدي صُداع.',
        'B: هَلْ تَحتاجُ طَبيبًا؟',
        'A: نَعَم، أَحتاجُ طَبيبًا.',
        'B: الصَّيْدَلِيَّة قَريبَة، وَالمُسْتَشْفى قَريب.',
        'A: أَيْنَ الصَّيْدَلِيَّة؟',
        'B: اِمْشِ إِلى الأَمام، ثُمَّ لُفّ يَمين.',
        'A: شُكْرًا.',
        'B: عَفْوًا.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: I am tired.',
        'B: What is the problem?',
        'A: I have pain in my head and I have a headache.',
        'B: Do you need a doctor?',
        'A: Yes, I need a doctor.',
        'B: The pharmacy is near, and the hospital is near.',
        'A: Where is the pharmacy?',
        'B: Go straight, then turn right.',
        'A: Thank you.',
        'B: You are welcome.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does رَأْس mean?', 'options' => ['A' => 'head', 'B' => 'stomach', 'C' => 'hand'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'What does بَطْن mean?', 'options' => ['A' => 'back', 'B' => 'stomach', 'C' => 'eye'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'عِنْدي أَلَم means:', 'options' => ['A' => 'I want water.', 'B' => 'I have pain.', 'C' => 'I am at home.'], 'correct' => 'B'],
        ['id' => 'mcq_4', 'question' => 'أَنا مُتْعَب means:', 'options' => ['A' => 'I am tired.', 'B' => 'I am a doctor.', 'C' => 'I need medicine.'], 'correct' => 'A'],
        ['id' => 'mcq_5', 'question' => 'أَحتاجُ طَبيبًا means:', 'options' => ['A' => 'I need a doctor.', 'B' => 'I have a cough.', 'C' => 'I want coffee.'], 'correct' => 'A'],
    ],
    'body_matching' => [
        ['id' => 'match_ras', 'arabic' => 'رَأْس', 'correct' => 'head'],
        ['id' => 'match_ayn', 'arabic' => 'عَيْن', 'correct' => 'eye'],
        ['id' => 'match_udhun', 'arabic' => 'أُذُن', 'correct' => 'ear'],
        ['id' => 'match_asnaan', 'arabic' => 'أَسْنان', 'correct' => 'teeth'],
        ['id' => 'match_halq', 'arabic' => 'حَلْق', 'correct' => 'throat'],
        ['id' => 'match_batn', 'arabic' => 'بَطْن', 'correct' => 'stomach'],
        ['id' => 'match_zahr', 'arabic' => 'ظَهْر', 'correct' => 'back'],
        ['id' => 'match_yad', 'arabic' => 'يَد', 'correct' => 'hand'],
        ['id' => 'match_rijl', 'arabic' => 'رِجْل', 'correct' => 'leg / foot'],
        ['id' => 'match_wajh', 'arabic' => 'وَجْه', 'correct' => 'face'],
    ],
    'body_matching_options' => ['head', 'eye', 'ear', 'teeth', 'throat', 'stomach', 'back', 'hand', 'leg / foot', 'face'],
    'health_phrase_matching' => [
        ['id' => 'match_mareed', 'arabic' => 'أَنا مَريض', 'correct' => 'I am sick'],
        ['id' => 'match_mutab', 'arabic' => 'أَنا مُتْعَب', 'correct' => 'I am tired'],
        ['id' => 'match_alam', 'arabic' => 'عِنْدي أَلَم', 'correct' => 'I have pain'],
        ['id' => 'match_sudaa', 'arabic' => 'عِنْدي صُداع', 'correct' => 'I have a headache'],
        ['id' => 'match_hummaa', 'arabic' => 'عِنْدي حُمّى', 'correct' => 'I have a fever'],
        ['id' => 'match_suaal', 'arabic' => 'عِنْدي سُعال', 'correct' => 'I have a cough'],
        ['id' => 'match_musaadah', 'arabic' => 'أَحتاجُ مُساعَدَة', 'correct' => 'I need help'],
        ['id' => 'match_dawaa', 'arabic' => 'أُريد دَواء', 'correct' => 'I want medicine'],
        ['id' => 'match_tabeeb', 'arabic' => 'أَحتاجُ طَبيبًا', 'correct' => 'I need a doctor'],
        ['id' => 'match_saydaliyyah', 'arabic' => 'أَيْنَ الصَّيْدَلِيَّة؟', 'correct' => 'Where is the pharmacy?'],
    ],
    'health_phrase_matching_options' => ['I am sick', 'I am tired', 'I have pain', 'I have a headache', 'I have a fever', 'I have a cough', 'I need help', 'I want medicine', 'I need a doctor', 'Where is the pharmacy?'],
    'pain_sentence_practice' => [
        ['id' => 'ps_1', 'question' => 'عِنْدي أَلَم في الرَّأْس.', 'options' => ['A' => 'I have pain in the head.', 'B' => 'I have pain in the stomach.', 'C' => 'I have pain in the back.'], 'correct' => 'A'],
        ['id' => 'ps_2', 'question' => 'عِنْدي أَلَم في البَطْن.', 'options' => ['A' => 'I have back pain.', 'B' => 'I have stomach pain.', 'C' => 'I have tooth pain.'], 'correct' => 'B'],
        ['id' => 'ps_3', 'question' => 'عِنْدي أَلَم في الأَسْنان.', 'options' => ['A' => 'I have tooth pain.', 'B' => 'I have a fever.', 'C' => 'I have a cough.'], 'correct' => 'A'],
        ['id' => 'ps_4', 'question' => 'عِنْدي سُعال.', 'options' => ['A' => 'I have a cough.', 'B' => 'I have dizziness.', 'C' => 'I need medicine.'], 'correct' => 'A'],
        ['id' => 'ps_5', 'question' => 'هَلْ عِنْدَكُم دَواء؟', 'options' => ['A' => 'Do you have medicine?', 'B' => 'Do you have water?', 'C' => 'Where is the hospital?'], 'correct' => 'A'],
        ['id' => 'ps_6', 'question' => 'أَحتاجُ طَبيبًا الآن.', 'options' => ['A' => 'I need a doctor now.', 'B' => 'I am a doctor now.', 'C' => 'I want the pharmacy now.'], 'correct' => 'A'],
    ],
    'matching' => [],
    'matching_options' => [],
    'number_recognition' => [],
    'price_recognition' => [],
    'color_recognition' => [],
    'time_recognition' => [],
    'daily_action_matching' => [],
    'direction_matching' => [],
    'direction_recognition' => [],
    'job_matching' => [],
    'workplace_matching' => [],
    'work_sentence_practice' => [],
    'sequence_practice' => [],
    'description_matching' => [],
    'category_practice' => [],
    'listening_review' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'عِنْدي أَلَم في ________.'],
        ['id' => 'cs_2', 'prompt' => 'أَنا ________.'],
        ['id' => 'cs_3', 'prompt' => 'أَحتاجُ ________.'],
        ['id' => 'cs_4', 'prompt' => 'أُريد ________.'],
        ['id' => 'cs_5', 'prompt' => 'أَيْنَ ________؟'],
        ['id' => 'cs_6', 'prompt' => 'عِنْدي ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write a Simple Health Problem',
    'writing_instructions' => 'Write 5-6 Arabic sentences about a simple practice/fake health problem. Do not share private medical details. Use: السَّلامُ عَلَيْكُم، أَنا مُتْعَب / مُتْعَبَة، عِنْدي أَلَم في، أَحتاجُ، شُكْرًا.',
    'writing_placeholder' => 'اكتب هنا 5 أو 6 جمل عن مشكلة صحية بسيطة...',
    'min_sentences' => 5,
    'speaking_title' => 'Speaking Task - Describe a Health Problem',
    'speaking_instructions' => 'Record yourself for about 60 seconds. Say you are tired or sick, say where you have pain, mention one health problem, ask for help or a doctor, ask where the pharmacy is, and say thank you. Direct browser recording only.',
    'self_check_min' => 4,
    'self_check' => [
        'body_parts' => 'I can say basic body parts in Arabic.',
        'tired_sick' => 'I can say "I am tired" or "I am sick" in Arabic.',
        'pain_in' => 'I can say "I have pain in..." in Arabic.',
        'headache_fever_cough' => 'I can say headache, fever, and cough in Arabic.',
        'ask_help' => 'I can ask for help in Arabic.',
        'ask_pharmacy' => 'I can ask where the pharmacy is.',
        'record_health_roleplay' => 'I can record a short health problem role-play.',
    ],
];
