<?php
declare(strict_types=1);

return [
    'unit_type' => 'lesson',
    'lesson_number' => 12,
    'title_en' => 'Full Daily Conversation',
    'title_ar' => 'مُحادَثَة يَوْمِيَّة كامِلَة',
    'slug' => 'lesson-12-full-daily-conversation',
    'goal_en' => 'By the end of this lesson, you can have a simple daily conversation in Arabic using everything you learned in this book.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تجري محادثة يومية بسيطة باللغة العربية باستخدام كل ما تعلمته في هذا الكتاب.',
    'goal_checks' => [
        'Introduce yourself.',
        'Say age, country, city, and phone number.',
        'Talk about family.',
        'Order food or drink.',
        'Ask about prices.',
        'Describe objects with colors.',
        'Talk about home and places.',
        'Ask for directions.',
        'Talk about daily routine and work.',
        'Describe a simple health problem.',
        'Record a longer daily conversation.',
    ],
    'situation_en' => 'You meet a new Arabic-speaking person in Dubai. You have a friendly conversation about yourself, your family, work, daily routine, nearby places, and simple daily needs.',
    'situation_ar' => 'تقابل شخصًا جديدًا يتكلم العربية في دبي. تجري معه محادثة ودية عن نفسك، وأسرتك، وعملك، وروتينك اليومي، والأماكن القريبة، واحتياجات يومية بسيطة.',
    'safety_disclaimer_en' => 'For practice, you can use fake personal information. Do not share private phone numbers, addresses, or medical details. This lesson is for language practice only.',
    'safety_disclaimer_ar' => 'للتدريب، يمكنك استخدام معلومات شخصية غير حقيقية. لا تشارك أرقام هواتف أو عناوين أو تفاصيل طبية خاصة. هذا الدرس للتدريب اللغوي فقط.',
    'warmup_title' => 'Quick Review from Lessons 1-11',
    'warmup_questions' => [
        'How do you say "My name is Ahmed" in Arabic?',
        'How do you say "I live in Dubai" in Arabic?',
        'How do you say "I want water" in Arabic?',
        'How do you ask "How much is this?" in Arabic?',
        'How do you ask "Where is the pharmacy?" in Arabic?',
        'How do you say "I need help" in Arabic?',
    ],
    'review_overview' => [
        ['title' => 'Introduce Yourself', 'items' => ['أَنا اسْمي...', 'أَنا مِن...', 'أَنا أَعيشُ في...']],
        ['title' => 'Personal Information', 'items' => ['عُمْري...', 'رَقْمُ هاتِفي...']],
        ['title' => 'Family', 'items' => ['عِنْدي...', 'لَيْسَ عِنْدي...', 'عائِلَتي...']],
        ['title' => 'Food / Shopping', 'items' => ['أُريد...', 'هذا بِكَم؟', 'هذا رَخيص.']],
        ['title' => 'Places / Directions', 'items' => ['أَيْنَ...؟', 'اِمْشِ إِلى الأَمام.', 'لُفّ يَمين / يَسار.']],
        ['title' => 'Routine / Work / Health', 'items' => ['أَصْحو في السّاعَة...', 'أَنا أَعْمَلُ في...', 'أَحتاجُ مُساعَدَة.']],
    ],
    'conversation_chunks' => [
        ['title' => 'Greeting and Introduction', 'arabic' => ['السَّلامُ عَلَيْكُم.', 'أَنا اسْمي ________.', 'أَنا مِن ________.', 'أَنا أَعيشُ في ________.']],
        ['title' => 'Personal Information', 'arabic' => ['عُمْري ________ سَنَة.', 'رَقْمُ هاتِفي ________.'], 'note' => 'Use a fake phone number for practice.'],
        ['title' => 'Family', 'arabic' => ['عائِلَتي ________.', 'عِنْدي ________.', 'لَيْسَ عِنْدي ________.']],
        ['title' => 'Food / Shopping', 'arabic' => ['أُريد ________، مِن فَضْلِكَ.', 'هذا بِكَم؟', 'السِّعْر ________ دَراهِم.']],
        ['title' => 'Place / Direction', 'arabic' => ['أَيْنَ ________؟', 'اِمْشِ إِلى الأَمام.', 'ثُمَّ لُفّ يَمين / يَسار.']],
        ['title' => 'Routine / Work', 'arabic' => ['أَصْحو في السّاعَة ________.', 'أَنا أَعْمَلُ في ________.', 'أَدْرُسُ العَرَبِيَّة في المَساء.']],
        ['title' => 'Health / Help', 'arabic' => ['أَنا مُتْعَب.', 'عِنْدي أَلَم في ________.', 'أَحتاجُ مُساعَدَة.']],
    ],
    'vocabulary' => [
        ['key' => 'ana', 'arabic' => 'أَنا', 'pronunciation' => 'ana', 'meaning' => 'I / me', 'category' => 'Lesson 1', 'example' => 'أَنا اسْمي أَحْمَد.'],
        ['key' => 'ism', 'arabic' => 'اِسْم', 'pronunciation' => 'ism', 'meaning' => 'name', 'category' => 'Lesson 1', 'example' => 'ما اسْمُكَ؟'],
        ['key' => 'min', 'arabic' => 'مِن', 'pronunciation' => 'min', 'meaning' => 'from', 'category' => 'Lesson 1', 'example' => 'أَنا مِن مِصْر.'],
        ['key' => 'aeeshu', 'arabic' => 'أَعيشُ', 'pronunciation' => "a'eeshu", 'meaning' => 'I live', 'category' => 'Lesson 1', 'example' => 'أَنا أَعيشُ في دُبَي.'],
        ['key' => 'umr', 'arabic' => 'عُمْر', 'pronunciation' => 'umr', 'meaning' => 'age', 'category' => 'Lesson 2', 'example' => 'عُمْري عِشْرون سَنَة.'],
        ['key' => 'raqm', 'arabic' => 'رَقْم', 'pronunciation' => 'raqm', 'meaning' => 'number', 'category' => 'Lesson 2', 'example' => 'رَقْمُ هاتِفي...'],
        ['key' => 'aa_ilah', 'arabic' => 'عائِلَة', 'pronunciation' => "aa'ilah", 'meaning' => 'family', 'category' => 'Lesson 3', 'example' => 'عائِلَتي صَغيرَة.'],
        ['key' => 'indi', 'arabic' => 'عِنْدي', 'pronunciation' => 'indi', 'meaning' => 'I have', 'category' => 'Lesson 3', 'example' => 'عِنْدي أَخ.'],
        ['key' => 'ureed', 'arabic' => 'أُريد', 'pronunciation' => 'ureed', 'meaning' => 'I want', 'category' => 'Lesson 4', 'example' => 'أُريد ماءً.'],
        ['key' => 'bikam', 'arabic' => 'بِكَم؟', 'pronunciation' => 'bikam?', 'meaning' => 'how much?', 'category' => 'Lesson 5', 'example' => 'هذا بِكَم؟'],
        ['key' => 'haadha', 'arabic' => 'هذا', 'pronunciation' => 'haadha', 'meaning' => 'this - masculine', 'category' => 'Lesson 6', 'example' => 'هذا قَلَم.'],
        ['key' => 'haadhihi', 'arabic' => 'هذه', 'pronunciation' => 'haadhihi', 'meaning' => 'this - feminine', 'category' => 'Lesson 6', 'example' => 'هذه حَقيبَة.'],
        ['key' => 'bayt', 'arabic' => 'بَيْت', 'pronunciation' => 'bayt', 'meaning' => 'house / home', 'category' => 'Lesson 7', 'example' => 'أَنا في البَيْت.'],
        ['key' => 'ayna', 'arabic' => 'أَيْنَ؟', 'pronunciation' => 'ayna?', 'meaning' => 'where?', 'category' => 'Lesson 7 / 9', 'example' => 'أَيْنَ المَطْعَم؟'],
        ['key' => 'as_saaah', 'arabic' => 'السّاعَة', 'pronunciation' => "as-saa'ah", 'meaning' => 'the time / o’clock', 'category' => 'Lesson 8', 'example' => 'السّاعَة سَبْعَة.'],
        ['key' => 'yameen', 'arabic' => 'يَمين', 'pronunciation' => 'yameen', 'meaning' => 'right', 'category' => 'Lesson 9', 'example' => 'لُفّ يَمين.'],
        ['key' => 'yasaar', 'arabic' => 'يَسار', 'pronunciation' => 'yasaar', 'meaning' => 'left', 'category' => 'Lesson 9', 'example' => 'لُفّ يَسار.'],
        ['key' => 'amal', 'arabic' => 'عَمَل', 'pronunciation' => 'amal', 'meaning' => 'work', 'category' => 'Lesson 10', 'example' => 'أَذْهَبُ إِلى العَمَل.'],
        ['key' => 'ahtaaju', 'arabic' => 'أَحتاجُ', 'pronunciation' => 'ahtaaju', 'meaning' => 'I need', 'category' => 'Lesson 10 / 11', 'example' => 'أَحتاجُ مُساعَدَة.'],
        ['key' => 'alam', 'arabic' => 'أَلَم', 'pronunciation' => 'alam', 'meaning' => 'pain', 'category' => 'Lesson 11', 'example' => 'عِنْدي أَلَم في الرَّأْس.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Core Conversation Vocabulary', 'key' => 'B1-L12-Core-Vocab', 'file' => '/assets/audio/books/beginner/lesson-12/B1-L12-Core-Vocab.mp3'],
        ['title' => 'Audio Practice - Full Daily Conversation', 'key' => 'B1-L12-Full-Conversation', 'file' => '/assets/audio/books/beginner/lesson-12/B1-L12-Full-Conversation.mp3'],
    ],
    'sentences' => [
        ['ar' => 'أَنا اسْمي أَحْمَد.', 'en' => 'My name is Ahmed.'],
        ['ar' => 'أَنا مِن مِصْر.', 'en' => 'I am from Egypt.'],
        ['ar' => 'أَنا أَعيشُ في دُبَي.', 'en' => 'I live in Dubai.'],
        ['ar' => 'عُمْري عِشْرون سَنَة.', 'en' => 'I am twenty years old.'],
        ['ar' => 'رَقْمُ هاتِفي واحِد، اِثْنان، ثَلاثَة.', 'en' => 'My phone number is one, two, three.'],
        ['ar' => 'عائِلَتي صَغيرَة.', 'en' => 'My family is small.'],
        ['ar' => 'عِنْدي أَب وَأُم.', 'en' => 'I have a father and mother.'],
        ['ar' => 'أُريد ماءً، مِن فَضْلِكَ.', 'en' => 'I want water, please.'],
        ['ar' => 'هذا بِكَم؟', 'en' => 'How much is this?'],
        ['ar' => 'هذا قَلَم أَحْمَر.', 'en' => 'This is a red pen.'],
        ['ar' => 'أَيْنَ الصَّيْدَلِيَّة؟', 'en' => 'Where is the pharmacy?'],
        ['ar' => 'اِمْشِ إِلى الأَمام، ثُمَّ لُفّ يَمين.', 'en' => 'Go straight, then turn right.'],
        ['ar' => 'أَصْحو في السّاعَة سَبْعَة.', 'en' => 'I wake up at seven o’clock.'],
        ['ar' => 'أَنا أَعْمَلُ في شَرِكَة.', 'en' => 'I work in a company.'],
        ['ar' => 'عِنْدي أَلَم في الرَّأْس.', 'en' => 'I have head pain.'],
        ['ar' => 'أَحتاجُ مُساعَدَة.', 'en' => 'I need help.'],
    ],
    'grammar_tip' => [
        'title' => 'Useful patterns review',
        'body' => 'This lesson combines the main patterns from the book: أَنا اسْمي, أَنا مِن, عِنْدي, أُريد, هذا بِكَم, أَيْنَ, أَصْحو في السّاعَة, أَعْمَلُ في, and أَحتاجُ. Keep sentences short and clear.',
        'examples' => [
            ['ar' => 'أَنا اسْمي أَحْمَد.', 'en' => 'My name is Ahmed.'],
            ['ar' => 'عِنْدي أَب وَأُم.', 'en' => 'I have a father and mother.'],
            ['ar' => 'أُريد ماءً.', 'en' => 'I want water.'],
            ['ar' => 'أَيْنَ الصَّيْدَلِيَّة؟', 'en' => 'Where is the pharmacy?'],
            ['ar' => 'أَحتاجُ مُساعَدَة.', 'en' => 'I need help.'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: ما اسْمُكَ؟',
        'B: أَنا اسْمي أَحْمَد. ما اسْمُكَ؟',
        'A: أَنا اسْمي عُمَر. مِن أَيْنَ أَنْتَ؟',
        'B: أَنا مِن مِصْر، وَأَنا أَعيشُ في دُبَي.',
        'A: كَمْ عُمْرُكَ؟',
        'B: عُمْري عِشْرون سَنَة.',
        'A: هَلْ عِنْدَكَ أُسْرَة في دُبَي؟',
        'B: لا، عائِلَتي في مِصْر. عِنْدي أَب وَأُم وَأَخ.',
        'A: ماذا تُريد الآن؟',
        'B: أُريد ماءً وَقَهْوَة، مِن فَضْلِكَ.',
        'A: هذا القَلَم بِكَم؟',
        'B: السِّعْر عَشَرَة دَراهِم.',
        'A: جَميل. أَيْنَ الصَّيْدَلِيَّة؟',
        'B: اِمْشِ إِلى الأَمام، ثُمَّ لُفّ يَمين. الصَّيْدَلِيَّة عَلى اليَمين.',
        'A: ماذا تَفْعَلُ كُلَّ يَوْم؟',
        'B: أَصْحو في السّاعَة سَبْعَة. أَذْهَبُ إِلى العَمَل، ثُمَّ أَدْرُسُ العَرَبِيَّة في المَساء.',
        'A: ما عَمَلُكَ؟',
        'B: أَنا أَعْمَلُ في شَرِكَة في دُبَي.',
        'A: هَلْ أَنْتَ بِخَيْر؟',
        'B: أَنا مُتْعَب قَليلًا. عِنْدي أَلَم في الرَّأْس.',
        'A: هَلْ تَحتاجُ مُساعَدَة؟',
        'B: نَعَم، أَحتاجُ مُساعَدَة. شُكْرًا.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: What is your name?',
        'B: My name is Ahmed. What is your name?',
        'A: My name is Omar. Where are you from?',
        'B: I am from Egypt, and I live in Dubai.',
        'A: How old are you?',
        'B: I am twenty years old.',
        'A: Do you have family in Dubai?',
        'B: No, my family is in Egypt. I have a father, mother, and brother.',
        'A: What do you want now?',
        'B: I want water and coffee, please.',
        'A: How much is this pen?',
        'B: The price is ten dirhams.',
        'A: Nice. Where is the pharmacy?',
        'B: Go straight, then turn right. The pharmacy is on the right.',
        'A: What do you do every day?',
        'B: I wake up at seven. I go to work, then I study Arabic in the evening.',
        'A: What is your work?',
        'B: I work in a company in Dubai.',
        'A: Are you okay?',
        'B: I am a little tired. I have pain in my head.',
        'A: Do you need help?',
        'B: Yes, I need help. Thank you.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'أَنا اسْمي means:', 'options' => ['A' => 'My name is', 'B' => 'My age is', 'C' => 'My work is'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'عِنْدي أَخ means:', 'options' => ['A' => 'I have a brother.', 'B' => 'I need a brother.', 'C' => 'I want a brother.'], 'correct' => 'A'],
        ['id' => 'mcq_3', 'question' => 'أُريد ماءً means:', 'options' => ['A' => 'I need help.', 'B' => 'I want water.', 'C' => 'I have water.'], 'correct' => 'B'],
        ['id' => 'mcq_4', 'question' => 'هذا بِكَم؟ means:', 'options' => ['A' => 'How much is this?', 'B' => 'What color is this?', 'C' => 'Where is this?'], 'correct' => 'A'],
        ['id' => 'mcq_5', 'question' => 'هذه حَقيبَة زَرْقاء means:', 'options' => ['A' => 'This is a red pen.', 'B' => 'This is a blue bag.', 'C' => 'This is a black phone.'], 'correct' => 'B'],
        ['id' => 'mcq_6', 'question' => 'أَيْنَ الصَّيْدَلِيَّة؟ means:', 'options' => ['A' => 'Where is the pharmacy?', 'B' => 'How much is the pharmacy?', 'C' => 'I need the pharmacy.'], 'correct' => 'A'],
        ['id' => 'mcq_7', 'question' => 'أَصْحو في السّاعَة سَبْعَة means:', 'options' => ['A' => 'I sleep at seven.', 'B' => 'I wake up at seven.', 'C' => 'I work at seven.'], 'correct' => 'B'],
        ['id' => 'mcq_8', 'question' => 'أَنا أَعْمَلُ في شَرِكَة means:', 'options' => ['A' => 'I work in a company.', 'B' => 'I live in a company.', 'C' => 'I want a company.'], 'correct' => 'A'],
        ['id' => 'mcq_9', 'question' => 'عِنْدي أَلَم في الرَّأْس means:', 'options' => ['A' => 'I have pain in my head.', 'B' => 'I need a doctor.', 'C' => 'I am at home.'], 'correct' => 'A'],
        ['id' => 'mcq_10', 'question' => 'أَحتاجُ مُساعَدَة means:', 'options' => ['A' => 'I have a task.', 'B' => 'I need help.', 'C' => 'I want food.'], 'correct' => 'B'],
    ],
    'conversation_phrase_matching' => [
        ['id' => 'match_name', 'arabic' => 'ما اسْمُكَ؟', 'correct' => 'What is your name?'],
        ['id' => 'match_country', 'arabic' => 'أَنا مِن مِصْر', 'correct' => 'I am from Egypt'],
        ['id' => 'match_age', 'arabic' => 'عُمْري عِشْرون سَنَة', 'correct' => 'I am twenty years old'],
        ['id' => 'match_family', 'arabic' => 'عائِلَتي صَغيرَة', 'correct' => 'My family is small'],
        ['id' => 'match_water', 'arabic' => 'أُريد ماءً', 'correct' => 'I want water'],
        ['id' => 'match_cheap', 'arabic' => 'هذا رَخيص', 'correct' => 'This is cheap'],
        ['id' => 'match_home', 'arabic' => 'بَيْتي قَريب مِن المَوْل', 'correct' => 'My home is near the mall'],
        ['id' => 'match_right', 'arabic' => 'لُفّ يَمين', 'correct' => 'Turn right'],
        ['id' => 'match_work', 'arabic' => 'أَذْهَبُ إِلى العَمَل', 'correct' => 'I go to work'],
        ['id' => 'match_doctor', 'arabic' => 'أَحتاجُ طَبيبًا', 'correct' => 'I need a doctor'],
    ],
    'conversation_phrase_matching_options' => ['What is your name?', 'I am from Egypt', 'I am twenty years old', 'My family is small', 'I want water', 'This is cheap', 'My home is near the mall', 'Turn right', 'I go to work', 'I need a doctor'],
    'topic_recognition' => [
        ['id' => 'topic_1', 'question' => 'أَنا اسْمي أَحْمَد.', 'options' => ['Introduction' => 'Introduction', 'Family' => 'Family', 'Food/Shopping' => 'Food/Shopping', 'Places/Directions' => 'Places/Directions', 'Routine/Work' => 'Routine/Work', 'Health' => 'Health'], 'correct' => 'Introduction'],
        ['id' => 'topic_2', 'question' => 'عِنْدي أَب وَأُم.', 'options' => ['Introduction' => 'Introduction', 'Family' => 'Family', 'Food/Shopping' => 'Food/Shopping', 'Places/Directions' => 'Places/Directions', 'Routine/Work' => 'Routine/Work', 'Health' => 'Health'], 'correct' => 'Family'],
        ['id' => 'topic_3', 'question' => 'أُريد قَهْوَة.', 'options' => ['Introduction' => 'Introduction', 'Family' => 'Family', 'Food/Shopping' => 'Food/Shopping', 'Places/Directions' => 'Places/Directions', 'Routine/Work' => 'Routine/Work', 'Health' => 'Health'], 'correct' => 'Food/Shopping'],
        ['id' => 'topic_4', 'question' => 'أَيْنَ المَطْعَم؟', 'options' => ['Introduction' => 'Introduction', 'Family' => 'Family', 'Food/Shopping' => 'Food/Shopping', 'Places/Directions' => 'Places/Directions', 'Routine/Work' => 'Routine/Work', 'Health' => 'Health'], 'correct' => 'Places/Directions'],
        ['id' => 'topic_5', 'question' => 'أَصْحو في السّاعَة سَبْعَة.', 'options' => ['Introduction' => 'Introduction', 'Family' => 'Family', 'Food/Shopping' => 'Food/Shopping', 'Places/Directions' => 'Places/Directions', 'Routine/Work' => 'Routine/Work', 'Health' => 'Health'], 'correct' => 'Routine/Work'],
        ['id' => 'topic_6', 'question' => 'أَحتاجُ طَبيبًا.', 'options' => ['Introduction' => 'Introduction', 'Family' => 'Family', 'Food/Shopping' => 'Food/Shopping', 'Places/Directions' => 'Places/Directions', 'Routine/Work' => 'Routine/Work', 'Health' => 'Health'], 'correct' => 'Health'],
        ['id' => 'topic_7', 'question' => 'هذا بِكَم؟', 'options' => ['Introduction' => 'Introduction', 'Family' => 'Family', 'Food/Shopping' => 'Food/Shopping', 'Places/Directions' => 'Places/Directions', 'Routine/Work' => 'Routine/Work', 'Health' => 'Health'], 'correct' => 'Food/Shopping'],
        ['id' => 'topic_8', 'question' => 'لُفّ يَسار.', 'options' => ['Introduction' => 'Introduction', 'Family' => 'Family', 'Food/Shopping' => 'Food/Shopping', 'Places/Directions' => 'Places/Directions', 'Routine/Work' => 'Routine/Work', 'Health' => 'Health'], 'correct' => 'Places/Directions'],
    ],
    'complete_conversation' => [
        ['id' => 'cc_1', 'prompt' => 'B: أَنا اسْمي ________.'],
        ['id' => 'cc_2', 'prompt' => 'B: أَنا مِن ________.'],
        ['id' => 'cc_3', 'prompt' => 'B: أَنا أَعيشُ في ________.'],
        ['id' => 'cc_4', 'prompt' => 'B: أُريد ________.'],
        ['id' => 'cc_5', 'prompt' => 'B: السِّعْر ________ دَراهِم.'],
        ['id' => 'cc_6', 'prompt' => 'B: اِمْشِ إِلى الأَمام، ثُمَّ لُفّ ________.'],
        ['id' => 'cc_7', 'prompt' => 'B: أَنا مُتْعَب. عِنْدي أَلَم في ________.'],
    ],
    'matching' => [],
    'matching_options' => [],
    'number_recognition' => [],
    'price_recognition' => [],
    'color_recognition' => [],
    'time_recognition' => [],
    'daily_action_matching' => [],
    'direction_matching' => [],
    'direction_recognition' => [],
    'job_matching' => [],
    'workplace_matching' => [],
    'work_sentence_practice' => [],
    'body_matching' => [],
    'health_phrase_matching' => [],
    'pain_sentence_practice' => [],
    'sequence_practice' => [],
    'description_matching' => [],
    'category_practice' => [],
    'listening_review' => [],
    'listening_numbers' => [],
    'complete_sentence' => [],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write a Full Daily Conversation',
    'writing_instructions' => 'Write a simple daily conversation in Arabic using at least 10 lines or sentences. Include greeting, name, country/city, age, family, food/drink, price, directions, routine/work, health/help, and thank you. You can use fake personal information for practice.',
    'writing_placeholder' => 'اكتب هنا محادثة يومية كاملة باللغة العربية...',
    'min_sentences' => 10,
    'speaking_title' => 'Speaking Task - Record a Full Daily Conversation',
    'speaking_instructions' => 'Record yourself for 90-150 seconds. Include greeting, introduction, country/city, age, family, food/drink, price, directions, routine/work, health/help, and thank you. Direct browser recording only.',
    'self_check_min' => 6,
    'self_check' => [
        'introduce_self' => 'I can introduce myself in Arabic.',
        'talk_family' => 'I can talk about family in Arabic.',
        'ask_food_drink' => 'I can ask for food or drink in Arabic.',
        'ask_prices' => 'I can ask about prices in Arabic.',
        'ask_place_directions' => 'I can ask where a place is and understand directions.',
        'daily_routine_sentence' => 'I can say a simple daily routine sentence.',
        'work_sentence' => 'I can say a simple work sentence.',
        'health_problem' => 'I can describe a simple health problem.',
        'combine_topics' => 'I can combine different topics in one Arabic conversation.',
        'ready_final_review' => 'I am ready for the Final Review.',
    ],
];
