<?php
declare(strict_types=1);

return [
    'unit_type' => 'lesson',
    'lesson_number' => 9,
    'title_en' => 'Directions',
    'title_ar' => 'الاتِّجاهات',
    'slug' => 'lesson-9-directions',
    'goal_en' => 'By the end of this lesson, you can ask for directions and understand simple direction phrases in Arabic.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تسأل عن الاتجاهات وتفهم عبارات اتجاه بسيطة باللغة العربية.',
    'goal_checks' => [
        'Say right and left in Arabic.',
        'Say straight / in front / behind.',
        'Ask where a place is.',
        'Say "go straight".',
        'Say "turn right / turn left".',
        'Use near and far.',
        'Record a short directions role-play.',
    ],
    'situation_en' => 'You are in a mall or street in Dubai. You need to ask where the restaurant, pharmacy, or bathroom is, and understand simple directions.',
    'situation_ar' => 'أنت في مول أو شارع في دبي. تحتاج أن تسأل شخصًا أين المطعم أو الصيدلية أو الحمام، وتفهم اتجاهات بسيطة.',
    'warmup_title' => 'Quick Review from Review 2',
    'warmup_questions' => [
        'How do you say "Where is the pharmacy?" in Arabic?',
        'How do you say "The restaurant is near" in Arabic?',
        'How do you say "I am in the mall" in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'yameen', 'arabic' => 'يَمين', 'pronunciation' => 'yameen', 'meaning' => 'right', 'category' => 'Direction', 'example' => 'اِذْهَب يَمين.'],
        ['key' => 'yasaar', 'arabic' => 'يَسار', 'pronunciation' => 'yasaar', 'meaning' => 'left', 'category' => 'Direction', 'example' => 'اِذْهَب يَسار.'],
        ['key' => 'ila_al_amaam', 'arabic' => 'إِلى الأَمام', 'pronunciation' => 'ila al-amaam', 'meaning' => 'forward / straight ahead', 'category' => 'Direction', 'example' => 'اِمْشِ إِلى الأَمام.'],
        ['key' => 'khalf', 'arabic' => 'خَلْف', 'pronunciation' => 'khalf', 'meaning' => 'behind', 'category' => 'Direction', 'example' => 'المَطْعَم خَلْف المَوْل.'],
        ['key' => 'amaam', 'arabic' => 'أَمام', 'pronunciation' => 'amaam', 'meaning' => 'in front of', 'category' => 'Direction', 'example' => 'الصَّيْدَلِيَّة أَمام المَسْجِد.'],
        ['key' => 'qareeb', 'arabic' => 'قَريب', 'pronunciation' => 'qareeb', 'meaning' => 'near', 'category' => 'Direction', 'example' => 'المَطْعَم قَريب.'],
        ['key' => 'qareebah', 'arabic' => 'قَريبَة', 'pronunciation' => 'qareebah', 'meaning' => 'near - feminine', 'category' => 'Direction', 'example' => 'الصَّيْدَلِيَّة قَريبَة.'],
        ['key' => 'baeed', 'arabic' => 'بَعيد', 'pronunciation' => "ba'eed", 'meaning' => 'far', 'category' => 'Direction', 'example' => 'المُسْتَشْفى بَعيد.'],
        ['key' => 'baeedah', 'arabic' => 'بَعيدَة', 'pronunciation' => "ba'eedah", 'meaning' => 'far - feminine', 'category' => 'Direction', 'example' => 'المَدْرَسَة بَعيدَة.'],
        ['key' => 'huna', 'arabic' => 'هُنا', 'pronunciation' => 'huna', 'meaning' => 'here', 'category' => 'Direction', 'example' => 'الحَمّام هُنا.'],
        ['key' => 'hunaak', 'arabic' => 'هُناك', 'pronunciation' => 'hunaak', 'meaning' => 'there / there is', 'category' => 'Direction', 'example' => 'هُناك مَطْعَم قَريب.'],
        ['key' => 'baad', 'arabic' => 'بَعْد', 'pronunciation' => "ba'd", 'meaning' => 'after', 'category' => 'Direction', 'example' => 'المَطْعَم بَعْد المَوْل.'],
        ['key' => 'qabl', 'arabic' => 'قَبْل', 'pronunciation' => 'qabl', 'meaning' => 'before', 'category' => 'Direction', 'example' => 'الصَّيْدَلِيَّة قَبْل المَطْعَم.'],
        ['key' => 'imshi', 'arabic' => 'اِمْشِ', 'pronunciation' => 'imshi', 'meaning' => 'walk / go', 'category' => 'Direction Verb', 'example' => 'اِمْشِ إِلى الأَمام.'],
        ['key' => 'idhhab', 'arabic' => 'اِذْهَب', 'pronunciation' => 'idhhab', 'meaning' => 'go', 'category' => 'Direction Verb', 'example' => 'اِذْهَب يَمين.'],
        ['key' => 'luff', 'arabic' => 'لُفّ', 'pronunciation' => 'luff', 'meaning' => 'turn', 'category' => 'Direction Verb', 'example' => 'لُفّ يَمين.'],
        ['key' => 'qif', 'arabic' => 'قِف', 'pronunciation' => 'qif', 'meaning' => 'stop', 'category' => 'Direction Verb', 'example' => 'قِف هُنا.'],
        ['key' => 'matam', 'arabic' => 'مَطْعَم', 'pronunciation' => "mat'am", 'meaning' => 'restaurant', 'category' => 'Place Review', 'example' => 'أَيْنَ المَطْعَم؟'],
        ['key' => 'saydaliyyah', 'arabic' => 'صَيْدَلِيَّة', 'pronunciation' => 'saydaliyyah', 'meaning' => 'pharmacy', 'category' => 'Place Review', 'example' => 'الصَّيْدَلِيَّة قَريبَة.'],
        ['key' => 'mall', 'arabic' => 'مَوْل', 'pronunciation' => 'mall', 'meaning' => 'mall', 'category' => 'Place Review', 'example' => 'أَنا في المَوْل.'],
        ['key' => 'masjid', 'arabic' => 'مَسْجِد', 'pronunciation' => 'masjid', 'meaning' => 'mosque', 'category' => 'Place Review', 'example' => 'المَسْجِد أَمام البَيْت.'],
        ['key' => 'mustashfaa', 'arabic' => 'مُسْتَشْفى', 'pronunciation' => 'mustashfaa', 'meaning' => 'hospital', 'category' => 'Place Review', 'example' => 'المُسْتَشْفى بَعيد.'],
        ['key' => 'hammaam', 'arabic' => 'حَمّام', 'pronunciation' => 'hammaam', 'meaning' => 'bathroom', 'category' => 'Place Review', 'example' => 'أَيْنَ الحَمّام؟'],
        ['key' => 'mahall', 'arabic' => 'مَحَلّ', 'pronunciation' => 'mahall', 'meaning' => 'shop / store', 'category' => 'Place Review', 'example' => 'المَحَلّ يَمين.'],
        ['key' => 'shaari', 'arabic' => 'شارِع', 'pronunciation' => "shaari'", 'meaning' => 'street', 'category' => 'Place Review', 'example' => 'هذا شارِع كَبير.'],
        ['key' => 'bank', 'arabic' => 'بِنْك', 'pronunciation' => 'bank', 'meaning' => 'bank', 'category' => 'Place Review', 'example' => 'البِنْك قَريب مِن المَوْل.'],
        ['key' => 'madrasah', 'arabic' => 'مَدْرَسَة', 'pronunciation' => 'madrasah', 'meaning' => 'school', 'category' => 'Place Review', 'example' => 'المَدْرَسَة بَعيدَة.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Directions Vocabulary', 'key' => 'B1-L09-Directions-Vocab', 'file' => '/assets/audio/books/beginner/lesson-9/B1-L09-Directions-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L09-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-9/B1-L09-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'أَيْنَ المَطْعَم؟', 'en' => 'Where is the restaurant?'],
        ['ar' => 'أَيْنَ الصَّيْدَلِيَّة؟', 'en' => 'Where is the pharmacy?'],
        ['ar' => 'أَيْنَ الحَمّام؟', 'en' => 'Where is the bathroom?'],
        ['ar' => 'أَيْنَ المَوْل؟', 'en' => 'Where is the mall?'],
        ['ar' => 'أَيْنَ البِنْك؟', 'en' => 'Where is the bank?'],
        ['ar' => 'هَلْ المَطْعَم قَريب؟', 'en' => 'Is the restaurant near?'],
        ['ar' => 'كَيْفَ أَذْهَبُ إِلى المَوْل؟', 'en' => 'How do I go to the mall?'],
        ['ar' => 'مِن فَضْلِكَ، أَيْنَ الحَمّام؟', 'en' => 'Please, where is the bathroom?'],
        ['ar' => 'اِمْشِ إِلى الأَمام.', 'en' => 'Go straight / walk forward.'],
        ['ar' => 'اِذْهَب يَمين.', 'en' => 'Go right.'],
        ['ar' => 'اِذْهَب يَسار.', 'en' => 'Go left.'],
        ['ar' => 'لُفّ يَمين.', 'en' => 'Turn right.'],
        ['ar' => 'لُفّ يَسار.', 'en' => 'Turn left.'],
        ['ar' => 'قِف هُنا.', 'en' => 'Stop here.'],
        ['ar' => 'المَطْعَم عَلى اليَمين.', 'en' => 'The restaurant is on the right.'],
        ['ar' => 'الصَّيْدَلِيَّة عَلى اليَسار.', 'en' => 'The pharmacy is on the left.'],
        ['ar' => 'الحَمّام أَمامَكَ.', 'en' => 'The bathroom is in front of you.'],
        ['ar' => 'المَطْعَم بَعْد المَسْجِد.', 'en' => 'The restaurant is after the mosque.'],
    ],
    'grammar_tip' => [
        'title' => 'How to ask where and give simple directions',
        'body' => 'Use أَيْنَ to ask "Where?". Use اِمْشِ, اِذْهَب, and لُفّ as practical direction commands. Keep the answer short and step by step.',
        'examples' => [
            ['ar' => 'أَيْنَ المَطْعَم؟', 'en' => 'Where is the restaurant?'],
            ['ar' => 'اِمْشِ إِلى الأَمام.', 'en' => 'Go straight.'],
            ['ar' => 'اِذْهَب يَمين.', 'en' => 'Go right.'],
            ['ar' => 'لُفّ يَسار.', 'en' => 'Turn left.'],
            ['ar' => 'الصَّيْدَلِيَّة عَلى اليَمين.', 'en' => 'The pharmacy is on the right.'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: مِن فَضْلِكَ، أَيْنَ الصَّيْدَلِيَّة؟',
        'B: الصَّيْدَلِيَّة قَريبَة.',
        'A: كَيْفَ أَذْهَبُ إِلَيْها؟',
        'B: اِمْشِ إِلى الأَمام، ثُمَّ لُفّ يَمين.',
        'A: هَلْ هي بَعْد المَطْعَم؟',
        'B: نَعَم، الصَّيْدَلِيَّة بَعْد المَطْعَم عَلى اليَمين.',
        'A: شُكْرًا.',
        'B: عَفْوًا.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: Please, where is the pharmacy?',
        'B: The pharmacy is near.',
        'A: How do I go to it?',
        'B: Go straight, then turn right.',
        'A: Is it after the restaurant?',
        'B: Yes, the pharmacy is after the restaurant on the right.',
        'A: Thank you.',
        'B: You’re welcome.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does يَمين mean?', 'options' => ['A' => 'right', 'B' => 'left', 'C' => 'straight'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'What does يَسار mean?', 'options' => ['A' => 'right', 'B' => 'left', 'C' => 'behind'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'اِمْشِ إِلى الأَمام means:', 'options' => ['A' => 'Turn right.', 'B' => 'Go straight.', 'C' => 'Stop here.'], 'correct' => 'B'],
        ['id' => 'mcq_4', 'question' => 'أَيْنَ الحَمّام؟ means:', 'options' => ['A' => 'Where is the bathroom?', 'B' => 'What color is the bathroom?', 'C' => 'How much is the bathroom?'], 'correct' => 'A'],
        ['id' => 'mcq_5', 'question' => 'الصَّيْدَلِيَّة عَلى اليَسار means:', 'options' => ['A' => 'The pharmacy is on the right.', 'B' => 'The pharmacy is on the left.', 'C' => 'The pharmacy is far.'], 'correct' => 'B'],
    ],
    'direction_matching' => [
        ['id' => 'match_yameen', 'arabic' => 'يَمين', 'correct' => 'right'],
        ['id' => 'match_yasaar', 'arabic' => 'يَسار', 'correct' => 'left'],
        ['id' => 'match_amaam', 'arabic' => 'إِلى الأَمام', 'correct' => 'straight ahead'],
        ['id' => 'match_khalf', 'arabic' => 'خَلْف', 'correct' => 'behind'],
        ['id' => 'match_amaam2', 'arabic' => 'أَمام', 'correct' => 'in front of'],
        ['id' => 'match_huna', 'arabic' => 'هُنا', 'correct' => 'here'],
        ['id' => 'match_hunaak', 'arabic' => 'هُناك', 'correct' => 'there'],
        ['id' => 'match_baad', 'arabic' => 'بَعْد', 'correct' => 'after'],
        ['id' => 'match_qabl', 'arabic' => 'قَبْل', 'correct' => 'before'],
        ['id' => 'match_qif', 'arabic' => 'قِف', 'correct' => 'stop'],
    ],
    'direction_matching_options' => ['right', 'left', 'straight ahead', 'behind', 'in front of', 'here', 'there', 'after', 'before', 'stop'],
    'direction_recognition' => [
        ['id' => 'dir_1', 'question' => 'لُفّ يَمين', 'options' => ['A' => 'Turn right', 'B' => 'Turn left', 'C' => 'Go straight'], 'correct' => 'A'],
        ['id' => 'dir_2', 'question' => 'لُفّ يَسار', 'options' => ['A' => 'Turn right', 'B' => 'Turn left', 'C' => 'Stop here'], 'correct' => 'B'],
        ['id' => 'dir_3', 'question' => 'قِف هُنا', 'options' => ['A' => 'Go there', 'B' => 'Stop here', 'C' => 'Walk forward'], 'correct' => 'B'],
        ['id' => 'dir_4', 'question' => 'المَطْعَم عَلى اليَمين', 'options' => ['A' => 'The restaurant is on the right.', 'B' => 'The restaurant is on the left.', 'C' => 'The restaurant is far.'], 'correct' => 'A'],
        ['id' => 'dir_5', 'question' => 'الحَمّام أَمامَكَ', 'options' => ['A' => 'The bathroom is behind you.', 'B' => 'The bathroom is in front of you.', 'C' => 'The bathroom is on the left.'], 'correct' => 'B'],
        ['id' => 'dir_6', 'question' => 'الصَّيْدَلِيَّة بَعْد المَطْعَم', 'options' => ['A' => 'The pharmacy is before the restaurant.', 'B' => 'The pharmacy is after the restaurant.', 'C' => 'The pharmacy is inside the restaurant.'], 'correct' => 'B'],
    ],
    'category_practice' => [
        ['id' => 'cat_1', 'question' => 'يَمين', 'options' => ['Direction' => 'Direction', 'Place' => 'Place', 'Direction Verb' => 'Direction Verb'], 'correct' => 'Direction'],
        ['id' => 'cat_2', 'question' => 'مَطْعَم', 'options' => ['Direction' => 'Direction', 'Place' => 'Place', 'Direction Verb' => 'Direction Verb'], 'correct' => 'Place'],
        ['id' => 'cat_3', 'question' => 'اِمْشِ', 'options' => ['Direction' => 'Direction', 'Place' => 'Place', 'Direction Verb' => 'Direction Verb'], 'correct' => 'Direction Verb'],
        ['id' => 'cat_4', 'question' => 'صَيْدَلِيَّة', 'options' => ['Direction' => 'Direction', 'Place' => 'Place', 'Direction Verb' => 'Direction Verb'], 'correct' => 'Place'],
        ['id' => 'cat_5', 'question' => 'لُفّ', 'options' => ['Direction' => 'Direction', 'Place' => 'Place', 'Direction Verb' => 'Direction Verb'], 'correct' => 'Direction Verb'],
        ['id' => 'cat_6', 'question' => 'يَسار', 'options' => ['Direction' => 'Direction', 'Place' => 'Place', 'Direction Verb' => 'Direction Verb'], 'correct' => 'Direction'],
    ],
    'matching' => [],
    'matching_options' => [],
    'number_recognition' => [],
    'price_recognition' => [],
    'color_recognition' => [],
    'time_recognition' => [],
    'daily_action_matching' => [],
    'sequence_practice' => [],
    'description_matching' => [],
    'listening_review' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'أَيْنَ ________؟'],
        ['id' => 'cs_2', 'prompt' => 'اِمْشِ إِلى ________.'],
        ['id' => 'cs_3', 'prompt' => 'لُفّ ________.'],
        ['id' => 'cs_4', 'prompt' => 'المَطْعَم عَلى ________.'],
        ['id' => 'cs_5', 'prompt' => 'الصَّيْدَلِيَّة ________ المَطْعَم.'],
        ['id' => 'cs_6', 'prompt' => 'قِف ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write Simple Directions',
    'writing_instructions' => 'Write 5-6 Arabic sentences giving simple directions to a place. Use أَيْنَ, اِمْشِ إِلى الأَمام, لُفّ يَمين / يَسار, and عَلى اليَمين / عَلى اليَسار.',
    'writing_placeholder' => 'اكتب هنا اتجاهات بسيطة إلى مكان...',
    'min_sentences' => 5,
    'speaking_title' => 'Speaking Task - Ask and Give Directions',
    'speaking_instructions' => 'Record yourself for about 60 seconds. Ask where one place is, say if it is near or far, give two directions, say where the place is, and say thank you. Direct browser recording only.',
    'self_check_min' => 4,
    'self_check' => [
        'right_left' => 'I can say right and left in Arabic.',
        'go_straight' => 'I can say go straight in Arabic.',
        'ask_where_place' => 'I can ask where a place is.',
        'near_far' => 'I can say a place is near or far.',
        'turn_right_left' => 'I can say turn right and turn left.',
        'give_simple_directions' => 'I can give simple directions in Arabic.',
        'record_directions_roleplay' => 'I can record a short directions role-play.',
    ],
];
