<?php
declare(strict_types=1);

return [
    'unit_type' => 'lesson',
    'lesson_number' => 7,
    'title_en' => 'Home & Places',
    'title_ar' => 'البَيْت وَالأَماكِن',
    'slug' => 'lesson-7-home-places',
    'goal_en' => 'By the end of this lesson, you can talk about your home and simple places around you in Arabic.',
    'goal_ar' => 'في نهاية هذا الدرس، تستطيع أن تتحدث عن بيتك وبعض الأماكن حولك باللغة العربية.',
    'goal_checks' => [
        'Say basic room names in Arabic.',
        'Say common places in the city.',
        'Use في to say "in / at".',
        'Ask "Where is...?" using أَيْنَ.',
        'Say where you live.',
        'Describe nearby places.',
        'Record a short speaking task about home and places.',
    ],
    'situation_en' => 'You are talking to a new Arabic-speaking friend. They ask where you live and what places are near your home.',
    'situation_ar' => 'تتحدث مع صديق جديد يتكلم العربية. يسألك أين تعيش وما الأماكن القريبة من بيتك.',
    'warmup_title' => 'Quick Review from Lesson 6',
    'warmup_questions' => [
        'How do you say "This is a red pen" in Arabic?',
        'How do you say "This is a blue bag" in Arabic?',
        'How do you ask "What color is this?" in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'bayt', 'arabic' => 'بَيْت', 'pronunciation' => 'bayt', 'meaning' => 'house / home', 'category' => 'Home', 'example' => 'أَنا في البَيْت.'],
        ['key' => 'shaqqah', 'arabic' => 'شَقَّة', 'pronunciation' => 'shaqqah', 'meaning' => 'apartment', 'category' => 'Home', 'example' => 'أَنا أَعيشُ في شَقَّة.'],
        ['key' => 'ghurfah', 'arabic' => 'غُرْفَة', 'pronunciation' => 'ghurfah', 'meaning' => 'room', 'category' => 'Home', 'example' => 'هذه غُرْفَة كَبيرَة.'],
        ['key' => 'ghurfat_an_nawm', 'arabic' => 'غُرْفَة النَّوْم', 'pronunciation' => 'ghurfat an-nawm', 'meaning' => 'bedroom', 'category' => 'Home', 'example' => 'أَنا في غُرْفَة النَّوْم.'],
        ['key' => 'matbakh', 'arabic' => 'مَطْبَخ', 'pronunciation' => 'matbakh', 'meaning' => 'kitchen', 'category' => 'Home', 'example' => 'أُمّي في المَطْبَخ.'],
        ['key' => 'hammaam', 'arabic' => 'حَمّام', 'pronunciation' => 'hammaam', 'meaning' => 'bathroom', 'category' => 'Home', 'example' => 'الحَمّام هُنا.'],
        ['key' => 'saalah', 'arabic' => 'صالَة', 'pronunciation' => 'saalah', 'meaning' => 'living room / hall', 'category' => 'Home', 'example' => 'العائِلَة في الصالَة.'],
        ['key' => 'baab', 'arabic' => 'باب', 'pronunciation' => 'baab', 'meaning' => 'door', 'category' => 'Home/Object', 'example' => 'هذا باب أَبْيَض.'],
        ['key' => 'naafidhah', 'arabic' => 'نافِذَة', 'pronunciation' => 'naafidhah', 'meaning' => 'window', 'category' => 'Home/Object', 'example' => 'هذه نافِذَة كَبيرَة.'],
        ['key' => 'miftaah', 'arabic' => 'مِفْتاح', 'pronunciation' => 'miftaah', 'meaning' => 'key', 'category' => 'Home/Object', 'example' => 'أَيْنَ المِفْتاح؟'],
        ['key' => 'taawilah', 'arabic' => 'طاوِلَة', 'pronunciation' => 'taawilah', 'meaning' => 'table', 'category' => 'Home/Object', 'example' => 'الكِتاب على الطاوِلَة.'],
        ['key' => 'kursi', 'arabic' => 'كُرْسي', 'pronunciation' => 'kursi', 'meaning' => 'chair', 'category' => 'Home/Object', 'example' => 'هذا كُرْسي بُنِّي.'],
        ['key' => 'madrasah', 'arabic' => 'مَدْرَسَة', 'pronunciation' => 'madrasah', 'meaning' => 'school', 'category' => 'City Place', 'example' => 'المَدْرَسَة قَريبَة.'],
        ['key' => 'masjid', 'arabic' => 'مَسْجِد', 'pronunciation' => 'masjid', 'meaning' => 'mosque', 'category' => 'City Place', 'example' => 'المَسْجِد قَريب مِن البَيْت.'],
        ['key' => 'mustashfaa', 'arabic' => 'مُسْتَشْفى', 'pronunciation' => 'mustashfaa', 'meaning' => 'hospital', 'category' => 'City Place', 'example' => 'المُسْتَشْفى بَعيد.'],
        ['key' => 'saydaliyyah', 'arabic' => 'صَيْدَلِيَّة', 'pronunciation' => 'saydaliyyah', 'meaning' => 'pharmacy', 'category' => 'City Place', 'example' => 'الصَّيْدَلِيَّة قَريبَة.'],
        ['key' => 'sooq', 'arabic' => 'سُوق', 'pronunciation' => 'sooq', 'meaning' => 'market', 'category' => 'City Place', 'example' => 'أَنا في السُّوق.'],
        ['key' => 'matam', 'arabic' => 'مَطْعَم', 'pronunciation' => "mat'am", 'meaning' => 'restaurant', 'category' => 'City Place', 'example' => 'المَطْعَم هُنا.'],
        ['key' => 'kaafeeh', 'arabic' => 'كافيه', 'pronunciation' => 'kaafeeh', 'meaning' => 'cafe', 'category' => 'City Place', 'example' => 'الكافيه قَريب.'],
        ['key' => 'mall', 'arabic' => 'مَوْل', 'pronunciation' => 'mall', 'meaning' => 'mall', 'category' => 'City Place', 'example' => 'أَنا في المَوْل.'],
        ['key' => 'shaari', 'arabic' => 'شارِع', 'pronunciation' => "shaari'", 'meaning' => 'street', 'category' => 'City Place', 'example' => 'هذا شارِع كَبير.'],
        ['key' => 'hadeeqah', 'arabic' => 'حَديقَة', 'pronunciation' => 'hadeeqah', 'meaning' => 'park / garden', 'category' => 'City Place', 'example' => 'الحَديقَة جَميلَة.'],
        ['key' => 'mahall', 'arabic' => 'مَحَلّ', 'pronunciation' => 'mahall', 'meaning' => 'shop / store', 'category' => 'City Place', 'example' => 'هذا مَحَلّ صَغير.'],
        ['key' => 'bank', 'arabic' => 'بِنْك', 'pronunciation' => 'bank', 'meaning' => 'bank', 'category' => 'City Place', 'example' => 'البِنْك قَريب مِن المَوْل.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Home & Places Vocabulary', 'key' => 'B1-L07-Home-Places-Vocab', 'file' => '/assets/audio/books/beginner/lesson-7/B1-L07-Home-Places-Vocab.mp3'],
        ['title' => 'Audio Practice - Dialogue', 'key' => 'B1-L07-Dialogue', 'file' => '/assets/audio/books/beginner/lesson-7/B1-L07-Dialogue.mp3'],
    ],
    'sentences' => [
        ['ar' => 'أَيْنَ البَيْت؟', 'en' => 'Where is the house?'],
        ['ar' => 'أَيْنَ المَطْبَخ؟', 'en' => 'Where is the kitchen?'],
        ['ar' => 'أَيْنَ المِفْتاح؟', 'en' => 'Where is the key?'],
        ['ar' => 'المِفْتاح في الغُرْفَة.', 'en' => 'The key is in the room.'],
        ['ar' => 'الكِتاب في الصالَة.', 'en' => 'The book is in the living room.'],
        ['ar' => 'أَنا في البَيْت.', 'en' => 'I am at home.'],
        ['ar' => 'أَنا في المَوْل.', 'en' => 'I am in the mall.'],
        ['ar' => 'أَنا في المَطْعَم.', 'en' => 'I am in the restaurant.'],
        ['ar' => 'المَطْعَم قَريب.', 'en' => 'The restaurant is near.'],
        ['ar' => 'المُسْتَشْفى بَعيد.', 'en' => 'The hospital is far.'],
        ['ar' => 'أَنا أَعيشُ في دُبَي.', 'en' => 'I live in Dubai.'],
        ['ar' => 'أَنا أَعيشُ في شَقَّة.', 'en' => 'I live in an apartment.'],
        ['ar' => 'بَيْتي قَريب مِن المَسْجِد.', 'en' => 'My house is near the mosque.'],
        ['ar' => 'هُناك مَطْعَم قَريب.', 'en' => 'There is a restaurant nearby.'],
        ['ar' => 'هُناك صَيْدَلِيَّة قَريبَة.', 'en' => 'There is a pharmacy nearby.'],
    ],
    'grammar_tip' => [
        'title' => 'How to say "in / at" and ask "Where?"',
        'body' => 'Use في to say "in" or "at". Use أَيْنَ to ask "Where?". Keep the pattern practical: أنا في البيت. أين المطعم؟',
        'examples' => [
            ['ar' => 'أَنا في البَيْت.', 'en' => 'I am at home.'],
            ['ar' => 'أَنا في المَوْل.', 'en' => 'I am in the mall.'],
            ['ar' => 'الكِتاب في الغُرْفَة.', 'en' => 'The book is in the room.'],
            ['ar' => 'أَيْنَ المَطْعَم؟', 'en' => 'Where is the restaurant?'],
            ['ar' => 'أَيْنَ تَعيشُ؟', 'en' => 'Where do you live? - to a male'],
        ],
    ],
    'dialogue_ar' => [
        'A: السَّلامُ عَلَيْكُم.',
        'B: وَعَلَيْكُمُ السَّلام.',
        'A: أَيْنَ تَعيشُ؟',
        'B: أَنا أَعيشُ في دُبَي.',
        'A: هَلْ تَعيشُ في بَيْت أَو شَقَّة؟',
        'B: أَنا أَعيشُ في شَقَّة.',
        'A: ما القَريب مِن بَيْتِكَ؟',
        'B: هُناك مَوْل قَريب وَمَطْعَم قَريب.',
        'A: أَيْنَ الصَّيْدَلِيَّة؟',
        'B: الصَّيْدَلِيَّة قَريبَة مِن البَيْت.',
    ],
    'dialogue_en' => [
        'A: Peace be upon you.',
        'B: And peace be upon you.',
        'A: Where do you live?',
        'B: I live in Dubai.',
        'A: Do you live in a house or an apartment?',
        'B: I live in an apartment.',
        'A: What is near your house?',
        'B: There is a mall nearby and a restaurant nearby.',
        'A: Where is the pharmacy?',
        'B: The pharmacy is near the house.',
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does بَيْت mean?', 'options' => ['A' => 'house / home', 'B' => 'school', 'C' => 'street'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'What does مَطْبَخ mean?', 'options' => ['A' => 'bathroom', 'B' => 'kitchen', 'C' => 'bedroom'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'أَنا في البَيْت means:', 'options' => ['A' => 'I am at home.', 'B' => 'I live in Dubai.', 'C' => 'I want the house.'], 'correct' => 'A'],
        ['id' => 'mcq_4', 'question' => 'أَيْنَ المِفْتاح؟ means:', 'options' => ['A' => 'What color is the key?', 'B' => 'Where is the key?', 'C' => 'How much is the key?'], 'correct' => 'B'],
        ['id' => 'mcq_5', 'question' => 'المَطْعَم قَريب means:', 'options' => ['A' => 'The restaurant is far.', 'B' => 'The restaurant is near.', 'C' => 'The restaurant is big.'], 'correct' => 'B'],
    ],
    'matching' => [
        ['id' => 'match_bayt', 'arabic' => 'بَيْت', 'correct' => 'house / home'],
        ['id' => 'match_shaqqah', 'arabic' => 'شَقَّة', 'correct' => 'apartment'],
        ['id' => 'match_ghurfah', 'arabic' => 'غُرْفَة', 'correct' => 'room'],
        ['id' => 'match_matbakh', 'arabic' => 'مَطْبَخ', 'correct' => 'kitchen'],
        ['id' => 'match_hammaam', 'arabic' => 'حَمّام', 'correct' => 'bathroom'],
        ['id' => 'match_madrasah', 'arabic' => 'مَدْرَسَة', 'correct' => 'school'],
        ['id' => 'match_masjid', 'arabic' => 'مَسْجِد', 'correct' => 'mosque'],
        ['id' => 'match_saydaliyyah', 'arabic' => 'صَيْدَلِيَّة', 'correct' => 'pharmacy'],
        ['id' => 'match_matam', 'arabic' => 'مَطْعَم', 'correct' => 'restaurant'],
        ['id' => 'match_mall', 'arabic' => 'مَوْل', 'correct' => 'mall'],
    ],
    'matching_options' => ['house / home', 'apartment', 'room', 'kitchen', 'bathroom', 'school', 'mosque', 'pharmacy', 'restaurant', 'mall'],
    'category_practice' => [
        ['id' => 'cat_1', 'question' => 'مَطْبَخ', 'options' => ['Home' => 'Home', 'City Place' => 'City Place', 'Object' => 'Object'], 'correct' => 'Home'],
        ['id' => 'cat_2', 'question' => 'مَوْل', 'options' => ['Home' => 'Home', 'City Place' => 'City Place', 'Object' => 'Object'], 'correct' => 'City Place'],
        ['id' => 'cat_3', 'question' => 'مِفْتاح', 'options' => ['Home' => 'Home', 'City Place' => 'City Place', 'Object' => 'Object'], 'correct' => 'Object'],
        ['id' => 'cat_4', 'question' => 'صَيْدَلِيَّة', 'options' => ['Home' => 'Home', 'City Place' => 'City Place', 'Object' => 'Object'], 'correct' => 'City Place'],
        ['id' => 'cat_5', 'question' => 'غُرْفَة النَّوْم', 'options' => ['Home' => 'Home', 'City Place' => 'City Place', 'Object' => 'Object'], 'correct' => 'Home'],
        ['id' => 'cat_6', 'question' => 'طاوِلَة', 'options' => ['Home' => 'Home', 'City Place' => 'City Place', 'Object' => 'Object'], 'correct' => 'Object'],
    ],
    'number_recognition' => [],
    'price_recognition' => [],
    'color_recognition' => [],
    'description_matching' => [],
    'listening_review' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'أَنا في ________.'],
        ['id' => 'cs_2', 'prompt' => 'أَنا أَعيشُ في ________.'],
        ['id' => 'cs_3', 'prompt' => 'أَيْنَ ________؟'],
        ['id' => 'cs_4', 'prompt' => 'المَطْعَم ________.'],
        ['id' => 'cs_5', 'prompt' => 'بَيْتي قَريب مِن ________.'],
    ],
    'arrange_words' => [],
    'writing_title' => 'Writing Task - Write About Your Home and Nearby Places',
    'writing_instructions' => 'Write 5 Arabic sentences about where you live and what places are near your home. You can write about a practice/fake place if you do not want to share personal information.',
    'writing_placeholder' => 'اكتب هنا 5 جمل عن بيتك والأماكن القريبة...',
    'min_sentences' => 5,
    'speaking_title' => 'Speaking Task - Talk About Your Home and Places Near You',
    'speaking_instructions' => 'Record yourself for 45-60 seconds. Say where you live, whether you live in a house or apartment, two places near your home, one place far away, and ask one question using أَيْنَ. Direct browser recording only.',
    'self_check_min' => 4,
    'self_check' => [
        'room_names' => 'I can say basic room names in Arabic.',
        'city_places' => 'I can say common places in the city.',
        'say_where_live' => 'I can say where I live in Arabic.',
        'use_fee' => 'I can use في in simple sentences.',
        'ask_where' => 'I can ask "Where is...?" in Arabic.',
        'near_far' => 'I can say near and far in Arabic.',
        'record_home_places' => 'I can record a short speaking task about home and places.',
    ],
];
