<?php
declare(strict_types=1);

return [
    'unit_type' => 'review',
    'lesson_number' => 102,
    'display_label' => 'Review 2',
    'title_en' => 'Review 2: Lessons 5-8',
    'title_ar' => 'مُراجَعَة ٢: الدُّروس ٥-٨',
    'slug' => 'review-2-lessons-5-to-8',
    'covers' => 'Shopping, Colors & Objects, Home & Places, Time & Daily Routine',
    'goal_en' => 'In this review, you will practice everything from Lessons 5-8 and use it together in real-life situations.',
    'goal_ar' => 'في هذه المراجعة، ستتدرب على كل ما تعلمته في الدروس ٥-٨ وتستخدمه معًا في مواقف حقيقية.',
    'goal_checks' => [
        'Ask about prices.',
        'Use shopping words.',
        'Describe objects with colors.',
        'Talk about home and nearby places.',
        'Say simple times.',
        'Describe a daily routine.',
        'Record a longer mixed speaking task.',
    ],
    'review_overview' => [
        ['title' => 'Lesson 5 - Shopping', 'items' => ['بِكَم؟', 'كَم السِّعْر؟', 'أُريد هذا / أُريد هذه', 'غالي / رَخيص', 'السِّعْر عَشَرَة دَراهِم']],
        ['title' => 'Lesson 6 - Colors & Objects', 'items' => ['أَحْمَر / حَمْراء', 'أَزْرَق / زَرْقاء', 'أَسْوَد / سَوْداء', 'قَلَم / كِتاب / هاتِف / حَقيبَة', 'هذا قَلَم أَحْمَر', 'هذه حَقيبَة زَرْقاء']],
        ['title' => 'Lesson 7 - Home & Places', 'items' => ['بَيْت / شَقَّة / غُرْفَة / مَطْبَخ', 'مَوْل / مَطْعَم / صَيْدَلِيَّة / مُسْتَشْفى', 'أَنا في البَيْت', 'أَيْنَ...؟', 'قَريب / بَعيد']],
        ['title' => 'Lesson 8 - Time & Daily Routine', 'items' => ['السّاعَة...', 'في السّاعَة...', 'الصَّباح / المَساء / اللَّيْل', 'أَصْحو / أَذْهَبُ / أَدْرُسُ / أَنامُ', 'ثُمَّ / بَعْدَ ذَلِكَ']],
    ],
    'situation_en' => 'You are reviewing Lessons 5-8 and combining shopping, colors, places, and daily routine in one practical conversation.',
    'situation_ar' => 'أنت تراجع الدروس ٥-٨ وتجمع التسوق والألوان والأماكن والروتين اليومي في محادثة عملية واحدة.',
    'warmup_title' => 'Quick Warm-up',
    'warmup_questions' => [
        'Can you ask "How much is this?" in Arabic?',
        'Can you describe one object with a color?',
        'Can you say one place near your home?',
        'Can you say one sentence about your daily routine?',
    ],
    'vocabulary' => [
        ['key' => 'sir', 'arabic' => 'سِعْر', 'pronunciation' => "si'r", 'meaning' => 'price', 'category' => 'Lesson 5', 'example' => 'كَم السِّعْر؟'],
        ['key' => 'bikam', 'arabic' => 'بِكَم؟', 'pronunciation' => 'bikam?', 'meaning' => 'how much?', 'category' => 'Lesson 5', 'example' => 'هذا بِكَم؟'],
        ['key' => 'dirham', 'arabic' => 'دِرْهَم', 'pronunciation' => 'dirham', 'meaning' => 'dirham', 'category' => 'Lesson 5', 'example' => 'السِّعْر عَشَرَة دَراهِم.'],
        ['key' => 'ghaalee', 'arabic' => 'غالي', 'pronunciation' => 'ghaalee', 'meaning' => 'expensive', 'category' => 'Lesson 5', 'example' => 'هذا غالي.'],
        ['key' => 'rakhees', 'arabic' => 'رَخيص', 'pronunciation' => 'rakhees', 'meaning' => 'cheap', 'category' => 'Lesson 5', 'example' => 'هذا رَخيص.'],
        ['key' => 'ahmar', 'arabic' => 'أَحْمَر', 'pronunciation' => 'ahmar', 'meaning' => 'red', 'category' => 'Lesson 6', 'example' => 'هذا قَلَم أَحْمَر.'],
        ['key' => 'azraq', 'arabic' => 'أَزْرَق', 'pronunciation' => 'azraq', 'meaning' => 'blue', 'category' => 'Lesson 6', 'example' => 'هذا كِتاب أَزْرَق.'],
        ['key' => 'aswad', 'arabic' => 'أَسْوَد', 'pronunciation' => 'aswad', 'meaning' => 'black', 'category' => 'Lesson 6', 'example' => 'هذا هاتِف أَسْوَد.'],
        ['key' => 'qalam', 'arabic' => 'قَلَم', 'pronunciation' => 'qalam', 'meaning' => 'pen', 'category' => 'Lesson 6', 'example' => 'هذا قَلَم.'],
        ['key' => 'kitaab', 'arabic' => 'كِتاب', 'pronunciation' => 'kitaab', 'meaning' => 'book', 'category' => 'Lesson 6', 'example' => 'هذا كِتاب.'],
        ['key' => 'haqeebah', 'arabic' => 'حَقيبَة', 'pronunciation' => 'haqeebah', 'meaning' => 'bag', 'category' => 'Lesson 6', 'example' => 'هذه حَقيبَة زَرْقاء.'],
        ['key' => 'bayt', 'arabic' => 'بَيْت', 'pronunciation' => 'bayt', 'meaning' => 'house / home', 'category' => 'Lesson 7', 'example' => 'أَنا في البَيْت.'],
        ['key' => 'shaqqah', 'arabic' => 'شَقَّة', 'pronunciation' => 'shaqqah', 'meaning' => 'apartment', 'category' => 'Lesson 7', 'example' => 'أَنا أَعيشُ في شَقَّة.'],
        ['key' => 'matam', 'arabic' => 'مَطْعَم', 'pronunciation' => "mat'am", 'meaning' => 'restaurant', 'category' => 'Lesson 7', 'example' => 'أَيْنَ المَطْعَم؟'],
        ['key' => 'mall', 'arabic' => 'مَوْل', 'pronunciation' => 'mall', 'meaning' => 'mall', 'category' => 'Lesson 7', 'example' => 'بَيْتي قَريب مِن المَوْل.'],
        ['key' => 'saydaliyyah', 'arabic' => 'صَيْدَلِيَّة', 'pronunciation' => 'saydaliyyah', 'meaning' => 'pharmacy', 'category' => 'Lesson 7', 'example' => 'أَيْنَ الصَّيْدَلِيَّة؟'],
        ['key' => 'qareeb', 'arabic' => 'قَريب', 'pronunciation' => 'qareeb', 'meaning' => 'near', 'category' => 'Lesson 7', 'example' => 'المَوْل قَريب.'],
        ['key' => 'baeed', 'arabic' => 'بَعيد', 'pronunciation' => "ba'eed", 'meaning' => 'far', 'category' => 'Lesson 7', 'example' => 'المُسْتَشْفى بَعيد.'],
        ['key' => 'as_saah', 'arabic' => 'السّاعَة', 'pronunciation' => "as-saa'ah", 'meaning' => 'the time / o’clock', 'category' => 'Lesson 8', 'example' => 'السّاعَة سَبْعَة.'],
        ['key' => 'as_sabaah', 'arabic' => 'الصَّباح', 'pronunciation' => 'as-sabaah', 'meaning' => 'morning', 'category' => 'Lesson 8', 'example' => 'أَصْحو في الصَّباح.'],
        ['key' => 'al_masaa', 'arabic' => 'المَساء', 'pronunciation' => "al-masaa'", 'meaning' => 'evening', 'category' => 'Lesson 8', 'example' => 'أَدْرُسُ في المَساء.'],
        ['key' => 'ashu', 'arabic' => 'أَصْحو', 'pronunciation' => 'ashu', 'meaning' => 'I wake up', 'category' => 'Lesson 8', 'example' => 'أَصْحو في السّاعَة سَبْعَة.'],
        ['key' => 'adhhabu', 'arabic' => 'أَذْهَبُ', 'pronunciation' => 'adhhabu', 'meaning' => 'I go', 'category' => 'Lesson 8', 'example' => 'أَذْهَبُ إلى العَمَل.'],
        ['key' => 'adrusu', 'arabic' => 'أَدْرُسُ', 'pronunciation' => 'adrusu', 'meaning' => 'I study', 'category' => 'Lesson 8', 'example' => 'أَدْرُسُ العَرَبِيَّة.'],
        ['key' => 'anaamu', 'arabic' => 'أَنامُ', 'pronunciation' => 'anaamu', 'meaning' => 'I sleep', 'category' => 'Lesson 8', 'example' => 'أَنامُ في اللَّيْل.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Review 2 Vocabulary', 'key' => 'B1-R02-Review-Vocab', 'file' => '/assets/audio/books/beginner/review-2/B1-R02-Review-Vocab.mp3'],
        ['title' => 'Listening Review Task', 'key' => 'B1-R02-Listening-Review', 'file' => '/assets/audio/books/beginner/review-2/B1-R02-Listening-Review.mp3'],
    ],
    'sentences' => [
        ['ar' => 'هذا بِكَم؟', 'en' => 'How much is this?'],
        ['ar' => 'كَم السِّعْر؟', 'en' => 'How much is the price?'],
        ['ar' => 'أُريد هذا، مِن فَضْلِكَ.', 'en' => 'I want this, please.'],
        ['ar' => 'هذا غالي.', 'en' => 'This is expensive.'],
        ['ar' => 'هذا قَلَم أَحْمَر.', 'en' => 'This is a red pen.'],
        ['ar' => 'هذه حَقيبَة زَرْقاء.', 'en' => 'This is a blue bag.'],
        ['ar' => 'ما لَوْن هذا؟', 'en' => 'What color is this?'],
        ['ar' => 'أَنا أَعيشُ في شَقَّة.', 'en' => 'I live in an apartment.'],
        ['ar' => 'بَيْتي قَريب مِن المَوْل.', 'en' => 'My house is near the mall.'],
        ['ar' => 'أَيْنَ الصَّيْدَلِيَّة؟', 'en' => 'Where is the pharmacy?'],
        ['ar' => 'أَصْحو في السّاعَة سَبْعَة.', 'en' => 'I wake up at seven o’clock.'],
        ['ar' => 'أَدْرُسُ العَرَبِيَّة في المَساء.', 'en' => 'I study Arabic in the evening.'],
        ['ar' => 'أَنامُ في اللَّيْل.', 'en' => 'I sleep at night.'],
    ],
    'grammar_tip' => [
        'title' => 'Review tip',
        'body' => 'Use short clear sentences. The goal is to combine shopping, object description, places, and routine without making the language too complicated.',
        'examples' => [
            ['ar' => 'هذا القَلَم بِكَم؟ هذا قَلَم أَحْمَر. بَيْتي قَريب مِن المَوْل. أَصْحو في السّاعَة سَبْعَة.', 'en' => 'How much is this pen? This is a red pen. My house is near the mall. I wake up at seven o’clock.'],
        ],
    ],
    'dialogue_ar' => [],
    'dialogue_en' => [],
    'listening_review' => [
        ['id' => 'lr_1', 'question' => 'What did you hear?', 'options' => ['A' => 'How much is this?', 'B' => 'Where is this?', 'C' => 'What color is this?'], 'correct' => 'A'],
        ['id' => 'lr_2', 'question' => 'What did you hear?', 'options' => ['A' => 'This is a blue book.', 'B' => 'This is a red pen.', 'C' => 'This is a black phone.'], 'correct' => 'B'],
        ['id' => 'lr_3', 'question' => 'What did you hear?', 'options' => ['A' => 'My house is far from the mall.', 'B' => 'My house is near the mall.', 'C' => 'I live in the mall.'], 'correct' => 'B'],
        ['id' => 'lr_4', 'question' => 'What did you hear?', 'options' => ['A' => 'I sleep at night.', 'B' => 'I wake up at seven o’clock.', 'C' => 'I go to work.'], 'correct' => 'B'],
        ['id' => 'lr_5', 'question' => 'What did you hear?', 'options' => ['A' => 'I study Arabic in the evening.', 'B' => 'I eat at noon.', 'C' => 'I return home.'], 'correct' => 'A'],
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'بِكَم؟ means:', 'options' => ['A' => 'How old?', 'B' => 'How much?', 'C' => 'Where?'], 'correct' => 'B'],
        ['id' => 'mcq_2', 'question' => 'غالي means:', 'options' => ['A' => 'cheap', 'B' => 'expensive', 'C' => 'red'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'أَزْرَق means:', 'options' => ['A' => 'blue', 'B' => 'red', 'C' => 'black'], 'correct' => 'A'],
        ['id' => 'mcq_4', 'question' => 'هذه حَقيبَة زَرْقاء means:', 'options' => ['A' => 'This is a red car.', 'B' => 'This is a blue bag.', 'C' => 'This is a black phone.'], 'correct' => 'B'],
        ['id' => 'mcq_5', 'question' => 'بَيْت means:', 'options' => ['A' => 'house / home', 'B' => 'restaurant', 'C' => 'market'], 'correct' => 'A'],
        ['id' => 'mcq_6', 'question' => 'أَيْنَ الصَّيْدَلِيَّة؟ means:', 'options' => ['A' => 'How much is the pharmacy?', 'B' => 'Where is the pharmacy?', 'C' => 'What color is the pharmacy?'], 'correct' => 'B'],
        ['id' => 'mcq_7', 'question' => 'أَصْحو means:', 'options' => ['A' => 'I wake up', 'B' => 'I sleep', 'C' => 'I eat'], 'correct' => 'A'],
        ['id' => 'mcq_8', 'question' => 'ثُمَّ means:', 'options' => ['A' => 'then', 'B' => 'near', 'C' => 'expensive'], 'correct' => 'A'],
    ],
    'matching' => [
        ['id' => 'match_sir', 'arabic' => 'سِعْر', 'correct' => 'price'],
        ['id' => 'match_rakhees', 'arabic' => 'رَخيص', 'correct' => 'cheap'],
        ['id' => 'match_qalam', 'arabic' => 'قَلَم', 'correct' => 'pen'],
        ['id' => 'match_haqeebah', 'arabic' => 'حَقيبَة', 'correct' => 'bag'],
        ['id' => 'match_bayt', 'arabic' => 'بَيْت', 'correct' => 'house / home'],
        ['id' => 'match_mall', 'arabic' => 'مَوْل', 'correct' => 'mall'],
        ['id' => 'match_saaah', 'arabic' => 'السّاعَة', 'correct' => 'the time / o’clock'],
        ['id' => 'match_anaamu', 'arabic' => 'أَنامُ', 'correct' => 'I sleep'],
    ],
    'matching_options' => ['price', 'cheap', 'pen', 'bag', 'house / home', 'mall', 'the time / o’clock', 'I sleep'],
    'category_practice' => [
        ['id' => 'cat_1', 'question' => 'بِكَم؟', 'options' => ['Shopping' => 'Shopping', 'Color/Object' => 'Color/Object', 'Place' => 'Place', 'Routine' => 'Routine'], 'correct' => 'Shopping'],
        ['id' => 'cat_2', 'question' => 'أَحْمَر', 'options' => ['Shopping' => 'Shopping', 'Color/Object' => 'Color/Object', 'Place' => 'Place', 'Routine' => 'Routine'], 'correct' => 'Color/Object'],
        ['id' => 'cat_3', 'question' => 'مَطْعَم', 'options' => ['Shopping' => 'Shopping', 'Color/Object' => 'Color/Object', 'Place' => 'Place', 'Routine' => 'Routine'], 'correct' => 'Place'],
        ['id' => 'cat_4', 'question' => 'أَصْحو', 'options' => ['Shopping' => 'Shopping', 'Color/Object' => 'Color/Object', 'Place' => 'Place', 'Routine' => 'Routine'], 'correct' => 'Routine'],
        ['id' => 'cat_5', 'question' => 'قَريب', 'options' => ['Shopping' => 'Shopping', 'Color/Object' => 'Color/Object', 'Place' => 'Place', 'Routine' => 'Routine'], 'correct' => 'Place'],
        ['id' => 'cat_6', 'question' => 'دِرْهَم', 'options' => ['Shopping' => 'Shopping', 'Color/Object' => 'Color/Object', 'Place' => 'Place', 'Routine' => 'Routine'], 'correct' => 'Shopping'],
        ['id' => 'cat_7', 'question' => 'كِتاب', 'options' => ['Shopping' => 'Shopping', 'Color/Object' => 'Color/Object', 'Place' => 'Place', 'Routine' => 'Routine'], 'correct' => 'Color/Object'],
        ['id' => 'cat_8', 'question' => 'أَدْرُسُ', 'options' => ['Shopping' => 'Shopping', 'Color/Object' => 'Color/Object', 'Place' => 'Place', 'Routine' => 'Routine'], 'correct' => 'Routine'],
    ],
    'number_recognition' => [],
    'price_recognition' => [],
    'color_recognition' => [],
    'time_recognition' => [],
    'daily_action_matching' => [],
    'sequence_practice' => [],
    'description_matching' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'هذا ________؟'],
        ['id' => 'cs_2', 'prompt' => 'هذا قَلَم ________.'],
        ['id' => 'cs_3', 'prompt' => 'هذه حَقيبَة ________.'],
        ['id' => 'cs_4', 'prompt' => 'أَنا أَعيشُ في ________.'],
        ['id' => 'cs_5', 'prompt' => 'بَيْتي قَريب مِن ________.'],
        ['id' => 'cs_6', 'prompt' => 'أَصْحو في السّاعَة ________.'],
        ['id' => 'cs_7', 'prompt' => 'أَدْرُسُ العَرَبِيَّة في ________.'],
    ],
    'arrange_words' => [],
    'writing_tasks' => [
        [
            'key' => 'shopping_object',
            'title' => 'Mini Writing Task 1 - Shopping & Object Description',
            'instructions' => 'Write 5-6 Arabic sentences. Ask about a price, describe one object with a color, and say if it is expensive or cheap.',
            'placeholder' => 'اكتب هنا موقف تسوق ووصف شيء...',
            'min_sentences' => 5,
        ],
        [
            'key' => 'home_routine',
            'title' => 'Mini Writing Task 2 - Home & Daily Routine',
            'instructions' => 'Write 6 Arabic sentences about where you live and your daily routine. You can write about a practice/fake place if you do not want to share personal information.',
            'placeholder' => 'اكتب هنا عن بيتك وروتينك اليومي...',
            'min_sentences' => 6,
        ],
    ],
    'writing_title' => '',
    'writing_instructions' => '',
    'writing_placeholder' => '',
    'min_sentences' => 0,
    'speaking_title' => 'Review 2 Speaking Challenge',
    'speaking_instructions' => 'Record yourself for 75-120 seconds. Include shopping, object description, home/places, and daily routine. Use ثُمَّ or بَعْدَ ذَلِكَ at least once. Direct browser recording only.',
    'self_check_min' => 4,
    'submit_label' => 'Submit Review',
    'submitted_message' => 'Review Submitted - Awaiting Teacher Feedback.',
    'self_check' => [
        'ask_prices' => 'I can ask about prices in Arabic.',
        'describe_objects_colors' => 'I can describe objects with colors in Arabic.',
        'talk_home_places' => 'I can talk about home and nearby places in Arabic.',
        'say_simple_times' => 'I can say simple times in Arabic.',
        'talk_daily_routine' => 'I can talk about my daily routine in Arabic.',
        'combine_lessons_5_8' => 'I can combine topics from Lessons 5-8 in speaking.',
        'understand_simple_sentences' => 'I can understand simple Arabic sentences from Lessons 5-8.',
    ],
];
