<?php
declare(strict_types=1);

return [
    'unit_type' => 'review',
    'lesson_number' => 101,
    'display_label' => 'Review 1',
    'title_en' => 'Review 1: Lessons 1-4',
    'title_ar' => 'مُراجَعَة ١: الدُّروس ١-٤',
    'slug' => 'review-1-lessons-1-to-4',
    'covers' => 'Introduce Yourself, Numbers, Family, Food & Drinks',
    'goal_en' => 'In this review, you will practice everything from Lessons 1-4 and use it together in real-life situations.',
    'goal_ar' => 'في هذه المراجعة، ستتدرب على كل ما تعلمته في الدروس ١-٤ وتستخدمه معًا في مواقف حقيقية.',
    'goal_checks' => [
        'Introduce themselves.',
        'Say age and phone number.',
        'Talk about family.',
        'Order food and drinks.',
        'Answer simple Arabic questions.',
        'Record a longer mixed speaking task.',
    ],
    'review_overview' => [
        ['title' => 'Lesson 1 - Introduce Yourself', 'items' => ['أَنا اسْمي...', 'أَنا مِن...', 'أَنا أَعيشُ في...', 'ما اسْمُكَ؟', 'مِن أَيْنَ أَنْتَ؟']],
        ['title' => 'Lesson 2 - Numbers, Age & Phone Number', 'items' => ['صِفْر إلى عِشْرون', 'عُمْري...', 'كَمْ عُمْرُكَ؟', 'رَقْمُ هاتِفي...', 'ما رَقْمُ هاتِفِكَ؟']],
        ['title' => 'Lesson 3 - Family', 'items' => ['أَب / أُم / أَخ / أُخْت', 'عِنْدي...', 'لَيْسَ عِنْدي...', 'عائِلَتي كَبيرَة / صَغيرَة']],
        ['title' => 'Lesson 4 - Food & Drinks', 'items' => ['ماء / شاي / قَهْوَة / عَصير', 'دَجاج / أَرُزّ / سَمَك / خُبْز', 'أُريد...', 'لا أُريد...', 'مِن فَضْلِكَ / شُكْرًا']],
    ],
    'situation_en' => 'You are reviewing Lessons 1-4 and combining them in one practical conversation.',
    'situation_ar' => 'أنت تراجع الدروس ١-٤ وتجمعها في محادثة عملية واحدة.',
    'warmup_title' => 'Quick Warm-up',
    'warmup_questions' => [
        'Can you introduce yourself in Arabic?',
        'Can you say your age in Arabic?',
        'Can you say one family word in Arabic?',
        'Can you order one drink in Arabic?',
    ],
    'vocabulary' => [
        ['key' => 'ism', 'arabic' => 'اِسْم', 'pronunciation' => 'ism', 'meaning' => 'name', 'category' => 'Lesson 1', 'example' => 'أَنا اسْمي أَحْمَد.'],
        ['key' => 'balad', 'arabic' => 'بَلَد', 'pronunciation' => 'balad', 'meaning' => 'country', 'category' => 'Lesson 1', 'example' => 'أَنا مِن مِصْر.'],
        ['key' => 'madeenah', 'arabic' => 'مَدينَة', 'pronunciation' => 'madeenah', 'meaning' => 'city', 'category' => 'Lesson 1', 'example' => 'أَنا أَعيشُ في دُبَي.'],
        ['key' => 'aeeshu', 'arabic' => 'أَعيشُ', 'pronunciation' => "a'eeshu", 'meaning' => 'I live', 'category' => 'Lesson 1', 'example' => 'أَنا أَعيشُ في دُبَي.'],
        ['key' => 'waahid', 'arabic' => 'واحِد', 'pronunciation' => 'waahid', 'meaning' => 'one', 'category' => 'Lesson 2', 'example' => 'رَقْمُ هاتِفي واحِد.'],
        ['key' => 'khamsa', 'arabic' => 'خَمْسَة', 'pronunciation' => 'khamsa', 'meaning' => 'five', 'category' => 'Lesson 2', 'example' => 'خَمْسَة.'],
        ['key' => 'ashara', 'arabic' => 'عَشَرَة', 'pronunciation' => 'ashara', 'meaning' => 'ten', 'category' => 'Lesson 2', 'example' => 'عَشَرَة.'],
        ['key' => 'ishroon', 'arabic' => 'عِشْرون', 'pronunciation' => 'ishroon', 'meaning' => 'twenty', 'category' => 'Lesson 2', 'example' => 'عُمْري عِشْرون سَنَة.'],
        ['key' => 'umr', 'arabic' => 'عُمْر', 'pronunciation' => 'umr', 'meaning' => 'age', 'category' => 'Lesson 2', 'example' => 'كَمْ عُمْرُكَ؟'],
        ['key' => 'raqm', 'arabic' => 'رَقْم', 'pronunciation' => 'raqm', 'meaning' => 'number', 'category' => 'Lesson 2', 'example' => 'رَقْمُ هاتِفي.'],
        ['key' => 'usrah', 'arabic' => 'أُسْرَة', 'pronunciation' => 'usrah', 'meaning' => 'family', 'category' => 'Lesson 3', 'example' => 'أُسْرَتي كَبيرَة.'],
        ['key' => 'ab', 'arabic' => 'أَب', 'pronunciation' => 'ab', 'meaning' => 'father', 'category' => 'Lesson 3', 'example' => 'عِنْدي أَب.'],
        ['key' => 'umm', 'arabic' => 'أُم', 'pronunciation' => 'umm', 'meaning' => 'mother', 'category' => 'Lesson 3', 'example' => 'عِنْدي أُم.'],
        ['key' => 'akh', 'arabic' => 'أَخ', 'pronunciation' => 'akh', 'meaning' => 'brother', 'category' => 'Lesson 3', 'example' => 'عِنْدي أَخ.'],
        ['key' => 'ukht', 'arabic' => 'أُخْت', 'pronunciation' => 'ukht', 'meaning' => 'sister', 'category' => 'Lesson 3', 'example' => 'عِنْدي أُخْت.'],
        ['key' => 'maa', 'arabic' => 'ماء', 'pronunciation' => "maa'", 'meaning' => 'water', 'category' => 'Lesson 4', 'example' => 'أُريد ماءً.'],
        ['key' => 'shaay', 'arabic' => 'شاي', 'pronunciation' => 'shaay', 'meaning' => 'tea', 'category' => 'Lesson 4', 'example' => 'أُريد شايًا.'],
        ['key' => 'qahwah', 'arabic' => 'قَهْوَة', 'pronunciation' => 'qahwah', 'meaning' => 'coffee', 'category' => 'Lesson 4', 'example' => 'أُريد قَهْوَة.'],
        ['key' => 'dajaaj', 'arabic' => 'دَجاج', 'pronunciation' => 'dajaaj', 'meaning' => 'chicken', 'category' => 'Lesson 4', 'example' => 'أُريد دَجاجًا.'],
        ['key' => 'aruzz', 'arabic' => 'أَرُزّ', 'pronunciation' => 'aruzz', 'meaning' => 'rice', 'category' => 'Lesson 4', 'example' => 'أُريد أَرُزًّا.'],
        ['key' => 'ureed', 'arabic' => 'أُريد', 'pronunciation' => 'ureed', 'meaning' => 'I want', 'category' => 'Lesson 4', 'example' => 'أُريد ماءً.'],
    ],
    'audio_blocks' => [
        ['title' => 'Audio Practice - Review Vocabulary', 'key' => 'B1-R01-Review-Vocab', 'file' => '/assets/audio/books/beginner/review-1/B1-R01-Review-Vocab.mp3'],
        ['title' => 'Listening Review Task', 'key' => 'B1-R01-Listening-Review', 'file' => '/assets/audio/books/beginner/review-1/B1-R01-Listening-Review.mp3'],
    ],
    'sentences' => [
        ['ar' => 'أَنا اسْمي أَحْمَد.', 'en' => 'My name is Ahmed.'],
        ['ar' => 'أَنا مِن مِصْر.', 'en' => 'I am from Egypt.'],
        ['ar' => 'أَنا أَعيشُ في دُبَي.', 'en' => 'I live in Dubai.'],
        ['ar' => 'عُمْري عِشْرون سَنَة.', 'en' => 'I am twenty years old.'],
        ['ar' => 'رَقْمُ هاتِفي واحِد، اِثْنان، ثَلاثَة.', 'en' => 'My phone number is one, two, three.'],
        ['ar' => 'عِنْدي أَب وَأُم.', 'en' => 'I have a father and mother.'],
        ['ar' => 'لَيْسَ عِنْدي أُخْت.', 'en' => 'I do not have a sister.'],
        ['ar' => 'عائِلَتي صَغيرَة.', 'en' => 'My family is small.'],
        ['ar' => 'أُريد ماءً.', 'en' => 'I want water.'],
        ['ar' => 'أُريد قَهْوَة، مِن فَضْلِكَ.', 'en' => 'I want coffee, please.'],
        ['ar' => 'لا أُريد سَمَكًا.', 'en' => 'I do not want fish.'],
        ['ar' => 'أُريد الحِساب، مِن فَضْلِكَ.', 'en' => 'I want the bill, please.'],
    ],
    'grammar_tip' => [
        'title' => 'Review tip',
        'body' => 'Use short clear sentences. The goal is to combine the language from Lessons 1-4, not to write long grammar-heavy answers.',
        'examples' => [
            ['ar' => 'أَنا اسْمي أَحْمَد. عِنْدي أَب وَأُم. أُريد ماءً.', 'en' => 'My name is Ahmed. I have a father and mother. I want water.'],
        ],
    ],
    'dialogue_ar' => [],
    'dialogue_en' => [],
    'listening_review' => [
        ['id' => 'lr_1', 'question' => 'What did you hear?', 'options' => ['A' => 'My name is Ahmed.', 'B' => 'I live in Dubai.', 'C' => 'I want water.'], 'correct' => 'A'],
        ['id' => 'lr_2', 'question' => 'What did you hear?', 'options' => ['A' => 'I have a brother.', 'B' => 'I am twenty years old.', 'C' => 'I am from Egypt.'], 'correct' => 'B'],
        ['id' => 'lr_3', 'question' => 'What did you hear?', 'options' => ['A' => 'I have a sister.', 'B' => 'I have a brother.', 'C' => 'I do not have a brother.'], 'correct' => 'B'],
        ['id' => 'lr_4', 'question' => 'What did you hear?', 'options' => ['A' => 'I want coffee.', 'B' => 'I want water.', 'C' => 'I want rice.'], 'correct' => 'B'],
        ['id' => 'lr_5', 'question' => 'What did you hear?', 'options' => ['A' => 'I want fish.', 'B' => 'I do not want fish.', 'C' => 'I want chicken.'], 'correct' => 'B'],
    ],
    'mcq' => [
        ['id' => 'mcq_1', 'question' => 'What does أَنا اسْمي mean?', 'options' => ['A' => 'My name is', 'B' => 'My age is', 'C' => 'My family is'], 'correct' => 'A'],
        ['id' => 'mcq_2', 'question' => 'كَمْ عُمْرُكَ؟ means:', 'options' => ['A' => 'What is your name?', 'B' => 'How old are you?', 'C' => 'Where are you from?'], 'correct' => 'B'],
        ['id' => 'mcq_3', 'question' => 'عِنْدي أُم means:', 'options' => ['A' => 'I have a mother.', 'B' => 'I have a brother.', 'C' => 'I do not have a mother.'], 'correct' => 'A'],
        ['id' => 'mcq_4', 'question' => 'أُريد قَهْوَة means:', 'options' => ['A' => 'I want coffee.', 'B' => 'I do not want coffee.', 'C' => 'I have coffee.'], 'correct' => 'A'],
        ['id' => 'mcq_5', 'question' => 'لا أُريد سَمَكًا means:', 'options' => ['A' => 'I want fish.', 'B' => 'I do not want fish.', 'C' => 'I want chicken.'], 'correct' => 'B'],
        ['id' => 'mcq_6', 'question' => 'رَقْمُ هاتِفي means:', 'options' => ['A' => 'my age', 'B' => 'my country', 'C' => 'my phone number'], 'correct' => 'C'],
        ['id' => 'mcq_7', 'question' => 'عائِلَتي صَغيرَة means:', 'options' => ['A' => 'My family is small.', 'B' => 'My family is big.', 'C' => 'My sister is small.'], 'correct' => 'A'],
        ['id' => 'mcq_8', 'question' => 'أَنا أَعيشُ في دُبَي means:', 'options' => ['A' => 'I am from Dubai.', 'B' => 'I live in Dubai.', 'C' => 'My name is Dubai.'], 'correct' => 'B'],
    ],
    'matching' => [
        ['id' => 'match_ism', 'arabic' => 'اِسْم', 'correct' => 'name'],
        ['id' => 'match_umr', 'arabic' => 'عُمْر', 'correct' => 'age'],
        ['id' => 'match_ab', 'arabic' => 'أَب', 'correct' => 'father'],
        ['id' => 'match_ukht', 'arabic' => 'أُخْت', 'correct' => 'sister'],
        ['id' => 'match_maa', 'arabic' => 'ماء', 'correct' => 'water'],
        ['id' => 'match_qahwah', 'arabic' => 'قَهْوَة', 'correct' => 'coffee'],
        ['id' => 'match_dajaaj', 'arabic' => 'دَجاج', 'correct' => 'chicken'],
        ['id' => 'match_ureed', 'arabic' => 'أُريد', 'correct' => 'I want'],
    ],
    'matching_options' => ['name', 'age', 'father', 'sister', 'water', 'coffee', 'chicken', 'I want'],
    'number_recognition' => [],
    'category_practice' => [],
    'listening_numbers' => [],
    'complete_sentence' => [
        ['id' => 'cs_1', 'prompt' => 'أَنا اسْمي ________.'],
        ['id' => 'cs_2', 'prompt' => 'عُمْري ________ سَنَة.'],
        ['id' => 'cs_3', 'prompt' => 'أَنا أَعيشُ في ________.'],
        ['id' => 'cs_4', 'prompt' => 'عِنْدي ________.'],
        ['id' => 'cs_5', 'prompt' => 'لَيْسَ عِنْدي ________.'],
        ['id' => 'cs_6', 'prompt' => 'أُريد ________.'],
        ['id' => 'cs_7', 'prompt' => 'لا أُريد ________.'],
    ],
    'arrange_words' => [],
    'writing_tasks' => [
        [
            'key' => 'personal_info',
            'title' => 'Mini Writing Task 1 - Personal Information',
            'instructions' => 'Write 4-5 Arabic sentences about yourself. You can use a fake phone number for practice.',
            'placeholder' => 'اكتب هنا معلومات بسيطة عن نفسك...',
            'min_sentences' => 4,
        ],
        [
            'key' => 'food_order',
            'title' => 'Mini Writing Task 2 - Food Order',
            'instructions' => 'Write 3-5 Arabic sentences for a restaurant/cafe order.',
            'placeholder' => 'اكتب هنا طلبًا بسيطًا في مطعم أو كافيه...',
            'min_sentences' => 3,
        ],
    ],
    'writing_title' => '',
    'writing_instructions' => '',
    'writing_placeholder' => '',
    'min_sentences' => 0,
    'speaking_title' => 'Speaking Role-Play Challenge',
    'speaking_instructions' => 'Record yourself for 60-90 seconds. Introduce yourself, talk about family, then order food and drink. Direct browser recording only.',
    'self_check_min' => 4,
    'submit_label' => 'Submit Review',
    'submitted_message' => 'Review Submitted - Awaiting Teacher Feedback.',
    'self_check' => [
        'introduce_self' => 'I can introduce myself in Arabic.',
        'say_age' => 'I can say my age in Arabic.',
        'say_phone' => 'I can say a phone number in Arabic.',
        'talk_family' => 'I can talk about my family in Arabic.',
        'order_food_drink' => 'I can order food and drinks in Arabic.',
        'combine_topics' => 'I can combine more than one topic in a short speaking task.',
        'understand_simple_sentences' => 'I can understand simple Arabic sentences from Lessons 1-4.',
    ],
];
